---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: calibre-web
  namespace: calibre-web
spec:
  interval: 15m
  chart:
    spec:
      chart: calibre-web
      version: 20.2.8
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    persistence:
      data:
        mountPath: /books
        enabled: true
        type: nfs 
        path: /mnt/AI_Storage/Calibre_library
        server: "10.0.10.10"
    ingress:
      main:
        enabled: true
        hosts:
          - host: calibre.aivallecrosia.com
            paths:
              - path: /
          - host: calibre.cloud.local
            paths:
              - path: /
        tls:
          - hosts:
              - calibre.aivallecrosia.com
              - calibre.cloud.local
        integrations:
          traefik:
            enabled: true 
   
