---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: wordpress-stag
  namespace: wordpress
spec:
  interval: 15m
  chart:
    spec:
      chart: wordpress
      version: 9.8.6
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    ingress:
      genea:
        enabled: true
        primary: true
        hosts:
          - host: genea.aivallecrosia.com
            paths:
              - path: /
          - host: genea.cloud.local
            paths:
              - path: /
        tls:
          - hosts:
              - genea.aivallecrosia.com
              - genea.cloud.local
        integrations:
          traefik:
            enabled: true