apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:wkT3UZ8RY86C00J320k+M2Rlm/RdaZSluDp/1VSsUVKgfcexBH+pq2d8x/epBcU5C9Qaqgh1Cr07znbEcbTADOE=,iv:c5ZOff44FpYFy+Z6ss0Yqi3SB57ZnOnH8F5OeOtsPhY=,tag:lMwWUTWJ7TbDqVmNnULCZQ==,type:comment]
    #ENC[AES256_GCM,data:f0HdjGT28RvwXqquskheVZsfTQNhYlIN14d7/G9IkAs5rrNPsNrQYHEaRrk=,iv:L8oqDDJV/wyxUZ9obL2eC1I94TM4+xppqe6Bwqe375c=,tag:RyBQ4MHp40Ek3m4h4tI7Gw==,type:comment]
    VIP: ENC[AES256_GCM,data:f0HBQCNpWDkoOA==,iv:yD6muBTj7OaoOpYGT2wdpMGLoh6lj7++reH0MIptXDs=,tag:e2cyXzkx1IGEyX0RlKJiKg==,type:str]
    #ENC[AES256_GCM,data:sBqNDm18grlQyc/eENQ7WV5V9WzWMT9NwaRu,iv:ER5uI79/nUjLHwHpXlpuyLWoehMLCpQXBqPJ/BNmW7A=,tag:yClNe/YlAtHCcQZGfqJydw==,type:comment]
    #ENC[AES256_GCM,data:IzImz+NXSj6BANSbGdTBRrFM6+G/lAHL2FrE2BlCdimONJDzz77qnnCNeEuLbxCR8Nq82XSn0RSAoZt9llm/FJBBUWo1HSLgUKuQximEAp46Ezlfl3kmU+k=,iv:7sXieaCMRdjJbQZt2gB4NMtsC/ekR+p+rN7d0xHK1LU=,tag:ftcoZhrWHCHFBwF/3VOcIg==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:89pTC2MNp+Rycg==,iv:L+/5T7ySiN0za2qx6/G+Vn+G/7pwNkjq65CCuKLJZWM=,tag:4IAm9L+NlMgF7chMlG1v8w==,type:str]
    #ENC[AES256_GCM,data:ksinQhGe5IzHfyPbCyWHNERVhMKzjVDj2jr2rh6D+WK7Ag==,iv:mCK1ZiIi12yPDWEJ0TTTuE00I7MC4YP6y2cCTa+mW8A=,tag:l4PNkcfM3mGpz6jboaTcnA==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:gn2qABxFPobc,iv:10KlH10ELCYipQ2yVm+kBhmcGtrmZKQv86YSWe9kEcA=,tag:OQunfN7giaZzRGHRur3HSQ==,type:str]
    #ENC[AES256_GCM,data:3ow2fwOci2013NbQeXAhXAHWXuj0ffehYA2bqUliDahlKnLv8RP/qc4bSSMXyb8=,iv:dizRkd4obj4jiTVAr1rGyjHuQBs9dm/PrUFLaAM6EPo=,tag:p04t+ewaeiMsYFFdU5FFeA==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:LxWGY87O2eG6VRUMQzWTUW8f0LYOVQ==,iv:vweQuN16xqLE+Pab/9GeOHMJP3P35yq8VtPnuTPK3fM=,tag:DqHVJ9RtWOh9sFDMgv6Cfw==,type:str]
    #ENC[AES256_GCM,data:IAz1ia5U/2XyVKIx3Hqd+0qWkl+dG96dvCLMYLE/qP8/Oxkg6y2x8J7DtavmSs1tBu2kmlnAwLe9wErKbvQ+hs0c4cvQUc3myPJL2LPI+SGf5g==,iv:k+UfeUaRGN2H7C8/XAUQFCR7mI9Qgg/zAvVIITENZN8=,tag:cReyC89+nifMhSr9cjuexg==,type:comment]
    TRAEFIK_IP: ENC[AES256_GCM,data:yUoD70YQkJwHSQ==,iv:r+wqNjU2AYF2q9KfzgS4sN/EgJACUrfQhFMr4FuWPjI=,tag:dBqJfPvfKaHiDGJdB8Fgmw==,type:str]
    #ENC[AES256_GCM,data:uU+lHNIV4OjPHADBQqlusc5Cp9JE7IYQzyt/6fy6itiK,iv:V/IcCfwNotxiFIai6xxYrM2tNb0qsd9QY8idXaOoM3k=,tag:qQV+u1C9TeLUiM88ensoqQ==,type:comment]
    BLOCKY_IP: ENC[AES256_GCM,data:CHA49I9hI8huaQ==,iv:Usuo3Zd3VxXCCKTHtBqH3/mWtTgG0Khg7/BZg5uk4to=,tag:5u8gd1oMd1Nk9SM51YmSzQ==,type:str]
    #ENC[AES256_GCM,data:u/aq9+9ylt6bQ4s347WnlqFNBUrW0xh7NYmG8FVU9N+dn5ZC2BE0CcdPYtQog4IE/BNrx56tQX6rpkUw3Hvm6lMlXmBfVGWok24PeY7nx2s=,iv:QfXBqnD5q2DQtRhBsDAEGtub1iz3goXZ84h5xpQYfvM=,tag:7joD01TFwA4zU48xZ2n0Qg==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:eqg3tkBMcQpPRA==,iv:6va6m+Gk3MFGzYw1ZBDEJCk6Md6bwKmV0cfa43lnvc4=,tag:4HJC47UBj+1Dm48ab12ZMw==,type:str]
    #ENC[AES256_GCM,data:cjrhR/M5q0jUmqlNAL0l2z+YDzabR+1jqoE3oJNYBXdr459WMy/FneVDEjSPvcMjsF6EO1O8gwv6pXPN/wIRjWLaaLoYBYkOSQpt/Ha/uq+08SANL4CZ,iv:EZ8RKh6Ah1WnS7MH3tGU6N2Cv2lqy0zK4rHJ9PYv/U8=,tag:FKIAUXYUj2sILlhehMxVnQ==,type:comment]
    #ENC[AES256_GCM,data:9NxEwKQcaDGa877CRl9Rp2wF8mje0RTfqUnOmUQlXinJHVlVaZvo+AJfEErtcCBS5lZLnOyOTf3MvHdJpi0DVAEWOb9NhtmUVzv+CMi1MKYErfz4I/uJQlZ7s3w50c2rVNo9kMLgWOxQOCQE/Q0E4mHZjOS1dhgLfo/mbQ==,iv:RJ+uFc1bXxp3kVwOX7HGbTjFVm8TiPRaMDS/VTlEA6c=,tag:/v8tzvW+27gJIfkwDwRBng==,type:comment]
    #ENC[AES256_GCM,data:fIS75iiChwj9nq7YgSt9bE3L7skjk5hqzG9yzImTKHasxMCUFyn3lhdUZwBlKktAZryeePtDFdfXf0sdyUsuOO/tezFRlu5wNrMJa+HtsMw=,iv:/aN4qVdsIw0TKCRDN7ULQmLon+Q1QcpaRIfsHIhc3s0=,tag:CB6N9CLwBmjdjymtpc5ETw==,type:comment]
    #ENC[AES256_GCM,data:wjNCayBmb5lb2cTu7j/1JR9p3ZoYat/Bc2Z/UIizlKXvoJcNQRXYi1kEMCmNN8khNsz+I5qu,iv:FkSmhxB58UAXKCfvXzNo0QBCUd8WK0VAw7hdlzj901w=,tag:RfPcKR9sZm4u4gnXEGAwYw==,type:comment]
    DOMAIN_0: ENC[AES256_GCM,data:wOjRke0q6/U0U8/Y0QrMfkM=,iv:OpFLXsGPVQ55sYqj/9kQoJpuBgiZHQDGsE96BBWZcl0=,tag:oXGXl8sQQbGhaRMWRN/zvQ==,type:str]
    DOMAIN_0_EMAIL: ENC[AES256_GCM,data:vPewyWWDsvB7j3xfS6Yu2p+njH9KKA==,iv:Cf0JmgHew3j1XywAqiO0zmyu+x9StzXHYlSMJhDU1DA=,tag:dfFa7xb3T6QB3rttcTrj/Q==,type:str]
    DOMAIN_0_CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:EL06noznsELTmNBN6G03YHFnF/lKdJ5zEg349cKO4Bp2Kz5ypIWlNA==,iv:BqJzMarskMl2kiARi6dSChcC/2ZsjGZkDposiolUhYI=,tag:yUVUPNKvaqeeqcBDsCBuGA==,type:str]
    #ENC[AES256_GCM,data:MDiwYzYX6ypY1jdwEzN7r1Olyjraku9oafDcwsCuN16ujOPligN28CX5bcSYyaU+AfpTqhuXm6s=,iv:5Ff2deDeCAZqzf/JheHzmRpUgML7/mnuuAVb3um7mug=,tag:qMZCQmTsrdYA00SI+7gPFw==,type:comment]
    #ENC[AES256_GCM,data:fP7OugVXvqLUcrOOEblLV4DF2PGxNWKjKQ==,iv:SKwywQFellkTf+3S+xMRpdzmyYdxWFxjynnzi6575ys=,tag:1pyOZXvGifP8nEZSU7Cxyg==,type:comment]
    #ENC[AES256_GCM,data:PWeMvoagdhHY7sGfJ2Q6y2iW1IKriUlt70n5tM0ni3BAH7nna3M3BqKyZvbZuzrCEop3A+exfKpPij5EW+8h3NULCWwJEjMtWwsX9+o=,iv:XZlC1/aucIuyDA7pr2CS2JJHwnFJUyHMp5WXNEKPhHE=,tag:bzXppNO67jm14e3gBNvGyg==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:wxEGPlB8SS7mii49ZZXkKeasSnC0ItvPzbB0iRkGQqK+7bBOSYBw5iySADRiVhSqZkVhDmtJpX6VDg==,iv:L45p2oDHmpXaiKvCcE/Rr7vTJu7J6TbeAMKQgunyUQ8=,tag:/bmOHSLSExRkC4lDgJ+xGQ==,type:str]
    #ENC[AES256_GCM,data:oO3Gzp0r+if9UOsBRe4a4GPYj4arrPbsrKWervETHQHVuJ5T1/SjSvofy88AW3IR71VjgqxTbNUqZhU8+RUBDyrMTvV8i38=,iv:PGInzn0bT+J5ce1RGDGSquza4EUXAzrtd4wbKJgv0o0=,tag:HTQH5XPj2JEtTx8jYr09yg==,type:comment]
    #ENC[AES256_GCM,data:g1nnse2a76uA1gWBPoOwVeA0pqZ6aAxlmj9w+QUImOYFNUyEBPJCVaGYEWg6xkIqZ6NkSL5K,iv:9VNujEvkzBK2uNtdi4w3YxKNir900gZ/4C68QGqnUZ0=,tag:uN/ODxw4s6n2Hc1c9CzrRQ==,type:comment]
    #ENC[AES256_GCM,data:PEt0bb624np8sjnbswx0938PA2YctDLMxyd8FH4RduTe7Pc=,iv:NWuG+vNLDp6kucspNYcO++4aUgA4NhXvTVGCY3h/yZw=,tag:3uYJlmfzRYtkYV0RUsvdpw==,type:comment]
    #ENC[AES256_GCM,data:ezlEukhASYGvJ1xFMwrKHN7B2W2I2FhPacVYXTvG5zJHXvSj4IdG,iv:pNO84BEKAdpafMuAmCQ4E0hsEof7r+p/vi1SzlKN7a0=,tag:spMpKsqZTmKT7UurXboLvw==,type:comment]
    #ENC[AES256_GCM,data:Axs0i02jHiTPaW49+m4=,iv:LJBY0/upHYrpqqOBTOdESna5mSBh7bVorYiCD2G3DLc=,tag:mZ67U7ffX3CtoSTNF8MV/A==,type:comment]
    PODNET: ENC[AES256_GCM,data:sSnahLdKeUPOvBpweg==,iv:fJ7kQW9rT4EW6uJ+UwpucLW8j92D7I6BkFq0wKX3QMk=,tag:PE8stXzEGcaD12fBSf9/6A==,type:str]
    SVCNET: ENC[AES256_GCM,data:3VKrtKgDTDsftqcNvg==,iv:HhNwevIlLMcdu/0X615s2nB782X50zoktGY+OyZYTwA=,tag:rdKUcIz0Of68wYEmP833mg==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:OYXwog==,iv:4Z1HaImqNJrVr1IG6jxaKhtGdDPxmcZqxdHpyZBz8xs=,tag:AliMcgGwxdzAfwRVgE4ALA==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19wg3490scy7jf9srcmzskv6k96nj9fx77psdqkxpt3lg66j3fcys4xndsq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1Z2pybG1mMUZVekltdXJk
            S3ZqLy9VNVVzMEtsYUxWSDA5VWJvQ041THh3CnRHTGY3YzZPQ2ZjbU9uNGlGWE5T
            eFQxeDROWSszWDNmS2JkUDFtNmtrUUkKLS0tIFZtL0p6MTc3WkFCM3AvaHVsOWZX
            VmR3QS9ZbEVNUGZ0bVpkd3UzYjlPTzAKpYRQHjVCT9CDr9+R36gmRxJrLxa3FfJC
            IS6FV4b36/C6Ro6MUQxvhyz8qIpxXfMUxiosILL5ZkHAhSyay7wGsQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-22T18:31:05Z"
    mac: ENC[AES256_GCM,data:9kIyvlMj6KGPYUMSxuh9b0tolTqZssPGlpO9ur6z/779VpMtwu2E7deu2uMgPmuYxinU76P9KnXIrZ+dQKajb6apc4/sDXPc5AaYcwRjIIUpxnIMxm+58SuShdXrun64ANXmf4P2lyljVfZ23zFlCvpZmBYGhnTjVhe0JWLT3Rg=,iv:Njg0WWxd+D3JAN6wm5yNlog3UD2IJiNvdl+Ycz4Z0XI=,tag:wZZUztnSitkUg3KlOhL05w==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
