apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:pfb9rnsJGRqmqJD03l/qUsQxOj3ya1u7tQ1epTAPE+caRSk7ryz1c1i2ZBm0plqawFHb6LniMEKtC8S1vk3UqTg=,iv:/5DZRpD6reexxJH6goqHdsi73h3DY3wFgGih9GL4LI4=,tag:vfZfM+ywSXC1r+6zhFQz9g==,type:comment]
    #ENC[AES256_GCM,data:4G5heuW+AOYNJFp4xmj9f/zKhhW4Lvlx039QowRDbqg2WDukutaWMQ7fU+c=,iv:4/gFQr1XVXVNUATxJtB4RyT82ypl/bmTnwqV0ZA27+M=,tag:StwVZP+a0rI7FZXrHxVFpg==,type:comment]
    VIP: ENC[AES256_GCM,data:f+JaS75GEYkGdQ==,iv:Mhlc9v6cYAr9V6Ip9uZhutVHqe+vfKcQBT/C28eQRVU=,tag:3GrMEqo9yltgP4QSp/JN/Q==,type:str]
    #ENC[AES256_GCM,data:hFcAnlijwnyCi5wuTYt9tEDRYPwRDcIwchm+,iv:4m44L9pimtfKcUV9DNwQbPX4Y2YmNAoZjG6OqrcbBAM=,tag:o+CplriO9bBqMLy4oJIwJA==,type:comment]
    #ENC[AES256_GCM,data:g0GrU9h50czAs1e3tFLXhfsJjmlzA3fzRLtP+BFUr7rVpniPJPtizmrsK1++CqOyLAvMGq1BGt8NfnHQEtSvEiSbGPtqHD2gWgx0klTOFQSXawnZP9X4Ko4=,iv:z1Fd1I6owfZxHI1oAKq/QC7TtvxoZQeV/LMtdRynvto=,tag:KSCNxUoeDAFitfbwB10HDg==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:SrbZV0AOc8xqMg==,iv:ZoQvSHqdPGnBW0jTAD2je3ePb2x1f1UdLL+meUjpT4Q=,tag:I8or/4D60NNks1eEvORnLQ==,type:str]
    #ENC[AES256_GCM,data:dMUpBZw5P1PNNM6hFyoP4FFgyKJ+gieVeiaRif8IqB9tgw==,iv:YNnmG5WaUrq2kqjWM+wxba37X6Nvh7tSmPnoHbKbfoM=,tag:z0CKJVWMQdSWofe88yCnQQ==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:F9ZRnu5XrV3a,iv:AWKWFZEyPLgyRyHdSGFGG2G8U7mn0/gxkya/hAD12pg=,tag:nFQq9Ko1TJLPuqE3wnm7MA==,type:str]
    #ENC[AES256_GCM,data:Y2NvSBOMQ2g7URbKsG/cYkJeU11yJM+t06WA7HYVTZAPvPI3a5Q2YKkPt96x6Ks=,iv:+w9og6A4HZ3fdD1syPonLjNrrfM9yK2IRy8LjpnUoaU=,tag:+ZQvGTVZvk86igF44BrJZw==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:eH+MZst1jxdLFntLezlTccHF4qy2WA==,iv:jf0iTwfXrB7AqNK0KtqiYWe24As0YaerrwH6L6y7ugw=,tag:10GhHDm5MvH6ABKj3XUo3Q==,type:str]
    #ENC[AES256_GCM,data:fDaeEeuBZKcl8xqg1TjLHwIt1lUD4PPm8DNKXFoQfDPqK98vjwuwEqQb9m5I3X5WqAXJRvpFqM7mnSwFFp+ED6uCd5E4OVD+HH+Ic3JiUdqChQ==,iv:G6jBuErukbvE2EG1NB67iRzKnqhIAthgiW0qwOwQg6c=,tag:P/8P01vosKklYlPiMZsCSg==,type:comment]
    TRAEFIK_IP: ENC[AES256_GCM,data:p4InQgYVT7TrAw==,iv:Vl37O5fal8FT+IgA3syX3yIADHtdbzIBgrQ/WmyFjl4=,tag:GzXpsbbv7Yj8r2QZIrUStA==,type:str]
    #ENC[AES256_GCM,data:5DB9OOSCjUeENpLGVdNkq3Dc8bhz3cuu2rvoT9YzPBXh,iv:fATmZDIeJcGy04CtfBMopKdOhBe8cjocfZc5yL1+5T0=,tag:dZNcxGJgO7ZI0oO5ysdaNQ==,type:comment]
    BLOCKY_IP: ENC[AES256_GCM,data:H8yfH/7Ixw6bJGlfa9w=,iv:9ZDwKC3H1i38mcAoPRG39ZPlNpbcC2WMYJ8AEkGaDBU=,tag:piENTqTngYP67CqXu4NXHA==,type:str]
    #ENC[AES256_GCM,data:2f5unk5vH0B1cxKatzFIH5sKNkmzZcA/6naGxVWUQSCBAHr6OmKvQjWd19ROVqzs7a4IVGRwsCCD4pDCUvLGXxhQYjgY9NcwoyZ1qbhK9qU=,iv:2l+gCxpbUEE/NZdz7Ypd9A7QeXCsV/ojnk7l4J6hj0I=,tag:0A33qj7W4C/byHfkLTiMIA==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:68Gx8ZR4MfImPwY=,iv:B4vJ6uR5Zuy8zoyy2b409C/uCtoeG/xPiTPqDPsi+y0=,tag:gnqDTyrNhuU4k3eTh+ILTg==,type:str]
    #ENC[AES256_GCM,data:ktCqP7RJoGrBxvoCtuGoI4jnIhgNXjJeEg+rGP02Q0WjSQgm2omZct3XA8ldFTSkLDbp/8C2eorgtvvGw2y9870FTLjg/luk4p4SKz9O2/W68LA4BzL4,iv:PXBjSHdkTtd3dkYPcMxXiarvd2V5oq4FfHiYyFo7BN8=,tag:RA+0ltKKka5ehwY5FjQahQ==,type:comment]
    #ENC[AES256_GCM,data:mbIDPH6TvNdG0+OXzHEgClf23HNBsI8LxajKhdQ8ElIY2XfX0S6Co++Cr9egZ3NhLjVg14CD2zN1gYAHswYUdX2t7x9gBED2T053HufVMY0vKlG5181uq3v8JADNSvHE+YjPCBjhI0vDCkDSS5F3OE3M+/tNDpuhU0EaRw==,iv:+nb6a/Uv5fKvZSTfyJFUgQj+kyibvwGhtyM1E7+dCe4=,tag:7BUb4YL0NJsFnPEzlR1Mww==,type:comment]
    #ENC[AES256_GCM,data:0MRGzWdhDgm9roG/MrCeRO/LoQntpemh2tIZqlfyrYtfMmCDgHgwRBKKGG08HjC+IHkZGpAdoaFUgBnNddj4HjF2cvqYoJmuHbZyQ+5Zxos=,iv:HHL/HRMJuv0E1zQVvGiWtVdH6GME5MNVeuFGJ4xnaI4=,tag:/BfxMT6M+lTOBGjha/8XLQ==,type:comment]
    #ENC[AES256_GCM,data:iWZexvLEVmp1qUyPYCFHJfFHLlPpCa8cvvIc6a6NbyEf3tpQvwyswuaajEVv5ORqT0DgGJlu,iv:W8AyrogmV4mW3sOj0LiOLVCu5sqxDh7hsZy21Nvon4I=,tag:A8+jhLJGmfPY27FEzvxpng==,type:comment]
    DOMAIN_0: ENC[AES256_GCM,data:g9BqoweX2Bi5hK5jxGakjS4=,iv:OMLGFVkrgTCxRzM9jmOnVYR2M9SpBrwicqZMc/aoDWg=,tag:IsCn9SdZ4OINrizd0B5USw==,type:str]
    DOMAIN_0_EMAIL: ENC[AES256_GCM,data:rM2cFQCBtlfIqpQgOoa2o7Uwmx8/YA==,iv:S+t2c6bAoeMEewruPs9JUJVOB6HNZZFiq0mvv3sOSLM=,tag:EpTHTdzOsbWebZeMQX/9sQ==,type:str]
    DOMAIN_0_CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:613tvQ18YfI4OeG9/YD+sUv1UYEJ69UEdbYa4xGNNPLrXv6PtzBh3A==,iv:73v84ATlgn4OjC0fdLj7ui0EbN0X1Q+d/PL2xeLlxmE=,tag:rBz9Wp73/S9Myu2hDnVghg==,type:str]
    #ENC[AES256_GCM,data:R0H27QbKxBtc96XQvkR3RZHHxDXxd3PMjfEDYhSTpiPc9mK9Ipx0sTCEl3bWHXRSZDeoxQgxKAk=,iv:sBM5xQv3e5qwt9zpulhUVNrEgT7pEtfq0cUJOjs3NZg=,tag:U9OPB1tM/+6Hdm8H97wm7w==,type:comment]
    #ENC[AES256_GCM,data:KDK3WiHd69q8L5L16RJMV8dgIAt8tKrDGQ==,iv:FJxSiIO11W60E5StOC+Q4VUgPbG1sKUCVYMN25cXBHg=,tag:sdN1xLLjmv4miGw78Nq0VQ==,type:comment]
    #ENC[AES256_GCM,data:sf9JAzrfcZ5K+ZHefeqIGgXpoO2wJeMl4XCRfF+4YKmfvvH0IjM/VpTSKACJzqNdNkHOeAntPJFdGLyMAh4+U0t5/b1S+bpWvmD+hXQ=,iv:JW5Jk7+CzRv4iFXdPBB04Lnp9Lg5t8bciWoNnuO23nQ=,tag:k1KK+2qFn3CzSHavbgwgrw==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:nnAmMiaiQU2fRkN861Jw0vjNfxhGjJA6hjxNwyivNHMUBAve9MVHmc9PffKw0aclidm4qT/XEJmrKA==,iv:iwEo+hqKdHsqIXDKHnX54eJRi8h2e71jlNjQD4ciXT4=,tag:Hy7Jo0MmHdl8zUVIuzj2IA==,type:str]
    #ENC[AES256_GCM,data:lQnXhsLznBOfqyvXANIEn3lJxl/jpgwWABP+O+pc//+0qbIej2FkLt5v4xXq455eTUA4bQn0tZmfx+ttihmfCYw527Q/yzU=,iv:QMe3NtZHMjqu1rwNZ471toQIvnJSfDSgcUDTEAKixo4=,tag:0bkavP/RtQAPduFgj5H4hQ==,type:comment]
    #ENC[AES256_GCM,data:aN0LPRf9bfuoz1NYCsplxvMWErxzyMMi7Jc5WG7tsE+7adqBV46n8fdivIkG8elNbp+1VmLz,iv:fBcLPhhqFfgMkNOaFUQjt9haNKWj5g/zbbZ4XUBOlEc=,tag:adrUkypm7yh34vvTbp0WSg==,type:comment]
    #ENC[AES256_GCM,data:a10nfYZFXXQFSg/NzqCaljUk7q/VkB5tBbzYu39tGla3J5U=,iv:N8PdbEUOiTo0PwqJmfb+vETCkMsu8Zc67I9yc3ilYTg=,tag:gnEy/zi9g+rzrYFOws8gbQ==,type:comment]
    #ENC[AES256_GCM,data:yzMHOxCMLfVrzOaPK24n28wNrPAi/BNbdkPmM9+T4pwUP5wDID9B,iv:2ivyQ2O6HSkB8owfr9PACW+VuPSe09e5mkNkcafs4hE=,tag:WFBZAPjs/PEG593RIs44sw==,type:comment]
    #ENC[AES256_GCM,data:ope9+yB8EyzAs512qDk=,iv:hkwitZHGftk1Y4XUWTCItcy9LNExxqDvJhzcsQLpdg4=,tag:+odRb/RMWY7BCpfG60llGg==,type:comment]
    PODNET: ENC[AES256_GCM,data:P9yz3BWSybdWxlmnjA==,iv:EYxlntG1Sp952MRtFOimhBfvSu7DcIhZQvkJT+nYeNs=,tag:2sW+M2zamVMZTSXNDWjsqw==,type:str]
    SVCNET: ENC[AES256_GCM,data:acZ+SFDXqm57niEx1Q==,iv:3SJhfwtcnmPlwiLABKK3k95WJSXDZKNlyTO665EQhGE=,tag:8L3yry52NEtmrW93lYvD3w==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:mIRE7g==,iv:jGk1Zn0/tELxPMAQ5ujfhmTk/fgxb1AOtHxP5pCGoMo=,tag:aCKHcGKkR6OVnex6DIT9fw==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z7h4mstndxkualruraf3vw8gugzzgulm8yzkrq70d4kjqd5yaqssjwksf9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPcEVFeUU2c21NblF2QXpF
            Q2tCenlwaHRqdnFjTVUzb1l6RDR1ZEFRWWp3CnVKaFg5S1F6amF2MzlXbG1QZGZX
            V3VLUlU0c3p2cXZ3QjFuUmNJS3hxNk0KLS0tIC93MCtLcnpBKzkwb29VcU5laEp6
            bjgxQWlKK2twS0ZLZmRUUHV1QW9NWjAKP/y+fpmcjZnaK9eXbb9bY6kD0txsIAOj
            a99cOaAC2QBoTxGmTd2VL1xVeADXMrlVPLEQydNLbajWLhgqUM4uXQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-21T16:49:12Z"
    mac: ENC[AES256_GCM,data:QOtD8ZPKweyhfpElQ3BSO/A/kzrXBzw987CpnqB3+g3LLMjpDbTodmVlDw8VybxIX3MrLeekDyN1Blu6O6akXxMF+g/Yhci3MBksLkVyfGUijJ0WqmgejS+eJPxKDs44MUouD/0dtnXds+eXCCR4YTRaSZ3v81WhmH4e4ET2ePE=,iv:cPrG+rB8Q1aKHGMFAh/QdpGXhuFVsZa2eNYb1iaDP2E=,tag:aj6RzO+PL5A9CV4q6Jaleg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
