apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:CuewkB1ExmpzBnqkBYmRfxsi0sY3dpOGD++vpyjWU49VGjeDiI5+q878lVx2T4KBJ5zBr+5nvIW5iE83OJC7RFQ=,iv:gMQbw0ejUIYT105FcBlfKIuZG7Q6S4fsKFphlMnn6hA=,tag:wDI0y9jzI2yKcywkeej7/g==,type:comment]
    #ENC[AES256_GCM,data:FQMTl36dcXD7YbNXa/FS30K670zm+A1lngutqTP3FHkB6W+v2ekq8xJuA8k=,iv:uyKeYx/CljoeD0S+PxtTa3yNo0cuUcGMwF9KjpwOtbw=,tag:V5Z1+E2W8FhkkQHpxoQmTg==,type:comment]
    VIP: ENC[AES256_GCM,data:TbyTgGo29iMxdw==,iv:YsZ01t1Qz2x6pwP4Oa9pJYiJFgAAMSW4rEAK+RD5/20=,tag:BmbC3coaYQYwMj0gRocxqA==,type:str]
    #ENC[AES256_GCM,data:UKSC7RFTc2SLux+ChKEUOBDCzeGBJK2bLyn1,iv:RhLyJGioUvAgF8amt5WezfI/qwqA8laUM48emY1D3bo=,tag:+hYtNuybnOVum6haSettlw==,type:comment]
    #ENC[AES256_GCM,data:qQRNOunzTQq3JPu4g2Hrkgb0Sf/bhDxgPPSYD3s1WH1kddLmG6JJSZQYWgq7/sXkRehu3omvgkX2x326JOuISUxTIIx3gmB1TFjK9XRqVfs/PV0jTW4vAD4=,iv:541XKy7iKsh4fWe/DlojMhpLh1VBFAgRFUUcpcR0X9g=,tag:EEtt64NIwRakjJ2iXKclYg==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:j5rEk2SBWTvqjg==,iv:rB0yxPxGC90QTeEVXmQJcH2aoSG6auq6rLXj319UBz8=,tag:sjFLZ8tovg8y0xT6GqRNFg==,type:str]
    #ENC[AES256_GCM,data:vPSCdZpddDVHQt1kuI2LMTJzaWQJKmlPmjrXWBG1Oeq4mQ==,iv:nMjXQx3p6FKU1FXds35HZWnSUPjPW8giOal41o2Smkk=,tag:OP7xIWYHS4StuVinj9Xz/A==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:nnscnsaqMgeD,iv:Mi2rVbkpgDeBec19caMQnneJ1vK559Y1FBd8CZaJlHc=,tag:mWtvp65asEnTUJcqE3yJVg==,type:str]
    #ENC[AES256_GCM,data:wn+98ZsZ8eefSGN6KMFv940DtqvkQbHx6CEs2ryU7sjNrbm+HNFLpWt6ZzQ5JMA=,iv:dxPMTHjgwnnP8DNzBnf0dBQDLpRLTlvUA4fGG/TXQiQ=,tag:TQ1cLdjKHNCeOem5OVjRnA==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:nnF0byr/u71Fu1umaXU9BkYAALsfLA==,iv:eYZ4G53CneBeypvTHRXKRejdxwWPZrzsj/CXG4OZ2DM=,tag:5VWtDFo6cx2oQdTNgaJ5uw==,type:str]
    #ENC[AES256_GCM,data:sf+Kkh6nurROop6vRwHpLGJxY91ekz+SQkvMS3NqJvayaV8zwNEdXAL+O4mfbnsoUZ7bRUjPgRjq0nsBpBsmPcjFj5T2ahQOHZ0fA99gB3Ls1Q==,iv:GC/Oz/gjRYNb3bSTyz8iKa1Bv14a0+DH5X6kPRZTSH8=,tag:iFL0aRJDk49+qJekPHxZfw==,type:comment]
    TRAEFIK_IP: ENC[AES256_GCM,data:/d0kO148sDikOg==,iv:loF6KyKp5EOwCF0xvgpj0nLmDXuArpWLBYmE4KX9+wM=,tag:AljI7In4qwu8vNagJdZl/g==,type:str]
    #ENC[AES256_GCM,data:aE1N+dvn4YDiF5eM82CYsLqiDJusKE1kTQbexv5Met0O,iv:/8Eb1du9UCFfPzBrY7UnuyGe5R+t1rPMNMO1oc7demM=,tag:r2O4ROPuExiRjAUd05l7Tw==,type:comment]
    BLOCKY_IP: ENC[AES256_GCM,data:+K23OHgCPc0UyA==,iv:ln+W3utXA+Cm44h6B0WbjBTzgxrAJlQCgQvSfKg60Vo=,tag:hqSVo4LGbLIC0jqUvXk7BA==,type:str]
    #ENC[AES256_GCM,data:PCEnfHEHC8zFGOuTb3vVeZsojW9E6myZAFdVn0cwVgqqes+2wudJIEa4/4IautoTTPm7ysTR27GZ2mmbo1sc8/6ZnY5qC1ImVNOh3cu6o9o=,iv:xiib94KXXqQcvDEhHlz49m0PZpjJ47KGbJ6LFcPLnOE=,tag:SasCR51+GYhXVOOlFOoa+w==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:Tcy2bKE287Tg8g==,iv:BaCWaem/GLpW3WfozHX5QQy6IvMaJ90fRb76ByUNBSM=,tag:2x+xqyAs3AhoS50HoqK5kw==,type:str]
    #ENC[AES256_GCM,data:owQIC+G2BtWScK2ChGNyvQ1FhKstN/debF3pRR2A5OrutGN8Qx2Nmspv6IA5dZgCKw4PNuvBs4v4YGwe+EQyAswE1SVjryJAi9oRGweO6d2JWyybLdXy,iv:GJn3PZQMjBnAzEXxwTtGact4op7L6o3reWmguIeUlGU=,tag:QxP0Sqa0hglv0zJRcergKQ==,type:comment]
    #ENC[AES256_GCM,data:sU/nFq2UjqhhnwpixFaH8/zzeutcCopxmpdgWk52qCKFR6jTEMVa8M3iEShOgszZvi9eIl0bbUjU5vxZCsOaX0uTjVfcCOtrvlVhyINdwzZNd6q6nuMrCqilyft2fFFqt45KMF8s/kTvfVUXfyIZ/AeoyW+bxPLbcHgnsg==,iv:pDVr6KurN9TSY9+c6FKXPymiEHI2a/VvqA1wuEw3c/U=,tag:CNMijo41j2EDpD5+XGJrvA==,type:comment]
    #ENC[AES256_GCM,data:zoRUj0OnqFMpkMPviRRhMpN6LiBf2AxYfBqql2XDVf9POg1/milpQl/vsYJfqL6rTb6+1VBBYHnufbaIhQBQD/05UczAHlP3jF2xCeTUmBU=,iv:LCDNhwrGQsn2sMo5Aeq0yrD7mPpjEOkoD6AESrr0wXg=,tag:X+6ioVyYo9AXgMBWTbraDw==,type:comment]
    #ENC[AES256_GCM,data:ae3EBftruQUQIMbtCceRMEegMM5Dhiq+qZWiBrhi5LP2nLQ+qsFrf85z/Vb2g7jg+8RzwE5T,iv:+ogcb87UqW+MlEx6B00wGwKVtSR1t5K1D1Y4PohWLn8=,tag:79BWYBocmiUGhA5dKuyvZw==,type:comment]
    DOMAIN_0: ENC[AES256_GCM,data:ODaTN5Nyrpx7ZcaOMIOip4I=,iv:0keHm1EFNor5L6ehrGmX/bpfWxDDjKnNWMzZi8/0cTM=,tag:bJkrVj5t5PAk96x07uRV3w==,type:str]
    DOMAIN_0_EMAIL: ENC[AES256_GCM,data:OK/9tLnew+rLmjdsZDxL8lrLHwKhhg==,iv:EvVl4n+oke5xzYhdZ0BAhfsCfrRkg6HhlMAt22a1Gts=,tag:oqm0wfRGoqdWB8rkwPFjFA==,type:str]
    DOMAIN_0_CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:Z8J9I+7/c2r9JKodLHoQqSbwQdtP1pKNd/61bMZBTqgdUPti1B1ifQ==,iv:oxWw14OGiuV1Tx5JHM6BLvRjdvRCkw7tTWTfvrZGCPI=,tag:SjHaA5fBNn6DrrrMCWdr6g==,type:str]
    #ENC[AES256_GCM,data:DsmA7hiZ4Jo2Gh82vxMNeIMCDOii84q3PONEyy8S4jMEFD+vvPClIarzT1E5UNY2Asdi44AHR/8=,iv:rHV3CmPuLCHUnUvbYyIy71Rek7kxTK88e7ThRXjrXHY=,tag:/2MeQg6sb+nG2FJpJFvUPA==,type:comment]
    #ENC[AES256_GCM,data:5Qep7MVDhwX4CMruMMUuG3P4xhmli7CYog==,iv:Vf5th45O1rKi0YwNr7O9mK9a2rAg3sed1kQeVj00Y4g=,tag:PAW5nobE2xG9VVZB4oTZgA==,type:comment]
    #ENC[AES256_GCM,data:YJ1O75LHr8XJuKP1C83LF3ftCTfSrxyL/G6mpYBfaM4uCHbi/9rZ/J8YLhOj+VNmaidJPYgUO3rDF9xMeCcXc+HCAJFlum7kfiSvSPA=,iv:JYR62d3t2iMGN+SO6+eemDpclK4TM8jzrxLOHW7VIgE=,tag:iTE4DJ5aeUvYQGq1mLxMKA==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:PYB55zuU51t8HIed/+F2yqIVSumumGGbxLy3AjsnnGxOcM8oJCqfiavBUvmfLixykhqvZ/H7w5cuZw==,iv:nWb7PaRqQEbAHxH46XtSui+nmgUdmol5aTmg4MHX4ls=,tag:YHkCmcBfN1ZPWq2l7bnegw==,type:str]
    #ENC[AES256_GCM,data:7CEvG5ge3Vhm7Toqk/gWXbRlXkXScpbgUcyEpn886SxHoPcliN86by6QY8sy416AveLWzdKgfqBwquGz/pC23tJA75rhBs8=,iv:ad4YC+MRGEiKuBpLB2UQPodeMQFfz2Ropc8qgYeRVP0=,tag:XBxOn4/082s91m9WmpWI0w==,type:comment]
    #ENC[AES256_GCM,data:aoIc4sUo1F4bRFsbuRwGuavJPuqVTQfJiuJdYXwsOr9wOHNtH0MtBhfYX+8omAD9Dfb6y53b,iv:XLKxLfS4MCOwbITTNb71W3TaJq1yKiOvIyaxRVZp+Nk=,tag:L6oM9hEX/ed5eDmOqTZU0A==,type:comment]
    #ENC[AES256_GCM,data:mI5cSX7hKtvuHqYRTV5XTKwi5JU/AeFfLg47iMcffEUt5QE=,iv:fmNCcqJz/m8yG5tpwciGNr5p3Z+LPfi+bEmIuacu0v4=,tag:DVj/TEJyX618O9Ax+BfggQ==,type:comment]
    #ENC[AES256_GCM,data:41Lmcm1k0F4s1w6Ms8muCALHbEXDbvrCQMy7Ui6MljUKi0I1n6Eg,iv:i6AnyYFtMmJC1f5JEVEBgPysUKDGviYduX7flW51gtM=,tag:K2+KHINWIrR/nVkrpHpQ5w==,type:comment]
    #ENC[AES256_GCM,data:rGUPqJwr7/DPs+PUXsA=,iv:scYn/Qs1oeQ1zJEnE3Nl2HTsbfdd3Jb9pRaktalpFyE=,tag:KDSLrFLnDHRzKQzpDeSEJQ==,type:comment]
    PODNET: ENC[AES256_GCM,data:ZFDRGm5TSmdRANDS8A==,iv:2+S1556E4Xz6DAljBWhW4ySjgLMWHijP7N/wzQ4hqNM=,tag:0Z4wPgR3j3i6xL80AfemmA==,type:str]
    SVCNET: ENC[AES256_GCM,data:daGVSzhO2cW4XkkkMw==,iv:CMt4W9SCh0ygWYxvE//ldSXLpYJU66BjMaQ6Gam/OtE=,tag:aGhIVeFx5Oq0U1oaUZlEMg==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:qDcoNA==,iv:rgHJM8+UFwltWQutDj3r3Fqv83Xgkl4AfHwnrsfFNEc=,tag:xKfurMPhFRiRTO5hMtM4XA==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19wg3490scy7jf9srcmzskv6k96nj9fx77psdqkxpt3lg66j3fcys4xndsq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2Q2pTSm5OaTlWdU5PVXlN
            OVhKWElDdUFJMU5mR2xKLzVYTjhPTXkra1Y4CjVhbzBaOEF0aGE0K096ZGQrZzRW
            WDZRUHBPclorQXFrZVl1cE1GdWV0eGMKLS0tIHBhM0FaM3pFQVNKTTlTN2JTTGZZ
            eXlGZVd1SzFXaUV3WFhybWo0VisyYzgKJZfderjlyVU0sZEhGyvT/sjL9d7cbJrX
            qwZ+p44nrapK4/StGMRJtOYNc2Vv45EsF7cpAlx4LIDMm5K/UESu6w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-26T00:15:22Z"
    mac: ENC[AES256_GCM,data:vspr5nB3k7MH8DIXtADWHDdt0XJ2ojrfLuk0I3suVfZ5pNmehYNdc8dR9kI/FH6WKheGjVPVNMsN4x/aq+xa+3rhZMk2PRlKEKQcuTgQYfSj1TydrIjcaboTMP4v4OFg/vGIIt4WsthTWeP5jTIleweBMGq2IRWefAb+I3mzxi4=,iv:+lAYJUQYwFBQVgD/9sD8GoLE7qYQJHErj1/4V0WGzWA=,tag:joF02j11+qhR0GrN8YFDgA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
