apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:PYPQt8Borkl/aaiIh4A5AiQ44MiqUmFvjxK+Ky96mkVgg5a9zfWMx+0gqNp+L+PbR36/71gS6/6PzEBHplQyOAg=,iv:AjGu1LYNZX8uLQERU54kLnrpjIvUlQSixzVi5Lgwn4A=,tag:6f0xX4Je7TDBqFRmmbCgVw==,type:comment]
    #ENC[AES256_GCM,data:VbxCb1onmq4wnQp2UflVnkFkdC77IukHBVEDOIKy5Ee5E4WSXsdfJjyoAyQ=,iv:+OW8AbWX3GbX+r9oOEbKi2D/Rd4o3CPUzDcvY31jlWE=,tag:I2bg/G043CD8q54lDLWpTA==,type:comment]
    VIP: ENC[AES256_GCM,data:ymsqSgfEobQT7w==,iv:15OAqdud9GCoCXpWwGcZKJ/qlnAeYXhvESjnUWv3ups=,tag:x0mHG/yQe1Gxz32eb9NHKg==,type:str]
    #ENC[AES256_GCM,data:SnS7u2Nkv5geZx9aBSeAPeKIcT44qIEWWpR0,iv:lKm+Yvu0jR5Buvjb6LQM7OMuMpyyh7XF0Cco96UvIBc=,tag:Ia92NnR6TOWnzwlqxLFtnw==,type:comment]
    #ENC[AES256_GCM,data:CiQbiOZ+crf35jDT0t10Y1389cg+2/hXqRepbQHxHJ6x1kHA3Ffo6SJte8nWpwq7jG7KO2hexNzCX8emjmrOcvvbkjqbGdryNI+Y2hrokeuTS93Ed5kyOss=,iv:7RDitAXhVEuWS8o9AGKxyGZ3WTGjB+r/6ThQQEhcP/Q=,tag:l9k5ddxxUZw3Nh9nDl+ojg==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:EAt7HMiW+V6ucA==,iv:NlsesBTC9VEAuucDgSTJMsEttsH1gpWbmac2NslXrs8=,tag:fROM1DGABOwgIRAKMBC+6A==,type:str]
    #ENC[AES256_GCM,data:/13cns/+4wTjbdys21P04lAAXiXdJ8X04FXBxwMo61hRBw==,iv:mAFOCZHx/zC4ewCTBbeOmiw2u6UnjTZxxSyUtYpEXas=,tag:AFwALxlEKjKKHGA2LeujoQ==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:K1jgLBNFrkBu,iv:5TnGfBZuHbdW9kgJHHFkqHCmeFTFgkwGZYys+55F/Ew=,tag:ddkAqy4uVnSv14xv90lvwA==,type:str]
    #ENC[AES256_GCM,data:Wmhz15YnnSz8y3XjsMnOU5ZjOi3Uz1eM4QVCOdaYIsTzGtQnfu1VleorESqBsO4=,iv:HJ/d7gJBylYYaKZWMuJIsZeE5n2j5V6jhVJiJhxdDs8=,tag:A6fAoo4/oFOhrbHJW/eA8Q==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:HObCfvV/g0aIaqiPvmQwXqOvQo2XEw==,iv:/24GVQ18sGUsPMuQCDviYKWR5WfEyXLTLm4wiskiiLE=,tag:G6PLFlqmzuWYL/KrIe/Xtw==,type:str]
    #ENC[AES256_GCM,data:9js2H7Vb86DkoVO1CEVi74ymiAE0bJ1P/hdhvpApj2hpljpygL9WrF6UpXHga1sEVnVXrO95ELHdO748awHEXWaSa5ksY5JiFjiY8kHz++OWOw==,iv:qLZPbT35O/en6uAuASkaia3560cLxeGCqowa73O9G6M=,tag:fnBd/Yym3RPi1ZJpGJQlLw==,type:comment]
    TRAEFIK_IP: ENC[AES256_GCM,data:sSQA546y55YmvA==,iv:r6Z3WTTbt30EjgMYCti4Z65CK/zUbHxLtfCax3k51ec=,tag:oggGII0xargoRT+S9m1lCA==,type:str]
    #ENC[AES256_GCM,data:lvnvA98QJBOc1Ue2Vct1c/GfxZxWz7zsQAVPt80j51Kv,iv:uW/9X9AKnxVPDlrX79j974t63J/jYBKTkKHdTjHjQiE=,tag:vVkODocLnVwxhgUlon+AOg==,type:comment]
    BLOCKY_IP: ENC[AES256_GCM,data:O8vme+pMLQe0SA==,iv:dX3DfS3sEF7IqIdV897fQ42hFvZfQaysQr8HsaRt5KY=,tag:Dkurx+w/zin7112Mc0Yv6A==,type:str]
    #ENC[AES256_GCM,data:+0Z6IJqYPanuT90ZCqtBPR2LfUaq/CRSX5d0UhqGHYcliy2knV8drEcKa0Hqw7NLlinWxHWVPbRnA3BG6oGpruV1yz6XpmZR9Dr34xm3szs=,iv:oaJk1dLYCiJtX6sVr/stX7jJHtK61+ZhhaqRzFqTh58=,tag:rZR72/z/JBrpNQG+ASVRpA==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:CgLWB/XxBNC2+A==,iv:OxZtbspuQHqYMYklwla+ZWPZJS24sbJCH9E/YXx3wEs=,tag:SNrIkHNUUOTngTzJYQgiZw==,type:str]
    #ENC[AES256_GCM,data:0lNqBHCHFgcI5ILY54rnk4tsb7e9CK67F7ZoJSRLtNMD8AL+ijae1MddA7zVD59w/CUlYAsD7OXW2T2yNxhEJ+ZVl8MDFroUryx0MACs2NZ9ZZkf7D7O,iv:GVyHgt5Bzj5OAgcdlmLitozH6Pl+kuj8Iio3sFXnw8w=,tag:NCumx7mCGeKTtYBpvW06fw==,type:comment]
    #ENC[AES256_GCM,data:rlLLP8Vdq/QNegCaTyQ6TwCKNNT4GewTtwgNRWP1+7sWD6Wk1CmO985fc590Y5vDxFiflUrgIzDDQZtiaXemVZwy68Q8KSwgWeHfBfl6JMtuBqssi8jBul23X0TE4IDpObTiGMb/S30RbD2rbCrKqRp96TQ/wRJiHJoEHg==,iv:BLJ4c/wKTGZpO1XVrdW+ieitYPCGrdBP7UPWjWrBpc8=,tag:4WUrFdcXoKYEB96rqUlV7w==,type:comment]
    #ENC[AES256_GCM,data:vOjFWBST3iAXtQ3KGR17TRdvm+MYMWlKIFK+PFIAheN9JURppCUb42hfqMMzDGPrDueOpS1TsUldmNwsLBR1yfgX7l7GRruc7sEaAoGXWsk=,iv:GCbG8zKobMxLsTX03eohTjK2jgXCFeZfwfPPiun6vJI=,tag:o9+nDdHQgf753cQ/Oib01A==,type:comment]
    #ENC[AES256_GCM,data:/8qaoVjMEYXhfvJHnSYnjl9ukDcsesSvS/izwJOVx7W532zT6mvBk22wvJPoWKnyb2u0A6Iu,iv:cIxq4Z+jlmBBHV7KeyoGoCYsCp46yJ51W9AVAklxreo=,tag:3+QvjyMiSFho7dGSZWsAfg==,type:comment]
    DOMAIN_0: ENC[AES256_GCM,data:gXylyItQsi//OZDWjMeRmgs=,iv:/UEFp1qlBhE68PmosO92bhHivlnmQtnhZuDSxgIMJNA=,tag:roBwUroZL4VZMsLlyvxrCw==,type:str]
    DOMAIN_0_EMAIL: ENC[AES256_GCM,data:dr97l50HHCqiEQAuxk/iQFQS7K+c9Q==,iv:u4b4PNYVZ7hAdAyPlZFrs2HyY18wiKJYEX4tsBBc41E=,tag:6h3fVAItGwB7lgHp3zfvQw==,type:str]
    DOMAIN_0_CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:X6gHh3wXuyw5ydUw3/ODGo5Yz75NruVvTskYfW/rwcJ8jG4F+ctz7A==,iv:nldwNbnNkqH0aZap2pkqhkdCd9Y6jCDVOnKEq687GuQ=,tag:Bctq4vnYkqX+R0uYnHdbiQ==,type:str]
    #ENC[AES256_GCM,data:4cr4X/b2AuV0w2Hh3M7AGPS4gpkHi8dq3uQ87fWHgjwb5ZFk73Y9bhUeChvDMpHgkQ2uoAbUn3A=,iv:GulyN8kD6mO3TobiLvQEltFB3/SMUztQng7TBAKWrH4=,tag:XQg1PcmdZ3AGySto2xSafw==,type:comment]
    #ENC[AES256_GCM,data:9n/+plYfSFIzma4GtP6+NG5YrOqbmz6W+A==,iv:IQ6Gq3ZUjGRSSCGhxIruZqhsiD4cpOKncZQ8eEMIucA=,tag:jX/H2hwLrW/Jtvn0M/5OrQ==,type:comment]
    #ENC[AES256_GCM,data:GxDISYHB1+qCF8XJqwVYr7sU4WvLMzhyjcWFjQptN+E7NReX+ntqmBtLCukaiDHG42ZUwhw6ucluEdi90mAN601oZWdxmv39B/zdVQc=,iv:IljCzYbA+9uUwWHfwWYNpmcV3d9CExhEmCFSYrkkBa8=,tag:XcxnGaMMxos02liopdHTsw==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:kb2iv/6/lOQSOrgUeoEHhwpH+eyx/gs4mlSfZreI4clF68zlL1fpLAWfQl8hfZ6iaAZsq29IQ2g62g==,iv:ECPnXUBeY4MySzipw4abD6aOvAYiNUQvVm5X215ipWQ=,tag:SotNeRw4donPG+CMZC9ozA==,type:str]
    #ENC[AES256_GCM,data:r74/a5+eOCNQUNpzsi1TWye+1+UeJrDnoc3d80rnxfSxvQhX/6HdVM6fYX0ZaWPqE50Z+g+1hXEb0IZHyjPzH6fuodCs3Yc=,iv:o/s6sI5Jj3Wv6YJDdjSShOjnpnHd53iwvnriYMiV8OA=,tag:bOWrODHGOf7XQWpeMPnpoA==,type:comment]
    #ENC[AES256_GCM,data:G3HjmszM8ZifL3ZbEbOQ2rJrX3ol6x+DB97kqE0vuqgcsN7qyqnGjTA9Bi2+PvunXh6jWjld,iv:0tyqiPECzHYJy9CbWAV8UcqbQhO2CNP29cWOl6TbNe4=,tag:eR8lhiB4hCmmgqTP6B86yQ==,type:comment]
    #ENC[AES256_GCM,data:944su4PYkNtXQRNF6ydN/omuigIkEnkNfiBf9TTQYZthLzw=,iv:dQHVavVfDJxQrjMMdgDv0srUvamp8xMd8SrlbzNfptw=,tag:hjUMVs5g4ZO+kEiYGGj3+Q==,type:comment]
    #ENC[AES256_GCM,data:hmWp8obSDO6/RRpnFkaReaI7qs702MhcbyC8YeQVQ2+dB8Z2YSYB,iv:c/nv3UCTUMn1Cg660oJ4CTe5AMZlEKvUUHpNpNapkfM=,tag:tN/PcrkHp46KEPvvuWQmiQ==,type:comment]
    #ENC[AES256_GCM,data:sQaIK6yEd/SIGkQwqdo=,iv:TMpR1cLFIuV0Wl3AuRSnlmPSiWU2xOVhsRUAWiRPY74=,tag:Xwae+X3RmMLaiceWx7U3UQ==,type:comment]
    PODNET: ENC[AES256_GCM,data:nGEngnHo6NUUpq3Zfg==,iv:Q8yY+iBEt8aSjVhkkxUoJ/T3HKjN/GEMkXw9PtYdTWg=,tag:hcY8HgZAiRPkWP7TFC7Q4Q==,type:str]
    SVCNET: ENC[AES256_GCM,data:nOnfKBj2nAgG1r78wQ==,iv:DtLNg89QmbxQ4oEh6ZnQNe0/wv3EjjfIUVeWN4Ky59Q=,tag:JCr5UEHnY+pJWzAB4ZroHg==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:TkmDqg==,iv:CW3HupmDVNIxCpjPA8JulSPBE1kn4x8Ryd4Qwn/rh2k=,tag:MZREQIXX6X9tIlqqLXoHvA==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19wg3490scy7jf9srcmzskv6k96nj9fx77psdqkxpt3lg66j3fcys4xndsq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIb0RDMm1DbjZEYTBSQ2o3
            UFVzV1h2elpEeU56M2huQ01Oa2c3TjhhckEwClFnSVFiQjVWaWJlcUNONUUvVUsx
            WnBaTkp6ay9DRjdpNUhhZ3ZlTGtTSmMKLS0tIFNLUC9TSTByakgyTFN1NWtXMHNN
            eXNoTk5Ec1o1bXMwZGc4dDByN2hKTm8KjKxSw9o/GJVUGzyLZTw9X+U48z8w/Tj7
            KEE7F7GYt5zSYPLp+ftYC0IekTHeH5P/M/Cdcub563t2Rjwb8pUXcQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-22T15:58:58Z"
    mac: ENC[AES256_GCM,data:Dw0ed7svM/3wbBXTr3HQHMl+C7Q03ZMQFZW1FX5ARaU25+AW2l02CmCBcpFjO9gGFcYCL+DNfKW78SEHRKxuGQjRSK2bmRp2FJ7OXOyeEaoIjv3iLV0o4WqUI0IcQe1mu6aVUjztAofrS2XipnVWquoiCILdUDuN8Y82IjOj36c=,iv:VQsZ1W2bhc+TsCDbd9pvlksLo5sMUEk6XPBpjHdSCHo=,tag:AGwSxBYS0ltW4cjD65uwKQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
