apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:WEqePoXgIkLzTBb0sAil/8W5WtpFmQWhiTgw2sPQSxSiq1UfqoCp3BaaJJ9excW+bLQdESJC4IFb0+bAeyOxTrI=,iv:Da52MD7DbeZfkE1tM+mTbxXQRZqwBnGC4G0G5ES+zIc=,tag:pIjxwOJl3HaswxgtPdN4OA==,type:comment]
    #ENC[AES256_GCM,data:MsJlBdGLfcc0RS2wCSjRf4cJx0H0bwXkOVgAhkjm2hQUHk6J6bG+u/fkb9I=,iv:TWnWQTgME+gGibGIC0xLe3FR6xTJXzltbLsdSgKg6jU=,tag:zeiI7jkYckzXbvHEEK/bzw==,type:comment]
    VIP: ENC[AES256_GCM,data:9pVNTKcS36Q14Q==,iv:kd8bS8cqtS5j8frd3yL3wuT1tNcn08tGWKe3M1K4mic=,tag:C1paYMF2QzBMNmREQvu1aQ==,type:str]
    #ENC[AES256_GCM,data:ERaGHFZZAJCzN93NTuqhwfSkwbiSgEuH6Gfy,iv:yKpB1uxSQBWzwPk47gBhBX+lgHEeN1R25yg1gMldqW0=,tag:RjoCH8+Ft+c7q/8BMdhX2g==,type:comment]
    #ENC[AES256_GCM,data:PyWvcd0dYtP2KREunAuJddNKx+lPoyxfHhQzWRVflz/D6GvI6O1CxcPCVQeECCTTdIqILmY2JDxjLgiiZZTVQmqgimQ6IO7j703igDIsy9sh2TyLrbvj7KU=,iv:eC2FfYHlivLFJJEo72Pqr5kKSIDKviQdnaskZihwEqA=,tag:TD87TETxCKiMHf/h+xDG5g==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:5QrNGnVwLsQNQQ==,iv:KEVJ6c8KgQUqtZjzGJEjYzZKgyNjADaOb7Gd9Lcgro8=,tag:u1bBWLwTpygVkbcKEd/6qQ==,type:str]
    #ENC[AES256_GCM,data:fILoGXd/ayvB1lV6tpBi95yu0CaBuHYM44J3Jwjg9uwwDQ==,iv:+CU3zWmwMFLTgGmIW62Svet2J4EmPI8hrgKz6j22Ros=,tag:b3H0ioeZMsPZ/L3Oo2PKIg==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:GD+Ll45gQQc0,iv:1CTFB043ss2nrvLotifzNi20acGJwJWvHU81wFJdmmY=,tag:LTf7vExW8zhhfc22Hx4CBQ==,type:str]
    #ENC[AES256_GCM,data:f1uJ1DY56U6kMXgphv0XRBhNO5XPMepKzerbM3+c+DJMvBOjYPclZTL+cvbqIzE=,iv:mqu6rHnw3+er0j47HZl4/CNagbMhYA5SuvN/yNWxSJI=,tag:R5jau/gs7RZ3ptXVOG8GFA==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:3+3WceFbDknk66AB1B1Ax3FmDUzduA==,iv:3v6wdjNaZTfR4gMXsrqGJgoB2BBt8Q3GpUVfuwaVuoE=,tag:gubvZ3DUS51gsOPhhZfr8w==,type:str]
    #ENC[AES256_GCM,data:4BxDSUEb8W7IClnVqp/4S64yVIEjEjks58T4w1sWPfMutqWJfXOtrxa6n88PzO/HBegEBriSge/chMPEljt1V6PuEwyW4hVZXv1xUQ9yaavd8A==,iv:0fTK8AC32vt1Yw+/qWHrTBZdgsrfMVqCcDoZwJMMxgI=,tag:vxEZRcNBRAgPCYfzaAGFeA==,type:comment]
    TRAEFIK_IP: ENC[AES256_GCM,data:U+/s8n5mCLnqdQ==,iv:2ivz8XGLFuLbpL+rIpLfv99L3aZbBJ29D6hTsS03YK0=,tag:8TlAT7d428DuMIac/DRjnQ==,type:str]
    #ENC[AES256_GCM,data:hK9JHMZMiJHUW8nYBAJf7A/whvZlRO9fDYlfoavwy4YK,iv:OPo9ShZg2JjJBVulkePaXocB05D0SSHFtDf7wduxmxg=,tag:2mgMUy+lcQxpe7NkzMkBgA==,type:comment]
    BLOCKY_IP: ENC[AES256_GCM,data:mnh42tt39MnFIg==,iv:UXWimON/ftI5x48l5SA1KwVWu4cs2IIOEGajKIiIJA4=,tag:rqCZlhaNxCqt4GHhI6k/kA==,type:str]
    #ENC[AES256_GCM,data:8/jz6VDt1OHpKn45WkwIL27cDOiWf78p8cetAMGw6Zj7N7bzsLquPikmZAnHRCMBjZNwGIA8moxk/g0S4ei4vxbTn1jV0kuN6x95sRkocZo=,iv:5R3T1cFHKQks9xJ73lBKd0c1PM1W6rneTFDysWMgYUs=,tag:1Bviz3faGBrMWuxSHOjJgA==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:XUBGzN4gAvHcNQ==,iv:4eR6HRxiYGbSFqb6W4pMfWXnE6tLClfVbKwkN9D5zC8=,tag:YaFrvtg4S+R039sw3EjtOg==,type:str]
    #ENC[AES256_GCM,data:KOJ7cyXRmVPK5KereCLW6dQEj4hMaxdyd+dgC+CGcSzy3vlrgaYDcyg3XACm970LOO+MujaQxZHQ7ISJZs0hhZlFn/dbb1SY+z72NGrxacY3VcNteAsx,iv:6q/gdel6qWGGD0o3kuhaXgHmvAObi8pIb7SkOeO84ZE=,tag:geuOirmwmYDuWnOX3SpfdA==,type:comment]
    #ENC[AES256_GCM,data:fax5DO3HXtZzJbtH9vNRgQ42sKw0GOW/yZcB1DwYqKWG/9byxisk5TqFkAKpX7QNpMpJ2NMmWFwVYRY7Kj8+0Ai8PqueQETKPWGL3/ykEwrYwabpvoadKNp5KDT/8roL8v5Gr+t8564S6oGAjyXzvQXpC3tgJ5k2i/zgHA==,iv:TXWBiEG9sER1mHBGr/Gdteayxe9UdoUOOeUvDzNAhSk=,tag:6UeQpxS0REEl0JJeQ5UqJQ==,type:comment]
    #ENC[AES256_GCM,data:TNoxE/jnQjDUJtU9prStY8AuC+2bMedmQjY86+QAA2Aps6YeoumqaR80eGM6g0662Sg74etYzQZTt7VVCv6QjLHiDLvaWmxBpf7hZo++hqM=,iv:7wTlNT0DiOTv80gvoBXKXOPZurDL1IathLenrfmjkjM=,tag:HQalWJ70gkZI8jR/+dl8mQ==,type:comment]
    #ENC[AES256_GCM,data:cMiyWmF7at3Phslf1oMMfMDA8YUDtTIjDN5I7c6J0DD/borJ9vQHYkF9yqv5deuklSluCvyd,iv:V+Bn+zn7S+RXCLTQEgm20OXjFmM4MtjGe6rIShHrhFI=,tag:J8HoXkCAbTXFvGodL3YdJA==,type:comment]
    DOMAIN_0: ENC[AES256_GCM,data:/kd0yjGrdbogdkcNj2uiRQ8=,iv:sCcfSKCm/hyn73hHoLP8EskwVh3Et5x17Zl7rGHNcE4=,tag:VkysCyYj49ltQnptHLUGwA==,type:str]
    DOMAIN_0_EMAIL: ENC[AES256_GCM,data:Qbr8w5yy50uEOsUtZ8pGlSVRfzgz4A==,iv:huWbh8Vu9KixcnZWI5bjhbFPBKel46BbO0q4k2UsLgQ=,tag:tGB2vbmH0f4A4yThcxAX7w==,type:str]
    DOMAIN_0_CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:VCe10laf0xNBczq1eQUkbLvqQBzB6DfIB3EDYAJZHrLbZwky64g3uQ==,iv:uHYT+dUbFOf9/CTIJ5gzQicXo+qgvkx0LV6SnbHV1hQ=,tag:luIcTbzKPPCAsdBolil44A==,type:str]
    #ENC[AES256_GCM,data:C/P5T5TjPAOLFr0phikWFrjXmrQNLslLzwvvCqw2oFVCtjGeojexL9uXXVpvXEZFUSqsKyxEK2o=,iv:PWY/Et7kCXokA/cTR2Dy798kV0OhYqwIDRMgz5X+ZLM=,tag:sOgybLoHuwNYkwCbTxZ/YA==,type:comment]
    #ENC[AES256_GCM,data:GxAZ05StICuTlZbRmksEsg5Pw/iZjFJ8+Q==,iv:B/smQyEfK6Hx5afNMmfIbVZuK8i8Yzuu81PjGaHT3sw=,tag:XTV8MjtMv7p1ebp2Z94u5g==,type:comment]
    #ENC[AES256_GCM,data:dHP/EBaka+sIwmmNKE17guEFtuOJMD/6MAxm8ewmM6+bOqNLclM0vhINaHL4s5uY/P44+htJeSx9jowdzdthBsGwGdYW3TSrv94Mnks=,iv:6JVKf+iyDZ8+2AdjbVdUsseoAaFxzRdQwfoQWU2CMIk=,tag:xxMBz4xKNlieubeK+kF0Ww==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:L6AqhbLFFsRaLom14fyjxHd9ao162Mg3UVMExoyDBVVsxncZPBHLfESkFBzrfXuesfA+7tnRpnDRVA==,iv:T0DG0CiKOK0hrBP3e3p+5TJdXRojehkwP+Be2wFk5MY=,tag:IuuEVVrW49FlA8gGq77fdw==,type:str]
    #ENC[AES256_GCM,data:00gAhbWhkH8XYO8PajoRwWjXmdKsEJ0uGHNXK72ybT6Ca+HkMuEophx0ho/QGoXO8EI2yRsneUVN6BYUqVb800gRvicuvlc=,iv:MRYbvYidweaThW2ZbBjW5qOm4IfB5Q9iAJv5IY9eq5M=,tag:xUkHe06Dg/7X9CouGCU7DQ==,type:comment]
    #ENC[AES256_GCM,data:KpvGj0JWMtoMON8soFulcIgas7cNBLRHgPdu+93/FbpKdVlV+EPKD6YKp6i3rMsCuku5Q9qb,iv:CMyB3uPHwlE0CqLljov0wgvhyFRRkuKtOhOcjEwN1pw=,tag:7fTNBNWw3J9WiWco1Bz9yw==,type:comment]
    #ENC[AES256_GCM,data:Qx/0oiPBRCG4iA7Hkg6nP3Q9VcXVj9vQWCEOmPp3Mkvx6Yg=,iv:aAq2Bzvh95yCvuv4uDdW74NVG8CmReE9ExiW8cVRzyE=,tag:FuFq6JVjQd9+09lkyIc3/Q==,type:comment]
    #ENC[AES256_GCM,data:W0bWzWPLpPK0nIUbS4y7zeTbfT03w8kSci0UWuo7owY5WSQnBLCo,iv:RB6BytswNgXEP92uND7+AaYn/Igf9sOhKu/yuX7UUDg=,tag:2lnyoP0m07DdVyWAJHFXdA==,type:comment]
    #ENC[AES256_GCM,data:u+dhju2q3A7W5RXOcIQ=,iv:ffujvBn7hemQd2upMyt9CIOHp/GlsAElrt3/iUT0CEk=,tag:G4H//PYamx/44MTq8xtBkQ==,type:comment]
    PODNET: ENC[AES256_GCM,data:2Y6TKoax/5F1DjpC6A==,iv:nYW7573liw2Yu5MKSYHXLQfuXnZxK1lk+65EQEo+6mc=,tag:Fp13IzUfdUZjU+d8zWEXKA==,type:str]
    SVCNET: ENC[AES256_GCM,data:/U3O6qVsbbjX1fxoZQ==,iv:TQdqUdw2KK5BlQumksddYxgFiX3/+oYN17s8At0OE58=,tag:7rUWmBFflsUwsBB1cSw35A==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:BqiM4w==,iv:m8v30y3B9eVXS4yz1zGILP7Gr+0Uq6MbsDQy8DYEQDk=,tag:nqq+El/kImRAL1+zVujymg==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19wg3490scy7jf9srcmzskv6k96nj9fx77psdqkxpt3lg66j3fcys4xndsq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWWGVJYnFpcFRhendMYmJZ
            ZTRmbEN3Wjd6NVVqYXQ3TmxZUmdpTEVwbEJVCmpDTHplU1Q4L0ZQKzJhTTdSeStk
            akRsb0tEaVdwSjg3ek9NbC9GbjhOZTAKLS0tIFFwQUYrNG5yVmdBTllxN2txQWlY
            eTBZRmcrUVlnMXFvbUE2cERlaEVSZVkKL0WK1b5gwV9SSnzJBReOkyA/sn4uJPM4
            ERsma68MXrdSs+6niTW1Y3R4ItE4/bcUiuCpbNb1Z+6y7CB7DgoCmg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-25T18:44:13Z"
    mac: ENC[AES256_GCM,data:m1p3wzow0YxLNnEdnemcFMyDFixQkdsvPmHpSuix4wGrK8eDY+7lyreYxQx+LEIfAs+q/6UlqOg/JQ/qH4HwdCpgxDzqrE48o9uViMou7zsEurDmGhenMXEHAMvtw/eUBCZQDOa/85lfIJMRNyKmS4VFOzAZpMunZgBvAGK+YgM=,iv:9IFCoTZxCl4Ctyxv+FzCnxyGuNEu72ZKBi8UFa9NPn8=,tag:DbHSSteWgEXPiSstb3QWGQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
