apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:voqfmWmrGtEeA0H3aw5Mw7wl8iImyvZHQLqHCLB5gFZ7+inD4DFHFpCze4LlRnx2Jl6zrtxeGhyHkMvobnaJJvk=,iv:pE/vpa6PD5sOJCwdvTSCGK/SEH7MjK4VUfqfLGqy4JU=,tag:oAh8bjiaX2gydboTUPtk/w==,type:comment]
    #ENC[AES256_GCM,data:X6LCtoX5WzX/C/yiDCkid6piI9FSvEblTfb2E2fEuWcy5grvq95n6VOIVc0=,iv:FoUSHT0kNE5Klxz064TNiVi+chKznKNPd9kErM6Skss=,tag:fyA3qdSaBRYP1qMHuA7luw==,type:comment]
    VIP: ENC[AES256_GCM,data:dncSqlX+dd9SiQ==,iv:P+E//OtF0rOKelDj44BcLsk1D9CYa5Ul/n2efClyI+M=,tag:8RxcuUEqNh7MzDPMCtnCEw==,type:str]
    #ENC[AES256_GCM,data:Rk0ZM1W8wy5eI6/NT5Om9O6si+1fKxRXtjdW,iv:bVNQNO0cwm7a1AbKDMXw7HurR5kdPYcTAUtEug/PAk0=,tag:Ko0Wofehlb5j0TWpLmssZw==,type:comment]
    #ENC[AES256_GCM,data:hJzgsiaFHW3/CdeSY2LZ1g7XQk/5DUHxO49Jljvho/8wDlUprBBxkeZnaiMcNW26DYmNvy1/arsLgprYONeWSr81eQ6rzO0E5KtRrzHjcaibyaz60MkrdCk=,iv:UxsaF7/XuVz+HzghpWm0o1SlYJ3MvZ+Gzr3CpUrzABA=,tag:6gaUk8bMSQbLEzvtnyMcWw==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:sgBIdcZqU5Jt+w==,iv:9XY9+D5Drd27fnKBELUIBV1K+zxoPanZlj43iFERiXA=,tag:YCIErxixMpOGDFDGQ4z0MA==,type:str]
    #ENC[AES256_GCM,data:gQBKPo2A6xTcSxn5cr+Rg7SZwZXgD+Ze5W0yJ20wZ07SqA==,iv:gMzK9dCc1veFvdkNjmU31PFJ94jOB3pdMPnGDVIBVTk=,tag:x0XGmwyT2MdZqaYEHq+Oxw==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:04uWkxgbiGJL,iv:3v+l1/wUc6gmu+O6BxKVYzEOgSFm2ejs1xsWvLfM/H0=,tag:qhxgGbYX41Yg5uQ8uIZIGA==,type:str]
    #ENC[AES256_GCM,data:aXL8xHxQ+y6z5qUhCCJrfEuIonGRUgZHEeadvuGnBjNcJVfMa5ip940gT79FmbM=,iv:jYTIcRNAENpZUb3xcH0cVCZG8V2P+GGu7W3PWCn01pQ=,tag:27pXBJ13Da55pql+oQu/Cw==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:ohgXc7XZ0lJ7bZ3wmqhwqlejK4XcIg==,iv:0nMOZ6vMzUKfVuh5XVIxILza7RNPATzxtHuvZlbQ2JA=,tag:oM1D3kdRwEPg5HEnEVwYmw==,type:str]
    #ENC[AES256_GCM,data:DSS5pAvAK0M8x2ZCXUZ2QQ5vwl4EnSdMfhlWicuEQttvEw3YMxW4s9AFxQ4QPscjKcijhXqIdIGRGex6BWaKGjXN6akElVRmuQThGylUKUGKjg==,iv:5ELe/8G20HrzBm2yCJPV+Jy/FUykDKHor3UdX45LR8k=,tag:hwxZgI32PB2r51nGScXpZA==,type:comment]
    TRAEFIK_IP: ENC[AES256_GCM,data:qF/7EPQtU1ruLw==,iv:6mxaROBw9wm1uca8i3ObijcMBxbFvOzVIR/6BEA+X5M=,tag:ZHUdHmHM14tjhvRPwf0sMQ==,type:str]
    #ENC[AES256_GCM,data:J77VzTCpWXydyxsxj3cL4loUpSJB6lxpCmJjHw3uujlr,iv:FBDUXdpL4gqAtkCK8DXGXxQbj7GcnHtzh41ZEX/2q9g=,tag:ZzYn3PNfwONmzLLLx6ox+A==,type:comment]
    BLOCKY_IP: ENC[AES256_GCM,data:ImTGyvMCEhqdNw==,iv:iiFPYkk0gaejAcaTk51RYdLynCeRKYDn5gI8pNR1cno=,tag:20W6+tZ4wN4PcVVzeLVnJA==,type:str]
    #ENC[AES256_GCM,data:oe4uYMLDOXvT6DQrD4y0/TjElPMN2wWFJgGkalJc40Y48GTTsXSxyy20QJjSilDb6Ipd6iNdEhueQDi/5Cc9WJ17EjssIs3OVhhjTOCSKF0=,iv:hDg9ioryneXQS4f/28LW7BqC8MhWuPHBpHyd4Uf8uxI=,tag:4nn6Ylt7D4s1xDhESdDkXQ==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:xxevJQuRNZ+zJA==,iv:W/U3n6rwCD/DH2F4T5mbN+ln44D7aYGDwRVZ1JBoSTU=,tag:R42/KVE8H5BLG5t7C3Ap5w==,type:str]
    #ENC[AES256_GCM,data:M76AhmLeE/a+b94Uulxqi6HSbicU7nX1Lia/k53txdrIDG9o6uF2wTdOJCC40osOci7HXNWdJVPjQ4iTQFLb2F/vX/GPidg7gZ893SucUoNgOWIkIi4O,iv:C4MuFllOsvmf3FJ19KciiKw6W4Fxt7obza/EA+mNang=,tag:8Q12dXrEETw0OfPJLgk6Wg==,type:comment]
    #ENC[AES256_GCM,data:zVJbGnfnFm50/xBYV63NAxN7nYsNPeVFrE1s4HZm6pjGTVSYi84977pj2d4r3hSfzu8FLFdVDs5cQvRhLkiMfrUFhRIljVoJddQrfVU5/6CDjUFM5dsnpayHon8zjgBYgQ5GqTsIxxHeuyZZPinpEqvRdg04tkzK6HmxVw==,iv:Q05JSjo80WHnXaS9XX/rgOgObh1aUh0xQbZYR5IZdB0=,tag:0rbGddoYV/EPLxn/vcCRKA==,type:comment]
    #ENC[AES256_GCM,data:YglY2zdiSyBB0nMkjrjU51icCSHNUCH8N0Iv6pz70xdqc5nGxF6pPVxXTnl+gpXhv9KcPWLUwVqogCC8sgueZm7GVmWLTS6Bp6XsOot2V74=,iv:gWDNAyefQqPurXXAVpERTBpKNCrrHNl5aFHqqxAd5ss=,tag:7ul1G15UbtIQ4A2c1rUt6A==,type:comment]
    #ENC[AES256_GCM,data:bna3WE6fxbgV0SmS8/7JkaPvIUHHLTMm28Dm1rSalAozfzXTU+k4mF8lLXz8CB+c4gbezkQv,iv:YOe4xeKn7qBQR7S3fWEPNxzXO8mJNcFTeL5j3cdHD4I=,tag:tGhGmjqxsepEAf3Zst/RKA==,type:comment]
    DOMAIN_0: ENC[AES256_GCM,data:eWqleEPIwcfMjjRTLbQAHRc=,iv:jQOIiSyTXJfzag2GCF7XzKOOA4PH2FmWE9ejLStKhos=,tag:N3z7OFbnkKyzR169rDpWYg==,type:str]
    DOMAIN_0_EMAIL: ENC[AES256_GCM,data:+VvltdOQ0AMUviRIg4Oyfl4Mz9zFHg==,iv:EKp3p/8lHyCv+TeKS7iHwJ4xy2JgLWKqWSp8X3LF1PQ=,tag:pbzx2ASrd7ua1uTu6fMD5g==,type:str]
    DOMAIN_0_CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:MJidyKt2ItEPMlEVNCv85mzMYa7pQmRFcDn7RXheIa0akmMw/1ukEg==,iv:bWeSdm7b+YacMPZC9nr1GZQVU9OtTbJ4Rz5b9GT9bfc=,tag:RX+pXHKH875UevIBkMrb7g==,type:str]
    #ENC[AES256_GCM,data:j3a0KcoDcvlH98rzMWedoLlXccYOz5WuMeSqGi7ROPzvQAzvaR11vPj6CCUDyf21M7hC++734AQ=,iv:EwsocV2ByCfMVKOg+UMPz4fk/kyL96sAoXTKj5RnayM=,tag:G2lgtxm6X9cTYO2doWSkaA==,type:comment]
    #ENC[AES256_GCM,data:q6jQzu47PfvSKYGWrB//7UlP5gws43pcEg==,iv:ksbZg0/SenT2akaYcJSgpAuKTHEu8YMjq+5B10DoCps=,tag:7yKmC7OdCOMbDCqPE+MuBA==,type:comment]
    #ENC[AES256_GCM,data:VtfeYM0LYdkFdU2HKWgAUMzYTssZzdp7AZygc2WSSBmyQ2xhIXX4uJvd/u3uvwbxlU7JAgAP/bQ7RkuYuPnEbANpoR8Y8W3qCfad8e4=,iv:CcbPPI1fSuvcBfVQGLvnlSets4E3OSixOXb03oBkSwA=,tag:2PTzOXxABh5ihnHImnq7fA==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:VNkaFmaBuvbgT9yiqAwDBSugOO/XcAip0hbWDB+cpOAW1i7TynE+ftr3+14QmA5fMyztgUNweiJcVw==,iv:4VliCI6MHd3FfH5+bItsSfA9Lgl+2z/Aj66Wf6V5t84=,tag:qjfyrmd7t6xLG81CHaR/tA==,type:str]
    #ENC[AES256_GCM,data:FJ5GyxtCAnDNIx6ChxnKi0SQySrhLGYScHUBT7FLVJi0h6UQ+KENzSdj6LRroHXH4ED7r3JlxwaJU6UEpNC9eaMSoOZ55J8=,iv:AAVgkOvEN3T7iJZoHLqfbRSjvp1Okt0xGbTAipf2jnU=,tag:PKMo3AJ5cjuUe8Hiu8yDww==,type:comment]
    #ENC[AES256_GCM,data:CPjZf1bv1wOyud5REzB5K340ImCWj2hO3aKZ9HZRE3QDQyynuf92xhjfw1TIDeEwSW6jc8EG,iv:bQFjZdEIlNmusm0LitW66eADya5ApZEA7PvEumV9bUg=,tag:foiBLmqm29WZSQ2gO1S1aQ==,type:comment]
    #ENC[AES256_GCM,data:rdT3UPqTLczsHasIkdnO7DHFm4yy7FUteqfVBunPwtmjgcU=,iv:YQJwwvgPPTGigx3t6KDuRARdqBWgEBavuCjbz5DJCQg=,tag:7Z1JHT00tjIPmULzsopAww==,type:comment]
    #ENC[AES256_GCM,data:hg0X3tf/UlZNsSz80lyUipHfqXaBHzk81aCUMI8NDHtJt3CNpEcQ,iv:GtXhHkapZmK8xkw7nVDy6wMQ098p6jGpThYaO9k2W9Y=,tag:SuwyAQPV3RKpfDqb+fj4YQ==,type:comment]
    #ENC[AES256_GCM,data:WpaQEoxyivwizeWIXsw=,iv:0mE+jyg+WTgn3FoPzKIW0IoQN7wCn8s3r99lhfcE6d0=,tag:W5xtDFKGv9isEDm2ju0yJw==,type:comment]
    PODNET: ENC[AES256_GCM,data:I+MynlNPcSscxd+rPw==,iv:TCNBabBK3nlEE09NTFf6QYT4tRY/9whfn0Q9Y1XSWsE=,tag:rahTGcQIkQ2/GUqmkvDPuQ==,type:str]
    SVCNET: ENC[AES256_GCM,data:YQZpWGs0TFjOh+kG3A==,iv:Ng2umIeEIS2qvEg7NFlHLpqipZi4f5kCrGGx6O0zf1Q=,tag:r7cf4qlOKh7pt5UoUBI+NQ==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:tLuzmA==,iv:3zH27dSWI8GwS+VxMmczPt5DRv+MUW/eppvCbsODXBw=,tag:gDC0BFGm8k79MuijESawQA==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19wg3490scy7jf9srcmzskv6k96nj9fx77psdqkxpt3lg66j3fcys4xndsq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqZlVGMWJPSmg4NXhDbVhJ
            ZG1PNktyR3lRZi9rclB3SzZpbjdZUFkyUDJzCkhyVGpMNnprRG5ib0pLMnhUTEhW
            Y0tQMVV4c1IvSEZkVWFsT0Y1TE5nOVEKLS0tIGp1eHN0aStYZGxQdU40MTcyQ0Vn
            TDdoSldidzgzYlMvc0Rlc2tNN1ZyME0KYBdQ+imyM3n02z7szr4flzRsDxWwG5CR
            WiDW8KppvGaXVdSiCgRLn3o6pxHIZipFlwsXpaPtOr8yyMK68GxrJQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-22T18:55:15Z"
    mac: ENC[AES256_GCM,data:vp6pb3HRwrWT5pAM0Q20d00IT6XTn4md2C7TTou1Tqn0DX0xGb8irQ0quvX20z/xic/leAjTMGbncwbJKz7oLR5ucMXy8Xs6QKgn5JwqeCKZoZz157BnuLERUX+Ic8QcQAtesln/ZcMzU1vBdPDGbxyJ3TUKGZACrQPBYzEDJAg=,iv:BlmspyUODt4R2UXsm1MCa11fz58MOa2Ynx2Ay9mhd6c=,tag:wT/gd+ifbaiT72a2Z7BqFA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
