apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:3wJNDigiQO5DQBUKzPGzhuvdDhSMqKN5zKDGUfI7gqWuOD4OaV83OaF48ZYP7YLfoc+70lrwuppscyMbfLr/pI0=,iv:hgWw5+Q3fiwPM5jGYfFiY7acGb1Z+LRyrZmM8an7yCY=,tag:XyT8vSFUjhqC9uaFlnMP0Q==,type:comment]
    #ENC[AES256_GCM,data:ChC3aPbnr+DbMSmA+OVysOnC+46ncQBxH25J/u470CprYTgZAIdydYVUYaU=,iv:AH2buCVD4tkDX2NVZzXu7on/xR75r8xi2iGQdqIUKQo=,tag:zJdinpUrcg8VITLESbqKIQ==,type:comment]
    VIP: ENC[AES256_GCM,data:LbCax1kMNakvcQ==,iv:8nc7mYC1HrHhGI8cGvWolcfaq5QblKVU6glCur5Xow8=,tag:p0r8NcdKhFRX6DeuY7Cp8Q==,type:str]
    #ENC[AES256_GCM,data:d8eGTHiJ1XxdOK1cSQwmJ4ClvbIK8Yd8e36B,iv:oTS9wucBJzn5qJRCOJaHqvOtKdZ5J7+RgRPzZnEZPt8=,tag:yck5I6Ka915Vd/h8wT2O8Q==,type:comment]
    #ENC[AES256_GCM,data:5YxY2QD/6RL6Gb734S1rbcu+MCkudJH7iPmtcaw8/LoE+T234u7YtxIGLLYzzDIOold2L9w2QS5hEn9qASAPHdTMDVaEsvvHjro+vg6ia76b0kWCQ0svBvA=,iv:IsZOKfH/bL9BmhMJh19AKHa7BBGPCDVPmRIK/C0joF0=,tag:gWEWWxxgLYwMGvnfMNv8zw==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:8ORTBnkFn8sUZg==,iv:HBNwGtKgM/el+pmFwwoqAv2hbZNleLG2tQpy5QAFn8M=,tag:mwyMRHlsgxD/LP3c/jZzkw==,type:str]
    #ENC[AES256_GCM,data:SzbUcUu1/CXmUW/LMfrElNffj1MBJqduwDlPXwfhbrcPrQ==,iv:RrZ2hGnX5xR2T+s0UuaeldSnx63SdCBfGW4+PC7QN9s=,tag:hHDPGA/OQPrhRQ13As3QEg==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:3b8Y81FMvlni,iv:EQN7mdtZjV2MnfQiNGINkJBq62/rcm5XU13QQp6NglY=,tag:jcya/WDCFsC2VmInbydCsQ==,type:str]
    #ENC[AES256_GCM,data:/wMUFMHdYgGZx2lH65oBPnocmYccPYWbD+Zcehm/7bfGw8T/U0TJPCmrAperB6E=,iv:EZ2AdMPIInuRz6YRUIWmFE9C0DWMYiwAhJPZ+gx10kM=,tag:5MaxF4+gh8EIXsM5t8BpNg==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:QtZ+xN1mX/y2afM9eYoIcPoXz2bugw==,iv:vzCTau3LiPYJmWEwWH3qTNdeLijDg4rN2Ya7srLYOSU=,tag:vvOG0VQiIg4r56w0dyONZg==,type:str]
    #ENC[AES256_GCM,data:6E65Ijs/YFt4w4AMGxC5pHoJGUDCHroclUQykrx7MTWzKTMh2M+iNdUfH8EMW88kcxInq2GymUEonw++QX0AYRUUjcI+ZOYEERsicNwWZkudfA==,iv:DBnLNTp05aJ3uKrJOIrF9W1OtIVKQszdiO3K34aWXMM=,tag:KIA1X7Tu73QUbW1lW2uf9w==,type:comment]
    TRAEFIK_IP: ENC[AES256_GCM,data:hhWOCCneiy72AQ==,iv:70OrquhhEZryPUt6Eq4kCbgC8+6IYxA3Ock+6NVtkUk=,tag:18UOMXAVJvq0lFdp9hTF5g==,type:str]
    #ENC[AES256_GCM,data:hrGkDgvGLlEtoafvUgcZgGvvr09KUxjua8KMszcMBVW/,iv:/+MelLJfnrC5lfr8dvlgJaQ7ZH9LuKQhiMsRA67ceTk=,tag:JuHLtx+pOq7/XZV6hJipUQ==,type:comment]
    BLOCKY_IP: ENC[AES256_GCM,data:ujdGnFNQ0n/Jya/66No=,iv:tA5N3zjmYn85q4Z2+v12iIWBNfGU9sOPVAvEU2tcG0g=,tag:XLNmDNwPPcctLoclZ4wHOg==,type:str]
    #ENC[AES256_GCM,data:e6DJ7Sbs88Uq5iX0JUTuPLca5UQyeTSlmcF08eo5GDPcHGLhsmNlav3u2WcYUjKINdW4O34uw9qWjZUUJ3BNgXWtNGhb08GCzpf/95qS9ak=,iv:mL91L96gS2JZatxX0yvXorursi31QkA9yg3lvtkBsWE=,tag:qkNxoqxa3b/KNdmj2AQUGA==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:rUbSonSYNiIGEGc=,iv:v5vlsA/WYgbYa3riakW6qxb9TIU+u9PCn0Xv0lC+2HE=,tag:SCoBVKIFyyP1HoHo6GI3Nw==,type:str]
    #ENC[AES256_GCM,data:Thi8SgvcMC7KO2NuerMirhioZXoAtMH/cqKmDjsjVQPuBj+r9z7uZDM+s8fx1dx4p1xdgGP/K1EJn5mQtyQWE1rt+4iF45GmzWlfT5cGNuOr2pv+FU9g,iv:Xf1M+MgxdxGKg5SbaBvmMzZV23otxNLHr9JJoftvoXQ=,tag:srUZ8MySHZTw1330ghfxpQ==,type:comment]
    #ENC[AES256_GCM,data:3EpU+luXwURgWQNN4Cvf0S64JG+POpPEpQMA4535KWjkDJnXGW5ZDZ6j/Qn3/og0BrM8RyRMw8YapG5ghSryol51E8T7+rxrlfPq1+bSowJdJXeBlr9Fal2o2NlrtnmmCRBon2TPtt45IKoYuNCKTGMwyVGzTBq8HR7eiw==,iv:PeFoRVJB5X0TFsIFlaFm1PR1ekEpVJ5bLNQwnIuO4a4=,tag:8X3999vFkwFjc8G/hywFfw==,type:comment]
    #ENC[AES256_GCM,data:2u/mTt+7BDvrT551AwlBC8t52aYVLPaZ/LfF6hl6Y+hRA/yFI3IlN1V5HdgrUfBNNKMiB3FOcHwzO1X9tyk5Bb+van6CegnljtArR+ZJqoI=,iv:1LQYmLPwOihe1SykjRlqm1wX8TO5JqQAFSvheucSzkM=,tag:KyZwJCrTodwGxV2GJA6yDw==,type:comment]
    #ENC[AES256_GCM,data:UD4foAmo02Maq+mIVYl4K21r/JgpstwPhjT4w+Hv68XCnfs8PUFi8aNkAGRUQx3jSnEhE072,iv:l+lYMvvJ07rTrl3agCW4lqRAaklV4bALu+H1qHUDdKQ=,tag:/e4Ur/XTnhPKq0/lgf5qkg==,type:comment]
    DOMAIN_0: ENC[AES256_GCM,data:WP11hogCIlpc1K0PVpKAMX4=,iv:Y6NdZHHnH2UIITvyqoHJuX+uKCj2TT+J/7m0jctJp94=,tag:esVSc0FPPc30vFzi2VbHKA==,type:str]
    DOMAIN_0_EMAIL: ENC[AES256_GCM,data:c23oDnCSarCiq4DDmdGZlDZoXYu1wQ==,iv:R1chT8QtLK7/YRmduDmPv2In64B2Yt1ytRVZDWAx+mY=,tag:5PfM962xvWpaVUBZouoXcw==,type:str]
    DOMAIN_0_CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:I1bKSyFgB25MR1ZO8Ld3lXgPpf8ui3uYaVZUDoDhnalsNwXOyK4DGg==,iv:aLP/p7rPIYLKci+Bu4ljFVj4SKd1JnGbtYz83WFzyWA=,tag:mJxBhaZLjnHDzj8vUyafww==,type:str]
    #ENC[AES256_GCM,data:jm8qENnzTH0hraIXdkatwzXVcEqZEeu/Lc6nXCt1mGOtzGcFrY26zwO35uOxS07IMb+jTo/FPUA=,iv:vTWGJXdKCRTlWXIcK1gmzDRY9UvXFkIAE29HgisO/MY=,tag:IJKjsmyyDkSwcaTRjsxeUw==,type:comment]
    #ENC[AES256_GCM,data:8bh78lspv4QIzur5M74bAWoyx8hz2LQWpA==,iv:mqm9SQMuyO96+YVYlKX+i5jKCv7IHUnnOKETEOPDLjw=,tag:n7VizZgVLTe9e3N0rS8GcA==,type:comment]
    #ENC[AES256_GCM,data:gLLbMeQzz9lSZKoC97cy7jWWJNlWCiGY+7WS6aJs1lpwUWvJ+k1UrfOGen+iikF86ZhR4VdnhRA2jQfrkBFY8yNeDxUHRfp7WPykMR4=,iv:rInzXvQBcC9eYxcKFw48c8i215ALNnIaZIeMCWP6Znw=,tag:TNy2LTBZMfWRW+q2JOqAuw==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:LIcWOKzyvLYfNiEMZWuEyF9Zzoh2Yaw/ywwThakvQy0rlrkVPli9FVAMXDASEIqs2CLj7eMCyLVeiQ==,iv:L1nw3+GZPohUBMTJ71FNnpFJL/vRgWUJhXe+yEu4Qo4=,tag:cUJji8WJn/EhenRvnanePw==,type:str]
    #ENC[AES256_GCM,data:u2qERNExyKDjV2G8qS+KmntFfFTRB1zA93eMv21FuMZcMx8uA0KZPS03WI6GTc4EkDn9Vgjnj/s0VVh1HDGai5YrGLKJUCI=,iv:SU2xiaxhYuH5nFgREtge5hVDFNLb3DC/iElfDTCukHk=,tag:KuH2p/nqoq6L06aqMm3h6g==,type:comment]
    #ENC[AES256_GCM,data:jrf7vvPtumDjzZrOGSH2h/k8d03AQ4ouVENndxqMBmOgEc3aknIDub5gCU8mKkjAW/zduzB3,iv:SfRqWKKR11Gw/XbqaI/qpqcCKOu/RJ59tn4rXAan0Nk=,tag:3BvFcdntnE8jbzo04EtKjg==,type:comment]
    #ENC[AES256_GCM,data:FPoHJJH1wdbWwzefNNd0rfCnKxayhMtxC2fxHDnQULoTxTw=,iv:d7S8CVzQtV3AVM5TEC8D7K+SU1ZS7jOpFDTui+C9pPU=,tag:ghhDzhJSL8naTFSa+KYCQw==,type:comment]
    #ENC[AES256_GCM,data:4jGyQHEhHleDzYY4vWOMf6VZQfPSUaS3wSJSuc84sg6WeWMA5Z27,iv:KzQTdWxpXh3708/Qr4ie10n0oo98lJaSBf6cYzZMfY8=,tag:9WQ+O8/m04LMaXpJEoy9Og==,type:comment]
    #ENC[AES256_GCM,data:sUKaPYTssHo8Y8j+X0c=,iv:hd/aPlWZjnIgQkAw3DD2T7Ju4uPDpAcegiVK1Lr99zM=,tag:2Bvkg1aIr85eQELUY6gRcQ==,type:comment]
    PODNET: ENC[AES256_GCM,data:J/B8AXEMQQJlh68VWQ==,iv:jwWkpAs8Eypc4qt3I+xF/i2vpB8rxpB74H9NDZjG8+c=,tag:s7i8upKaTqXnZLtohWn9TQ==,type:str]
    SVCNET: ENC[AES256_GCM,data:wc03iuSjcpTcAxbeRg==,iv:crUi5OTKT7KC/F4u4+77yRZ/BaXzFsVAZ2FmVme0qQM=,tag:Wx94Jto1ybBqlb0WDQtbCQ==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:PSLpTw==,iv:JeNIflEpr8uPb3SsvE+jQpsNDSMcb7zDvpwIHWpzoks=,tag:A+z2FR8NelMiRDwqQxlv0w==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z7h4mstndxkualruraf3vw8gugzzgulm8yzkrq70d4kjqd5yaqssjwksf9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlZ2wwUU5Ma2tJNTI0aFd3
            UHgvRmhKelJGL0ZEN1ptRlBFeTVZaFIzUkRzCjN2STR1NEduOVUrYWFwSytuV2lI
            MFRjd0V2dWpiY2VXdUtjeW1Hb3RMZzAKLS0tIG1rdkFVKy9FUG1DTTZBRTVkNTFi
            YTdXcjROYkRaN2V0d2lrSmNpZldnL28K8xl8X/e2XlN0AQhastHQqsw0FTjBY2cK
            zrNLctThxAFSfzqNd+hJjZKEUJ++77KB7P3c/SY7vsEnE0U/7Is4Xg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-21T16:47:31Z"
    mac: ENC[AES256_GCM,data:eU5SFmfPbPaYSIYng5aej4PndWGnjQVe9bRvbl/T2qZIUwGod+SILGzuGgJyp3roXaJ2GbqM1AenlInwB1xhKqD08QeiUBrmiyzccNALDHgDijPIZ3DvTu3D/JCrYx7ZEQas3R4tFU9du8rv5PuAxe+Jt7douSEQNpl7P6bCRc0=,iv:bMhvmG3dHB5h97ryCGzyNY+5AnJrdSMrigoyXpfdTqE=,tag:RUA8ka4nXMtDi3WJ8kDUxg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
