apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:jRhA346vHMRyaUr401GGwdGAk3fruq0qq6OwWMi1Qfd7XozwKJeCdkhIHIL5yLEKVOtfJRBsjKnFk9NzVwoZyy8=,iv:WsJOIVM524+aCN3PxwCfEm421RXRh1siaNDvbYYPJT8=,tag:YcQopZgkQBoOLa9YniSggQ==,type:comment]
    #ENC[AES256_GCM,data:Ky3oLD5z5oMhthdiClo4BF5y+Ue8O7qdKTVG1hoqBkkdgahosCNgohEsQ5g=,iv:omAMOP8toe2cAQQYuyu5H+DzxgO0VsF83nE0N+qD5kU=,tag:tIPgpG7CkvET2LSZzHjEJQ==,type:comment]
    VIP: ENC[AES256_GCM,data:f6xTBb5vKkVznQ==,iv:rDFhFI1BvsNHoZnAJucekYJE1nwh5CsSl/RcZ/zJNIY=,tag:VpOQrVhKsFNyHlpC7Nw1Ug==,type:str]
    #ENC[AES256_GCM,data:Fg39j2XOZ+28E9huZ90HmFNOUZlqaZwjaaB7,iv:cG2iXrMnW1q/sPV9jfv8i7eVYqP6XaOZ5K0pOc0Df+Y=,tag:AB7oXsg2Sg9idGoBMq7rpg==,type:comment]
    #ENC[AES256_GCM,data:mZgviQm/CWe/sSit/jj3vWxqCOkeBbhxsNKfKlwwEZcFsKYmGvTFicMShPkD+S8RK8y+uV6e4CJfzsBkrQDf8mGiLlkg1G8A/ACB5VAdje9LdwmV8anUJD0=,iv:Jc0m1+2StomRe2JzYp6Bd0Qa0+411QtQEIDEnrmLO38=,tag:onvVTgXSkJs/AYAd1erlWQ==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:5Rb3LClPInrVqg==,iv:98Lr2bBtZMMvN7ftWNXqcTYvyA0PzVMBtNNJF4Ynw8w=,tag:V90fh7WpNNk3gNwEDNfkgg==,type:str]
    #ENC[AES256_GCM,data:pLLaxZFoWWFvirEsbi8ntBi+UtjupfKQtSZCFwYVwbB1hw==,iv:0vrAyTTWFpKytdmV1ZGX8zNJJTnMc96CpooIAn9wc68=,tag:AHCaM+PQqHIYNsS/19T1dw==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:SgNRD7AbLe+s,iv:HSZOLEP9/Dod89vn14c4K4RuHbcUI1AXFb4KKdRcSXM=,tag:okzXc5JmxfJg/IkM9lBX6A==,type:str]
    #ENC[AES256_GCM,data:6STKWPUkQuvrFhJbCoH4oH7XE4A3oBgXiufJYxVHdvrbW+VaXUGSPl8luGuOkEE=,iv:oQ+NicC9zNeA3l3V8v3mCyiKVk5z1SREirjHfRgYRkw=,tag:l+WdIkntzGGFC3/MSZ/HlA==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:zo4RRB/HjYS8EZjMFUOy1aNdfEfGfQ==,iv:i0OlJG1gao6jXCz6WNrVUMeIpL2AC0KgIQ3jRlw1Md0=,tag:hVzGySnE1zk+2D8Kvkc9lA==,type:str]
    #ENC[AES256_GCM,data:1kyz5vnZbBCNrWaK05PRxY8CF+BkT1slFvFMtixlqIzU5UYUFot38TvLqiWaK9QzzNwoNTvdY1/1luvoW4IvBFD7lOFOkp+Yh014y+Dt30pq1A==,iv:GfjfCkpCj89H1Ej9GKbbBgREKXgMyHtNioemrLYQN0k=,tag:VmxsYFj9l+7gNjjTS0tajA==,type:comment]
    TRAEFIK_IP: ENC[AES256_GCM,data:WjG5lqGbq3fCFA==,iv:AUMg2SaJjMt5aDaCAtEd6E1dM7T5z5qg7PKbzd9sSKI=,tag:7qRJa2KEajWw4KTlYA/xVg==,type:str]
    #ENC[AES256_GCM,data:OJhgH3KZYtaetrcVfRVT5noteR4a6oeguZ/ZVBoqR8kN,iv:HYvuSt9Asn/hRDZGYgnrdDo6oSkDQO+lvtg3sZeMRsY=,tag:4ZO+XzcnpKWwZE3Uc2bxjg==,type:comment]
    BLOCKY_IP: ENC[AES256_GCM,data:p5sQHlWGaiOtBA==,iv:Qnls9/zjKmfas3qR5neewQBaE0hhuo461LcmCbQSBqY=,tag:GWgacew1mCB38bmsdeHHFQ==,type:str]
    #ENC[AES256_GCM,data:fOr9dvldM/XIs6m00xFr0CJ16TlNxN08ZFUqU/5BbRpH+EX7eozGtdPG0nXvpk/af8MnfvcKPVl4Q9c0yCVnPL6h5qh+/Nh4vCxfgSd4k1w=,iv:Lrh3lyHvuspfVw/PZH25L44kUSnlmPDfhDUGVBWVK3g=,tag:og+7jMUuU0nifXDoiGbEGg==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:VUmNFzlfjlw5tA==,iv:f0ucWVnUGdVM+dAxZnEd8ntnwj21zEu0ScdjdwpY38o=,tag:fEhUycyWAE28uAsLP817EA==,type:str]
    #ENC[AES256_GCM,data:g77FdeWzt1yTGA1U/gINB76CzCqTpJp07uc70wtclxLGtDz7RGaD4Fyoze3CRUnn+7Qh7W4EdyiT8VzL6fUd3ltapPtOga2gkW4XaQs6ZrpZSC3IitJK,iv:nLXfJvAKhySx/YFb+sav2qZznlFgq0AS7mkJPJxgjlg=,tag:xXRdb3WyI55+EiAtW1SytQ==,type:comment]
    #ENC[AES256_GCM,data:WuwXdBchPCkLFYF9c+J1oZiSv2633Evqzg6LA1W6qwd0aw/rwJV8Erfy6X1uA6xi7vbpaL/PwC4M5CrphBEFH/3EAczY6vnSoXkH9coB9iZPK1RPeV1N64n7FrGqLmAmKSVAwRayLF7yR2uIgT2uBvvM/IRQ4NmGRRGfOQ==,iv:IPg8eEQ6RQ5b1YEX4JB6G6o6R6KG9r+Xo+t2ClQkD8k=,tag:5vDRUawDgMMA3hubhHcwWA==,type:comment]
    #ENC[AES256_GCM,data:rxVRZ4HtstLJk7oAemlSDvKU3V0cPm7Eriv8S1l6njZFzBf+sPfPk6DeYcnK473ga/UZwBy+Pa3rCsn0eKgpXX5tzhA1dLb+qm2xKMPM2iw=,iv:uXk5Nt2BVHBx455pwGty+fXccLY7fjihq2aS/NFzikI=,tag:HfSTMdJPMBCDKiopW19TFw==,type:comment]
    #ENC[AES256_GCM,data:1MzzxCsmi7G8MudYEyhbrDyz+u7OlSE31CyZVnvGjPk1XwtScFIk7frK0nsDSYqO5fhC8doR,iv:7aB+pd68MsQAbEN7zAIvrOZQfzPhCeckG8mB+022UUY=,tag:7HWHpJdoeAei48PMxAB4rg==,type:comment]
    DOMAIN_0: ENC[AES256_GCM,data:skcO9cPyvoU42jDmA57aqtc=,iv:3xM/83wZv4K6eVrE+DZeDA1ltGVnIVgu8YqwjKR4i0Q=,tag:KByvAYv2Y8jP9fs1jJ2hSA==,type:str]
    DOMAIN_0_EMAIL: ENC[AES256_GCM,data:WkGmlj69w4c9FuZyIi/Fh8RDaq7JQA==,iv:IBobfLSWbuJhuKUxOFS3chGeseF96zT8C3UxmKauGcI=,tag:IKtxNMwhxHDHm5Za4Xpefw==,type:str]
    DOMAIN_0_CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:UrvX2+2ufCGG4rRuuxccHXlbk6qurx/wyTxgzbb1UyrngQi4FUheBg==,iv:P6i5PYQsbjMCCOImQSh620dGmyBFbUN6oV4uowQbIBo=,tag:Y1GPnzydPSY1ZQyMVa5chA==,type:str]
    #ENC[AES256_GCM,data:aol1UbphaEYlUOt+XLWRvt7UsHkox7ieD7oI+WAOj8aU37J4dikJ09ckFVxCjFun9Wh8MvM03+w=,iv:N4wls3CXJE1XnpZSasevqoMHhrzjZQzUTyBdMsREilg=,tag:ngCy5kIy8heoRz3zOwXkDw==,type:comment]
    #ENC[AES256_GCM,data:jn5sOqShCaq+e+Q7Qz421HRHn6G3QWs9tg==,iv:HjTYJi70dpwgEJQLB5qL+SPRHoID0TTLE0jUKwczkCw=,tag:yO7yNHD6H91VSudcxFVTNA==,type:comment]
    #ENC[AES256_GCM,data:0AIfS7xp8H+Sbr/lQmRAvGJbmjmrwGoWLi0dV9pupBDtjqXkh+73Ql+ipa7fvISZEvRUNXdKVfdYyUVgj4xb+v/LzmOAWRb51AAizZQ=,iv:XFA0Z4qN9BPxmD2Mu25hckXOrgswJGatx0B/aftPJeg=,tag:inMLgickjo5zc2QkJhRoNw==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:q1b7TBv/2axsc847YDj8ItslovSwfAmKeQRe3Kfwv29pZvQvGRsFXCibaRIehqSWBDbemoCQlu/Aiw==,iv:tWXc0hSwbWdmYmhIsFHviKU5oyOX+DwNaktrRQRUHUk=,tag:ItvBcBJHlXwLjvRV8fjjuQ==,type:str]
    #ENC[AES256_GCM,data:SKy+IsyxkCtKo/hmBaIfZ/CLtckuMWHoIxf0Q4ppnt+jO6x8Xx6ssJ4FiJQK/D8xFzTsqflv/DhhrkOcLkR3+2uklLvQwMc=,iv:OGpvuZGazqo+Q+LsY2qW7tIOJM9ZyQc+zJe258k2y7Q=,tag:YZsmk1IyziK+VZCV3Wvj4Q==,type:comment]
    #ENC[AES256_GCM,data:tG17lveqd5EEOPoP3sxVkoFhqYpR1Id5MBbTZC7Bq0jqhPr+n+TAnwrkYQyzQDVK0Sljb+i7,iv:Y4f2OJC/bn9BgqxhlNfKG9yQahuRbINSAekByTOJzmI=,tag:feC/oTrubOjlys2PlAazsA==,type:comment]
    #ENC[AES256_GCM,data:ruIlmA8HouKsNFcGbnLQb/Rj0DwoFwJ/NFndPD/7/yNmb7Y=,iv:J+dKAtFmgOGgYWMbwg7gCEIsX4738X4vSfHsLgezsNU=,tag:uh1MMViJk/rQuDUa9OIR6g==,type:comment]
    #ENC[AES256_GCM,data:0ZNBQYWhqiynG4UW6KT/nEvKeE1uLsaXHlyguJWnfxfuZ9xJk4ss,iv:xnDd9WkWCmt/JnLoyeLwa+YSr8FvCq4UAs7R2eahfm0=,tag:GcDCI16T9NnGEe6ovPffYw==,type:comment]
    #ENC[AES256_GCM,data:edtfRgCWE5dICPM9/Ck=,iv:4khKWJUlRRZGlNH7g9LxFFtv8WplT1dz9KfGdxuN0CY=,tag:8QIIwhRzMG/GaC9PlDG/pA==,type:comment]
    PODNET: ENC[AES256_GCM,data:yLzcJrTUB3rfAoIdtQ==,iv:+GZrwU+O00hJ93tiWnZSW2WyeKr8LBx81HNfGLd/rtU=,tag:hpJ8FO0nFLq1FwMwML64xQ==,type:str]
    SVCNET: ENC[AES256_GCM,data:+NW6l9WtG648wNvRZg==,iv:Zj2UVgE25WqpwVsKvfPtEEk8Fdb8E/cBEmksFMwQkO4=,tag:wb+UaKamznxJfN0T7YDmGg==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:aAfQmA==,iv:YthvS0FZ1MqFrBbSr5RSEDnBvtw90RQvo6C/230rVyY=,tag:4n+oqvRdUCyVCAEhCx4Rcw==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19wg3490scy7jf9srcmzskv6k96nj9fx77psdqkxpt3lg66j3fcys4xndsq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTTTFLWnloSXQvOGUrdG04
            azFlNDcxajI3OUszRkR5STc2NnJpemFmMlY0CmhyaERXTCtYK2dFcUJSbm9mbTFY
            MzVqTmI3Q3I3N0dlUkJLa2M3NytYVncKLS0tIDFicmwveGFWTWtlbnUvUFg5MmZD
            SW9LclpFYTgxU3FncTUxWjlwN2MxSzgK4to8Xts44FmKo8qV2lbmPl8mkjWy849Z
            A+4DRv0g51I9gIjZ+ttq8ZSFc7na+kh6cxWzgWXY/j3lmgBA9ogn/w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-23T11:27:37Z"
    mac: ENC[AES256_GCM,data:R0h3vMuer3855lk/Myr1Als0oFFr8pRPBTd8hMK/pSQ60kXOMQtPDP2RWq3azQjDlNHKEdd+V9ctP2SuClEPZcye2qUpYYdvS5DGNoJFMN6ZM8dNDWdWAkoKSdQVnQp8tU4RRBZJxrdPZdQJu7k1443fHOcTkU75SjKIWfWMa5k=,iv:+6NG5/Qy0iNo5voMngtumvwPI14Y4nJMPeYm3wV+nUA=,tag:yi2qIwdL19pjDPCT0qvVdw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
