apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:sEoFXTVGLBLZ5MisFGi28umrjgDEWD+zVc4a3ahuvdb9Fp3dmigz0FqvK0xRxyLlONM1GHCs13yMnvYTXZ/sr8o=,iv:vWK93574Aq99caLMycwGjspZTWSI9pYP070EDStVwZg=,tag:9Xqt8FBpMRTj3oHduISpRw==,type:comment]
    #ENC[AES256_GCM,data:viB4HdaECIK629K9g2RYoRxiM5hFL+00XT0BPBwJ89QKfW3WPZSjHHPYyDA=,iv:N8s/vFun7bxwCP3xKF5iwPK3Ae/aNKqH+r3b2259CZg=,tag:IjXzXn7LCQfCfOVZndhlvQ==,type:comment]
    VIP: ENC[AES256_GCM,data:l9Rmdw0rFFmfSg==,iv:/n7duDg24UWgNqFc/xnpGckzopq6yc1sVJiThNsjJuw=,tag:9U+DNlB6V0XVaiTg+Vw6VQ==,type:str]
    #ENC[AES256_GCM,data:p145E+ghf+pkXB/dhGA3C6o/7oBC48xGEIzZ,iv:b7aDq/S4VmgN7jcu3e8luj+kc/7pv2dMeIHzeNy421Q=,tag:FoP52iHMCrMBy3p2inmMDA==,type:comment]
    #ENC[AES256_GCM,data:DRmL97M09rK++VpcldHJlId+GvOTDFFSnxUpHGETMtILWxhOLYoPlyrDXFXvC558hxVnvad5j2GEV/cBDNnsKf4ylwFW0DW3HnaEIoybhyEX/xWsUc5+yUY=,iv:2wH9xdX/CBQaEF/or/nzRn9EuyZnLkiabPtGcmz6tNc=,tag:W/BXQWHP9+DThB6N3p9Ojg==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:NbdCQVRHmm/QyA==,iv:hC9OW7rh25FRZfsVrnlfUoUvlSqdLw8T3LuKg8gmh1Q=,tag:SPl+f1J25lMxWJLJlnShIg==,type:str]
    #ENC[AES256_GCM,data:H+ze71dwq/qyucD+vk+RfHIfC4ArMm/5m+dzgH2UevOp0Q==,iv:vxIXQDgjnRMMEtIVcgE+C75K0M3uIIR+n1kED3z7Ack=,tag:YVygYF0FDvWKEvb8DwHmSA==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:6Age28X3NPaJ,iv:6wQEmEixtEmFUM7dF6KAeu1jsmou1Gi9gxxr3x9fn34=,tag:vvbwMP160OpmTD46u6Z+cA==,type:str]
    #ENC[AES256_GCM,data:HJAEydgkTlRu98kHbyd6LOLdjMe6xiNkhRWcbbdmiubtIMu3io6arK7jJpIxAqU=,iv:l3kt32buXQj10l54pN3vajW47ODclW5ah15TR7JJzwY=,tag:8oG66iwtOSie8HFrFwjHfw==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:J3tbDx/9yFu072VXGNHUFvF6v1m/CQ==,iv:Y37bra5w1oq6++WnYE2PHn1UdkNy+4PD6VsXa4LLNCk=,tag:zeGesmvj7Tzfa8GudLThOw==,type:str]
    #ENC[AES256_GCM,data:rUJxrQTuSxSjP1/m6CkHxOO7LPWmtiF9GW0jR3RMuIQTB0PgPwNO1n/5zPs0lvkYPtYTokxWJ31Zpwn77UT7+OoXW6Vcu08Rnqk8i8KoUPNRuw==,iv:v6BxYTJdM30H6x2CKM9NBe5Yq2eqrlkztYweB5wQUlw=,tag:S6qsoNSVZdk+0hgf8Jr0sg==,type:comment]
    TRAEFIK_IP: ENC[AES256_GCM,data:H3wlB93vjg9vhg==,iv:4BW3rFQHYAmcRRvWNCJDAiCYIlHXkJQhYkL+Dvo/itY=,tag:pGwOSncsljqGo2PucCnRxQ==,type:str]
    #ENC[AES256_GCM,data:w+OdwyUqiDASUfd8Wlh6qYLeIlt+uueGY5VOGHqKIc/B,iv:XYcSxY29PagNO+1ZSaxWpO3zMrerz/cMUSVcb8Sa+6s=,tag:WAbT1ADVrUJXk1PaPaB/7g==,type:comment]
    BLOCKY_IP: ENC[AES256_GCM,data:JYp183a6tDmKtg==,iv:fTHsTtgvVZV+X01dxrEIElkKmME6s2IwGAbb1YtGpYQ=,tag:RD6emy/+cuz9WF7/8tc+PA==,type:str]
    #ENC[AES256_GCM,data:YEwfopw7/Z5/x5Dr+ZpN1DCCEAnUIzeyDa3Ep0IeAi4riBfjDnU2rvCfKQpLw+JTtySIPELlA+2F3j0tM1kSw7345r8n0Llqp9pORvY6YNw=,iv:LRJdMU588ueXJ8qAH8Yw4JJ/KGeSrRqYCi3SuLnde+E=,tag:8+GN1rRvULEYf7/AwuXuWQ==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:av3GAd9KzMYvsg==,iv:FpKLek8lWpoIvu4jpCNoA8YXO7x5l4DrINQJvul4CNg=,tag:tEgkN07FoILZXAHRdL1rFA==,type:str]
    #ENC[AES256_GCM,data:abVf/HKAnSgBonigHXKvEhJE/hcCpNxlIZi2PDBE4kMFK0a6vicv110l0J22SOHoCuT8ukDuVkkVIR+qhPGQbE4Tz/UlcLVHcTWwuAZXsbQgZLbgkyjr,iv:APJtmJaNPXTTHhNeIj0mqH5UE1wjX64NWkio/tfO4KU=,tag:mU9ACdRcqUQ1CTjPj8gavQ==,type:comment]
    #ENC[AES256_GCM,data:Lvx0fsGS0ekAyELh7tIR3rOX2mJh4RbkLsMQuKgsYke8xR3rEpK6srXRzU9xlIOV0gqCqCWyjWft1HuTdJWivNTn4fQ9clQ0PW0drpAAaY+cGq7oCSZuvclIU6RNjsroo/jejJkxkPBBU9m7O/hCBzxIYO2PeGb+8FDy+Q==,iv:Bz2O9ZJVUE4eI7OpWqNDe3L2GiVLCa59ZwYWxDxXhOw=,tag:WtNT8eeczrl78ahoz0Y1iQ==,type:comment]
    #ENC[AES256_GCM,data:pUpBpZFSPmjdaCmV6yXfmXM4a3oaqXcU21iCAZMD/Qm+sh3Bh2K3t1KYgLHzd98NizbJzONBL0sWW6d3URgk3hOmLJR/3LmBXdXRMO0q/yo=,iv:xaP58Mz5wKqY+UMdq0FXHItKX6RD3Rjs+bFEgGcHmgQ=,tag:SF+N/ArBNdndw5uM40PlKg==,type:comment]
    #ENC[AES256_GCM,data:5VjyBtPfEP1CVq14o6U27URn7qbslDlZM4BpA068+zL3wSJupXn0xCl3v3W22LjJ/mC9+Bs0,iv:SI8fvywr/hHnYaDQmtu9KSMVox2jzmqFiIDx7HLniH0=,tag:OAUly+rSW4PKTMEgouLRYw==,type:comment]
    DOMAIN_0: ENC[AES256_GCM,data:JGs3R6Q+cb+HF36sPJEwwzk=,iv://NRaSBpP3YDUzEPASk4esd18vxACTXuYtNSC1MlsbU=,tag:AUu3OgUzSBQ+MVcYBHL9+w==,type:str]
    DOMAIN_0_EMAIL: ENC[AES256_GCM,data:9ydOfR4ghKo0XLMt7dLVhROGGj6ABA==,iv:kGXgtWdpQ/sqP7XAnlnT38UpXGg+BeDibGYA3uD770c=,tag:J4Pne2JlPxV63/Hjctgb6w==,type:str]
    DOMAIN_0_CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:diEt1fr2nWiD6EcWBPu6IsDl7WKn74/1Boj4iZOpuOOL/Bm4uOPXxQ==,iv:aT55WZC6DbWM4DNhUlxepL+vyD7QtGmlmc/J8pXPvyU=,tag:Cju+szcbj7LCB3uDKjf7hg==,type:str]
    #ENC[AES256_GCM,data:8+OZOafe9TlVxslo0WwDdsQ12bqclF8zThTHam4Uk05zUMydFrVTrTZ9lCh2dvOTgOYV0Le/ysM=,iv:uArbpyNd/7XHZl7wknUOJksYeNN3WiMhLqU1X3TlhZw=,tag:JHLCr+XKLWwKMtz/10wiyw==,type:comment]
    #ENC[AES256_GCM,data:IQ996SnryPYhYiZKdkuMRbg20mirC9Sosg==,iv:LAScS/tbnq8NOOgTHyczULUJgLTg+ixXl0i5vBLGBbY=,tag:Qk/enZgdjTF8EQrUdx47qA==,type:comment]
    #ENC[AES256_GCM,data:JGXMkafKREdi5eihiQpmusS5CdsEAYfaO9xdPcJmXPktRbyc9isxD6utk7x6UBWfwEMZ+zhUSvMNYGmSI+/yHzcw3qM/lR62vg5d/K4=,iv:uoyWLhWiWsSvTpFeEuyTQsg7wh3IgwAYggVuP0Wq1IY=,tag:0/REJTTQkiETvIThdzmLng==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:kFC0uwo52WsvYqtUhLcsE1LdLq+rVpZ9Y+9Afnahr3q3uzZY//kNswqYRn/hFt2fxwlw5NADgWfBtQ==,iv:Y0OeULZLPD/7h5lc+z9umNUgjVvtqGBzed0WsWNlbdg=,tag:Q2yF95bamZtjqKQSwdEGSQ==,type:str]
    #ENC[AES256_GCM,data:EEdL61d6Q5fAmRHTSbMChfXtay8EahRAfrAIuIWVB70gXWR8h0BBMDd0/3BLP2YhDsJ74tpyN1ywAQCEJeKrdYgZFTJW3Tw=,iv:ISQHg06jj0GpePua0bGwiCXqhp/w/1CGqsfH2TuKhK4=,tag:+JKr5oVS7PPq1PEwKcPL/w==,type:comment]
    #ENC[AES256_GCM,data:GAFCJOiG0PR23akwDUViyZqfW+crRMWma6wyRWix5DHALpIFBJ82EU/zF+4QxBo+CGRnYLoM,iv:REzUFq6CXzlc+AP5t1itmN/Vfhc5b215/xX61hcKuvY=,tag:OFKvjCrygpFehIeNNhJV9A==,type:comment]
    #ENC[AES256_GCM,data:BIZUmbyryWKd2k6etr1xYojV7HVnDRSbhCJJN1thXCgMybg=,iv:ynCNh/Z/2VeHzDwpjt+8on0TpMqCpX9nZtrDycbc0Z8=,tag:7sHAVqc9lJFBbaGe2St1Ew==,type:comment]
    #ENC[AES256_GCM,data:ico7jaf4jRSvs/sw4BYYsFxn6HWsLOW6DhnQxtsYHK9mpsLJ4/NX,iv:Au9kYoncS54i4djD8UWhcRZXLzaZgDMVK9a8cH9uHjI=,tag:hROvVvxgJZTqsGTxnmpGCQ==,type:comment]
    #ENC[AES256_GCM,data:xarGVnp4cGZTE2H/B9s=,iv:WS9HOYOovHkgp1+n36xm8ko9NLQpCzE/lEvBqvWztSY=,tag:z7tyVsL3my+6Vner7C1JDg==,type:comment]
    PODNET: ENC[AES256_GCM,data:EAi7o4+YUp3IC+xxhw==,iv:XiLvca5xsyy4ftiBhtNDHwwYBM/EgOQ2OexZ83md9Xg=,tag:ah82Vu9YG8UjPdtPDrGrhg==,type:str]
    SVCNET: ENC[AES256_GCM,data:LqnPyoTjyDbwA42y8A==,iv:strxDElX2hfGWc1bXPERPaJKSx3I7WakB5MLpP7wrlM=,tag:OEY8uotdu1o+UujpN+kBsw==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:X3ywMw==,iv:tSYHiaNkfaEnvHAMocTBwCUIeS+OaqLcufvf5ssybuQ=,tag:/86T5NNgdumHgwqSrtlnAA==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19wg3490scy7jf9srcmzskv6k96nj9fx77psdqkxpt3lg66j3fcys4xndsq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsSGtEdTRUL2toejZESGor
            cTZmbzkzanFhdWR1MFRzSThyMWwyczBGMUJrCjlhdXBVekRMc2dYZ1UxWXpXOE02
            eDk3MXhCUjM0RFpzamRqVHp6eE5POUEKLS0tIHMrSW9oUjJPKzFtRnNMZ3JJamF6
            eHBWeTFUUFFiOWkrczliTkZxdGJHRXMKgZW3dgA/xALN3qpZQtKOVRs6Q4HlJrnw
            YowsamYemJPXB58faq12LSI0Zi4BeixeAkUULg34YOFB0MphhjdK4w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-22T19:29:21Z"
    mac: ENC[AES256_GCM,data:J4rsSD3rjlhiGgr8QeVSuitHeyuGRZH58dr9xHMunYJIIYHlABK3Mv9vzgG6MUndZgumu+WW6UoJLHodjTB5Y8ks5eECBPf6GaBX3UhQglKjXaFN70CBo2SSBMQTPrutd8TgPCfPqR/2jktEVDmkykxETkY4aZxKOmhwIElqfDs=,iv:o2yA7BNNIkYHhUDma2xvEq4QN19vVexT0nwPgVa1ko4=,tag:AZN3lqmdF4wnjC/AVEfhRg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
