apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:IVj4LJjBQfCBg7UPjX3c2FtwVNi4JqbGhFkSwkkKZEw5DGhf9uEfMVJGb1FW5oOnCYkYfMCS4egChdUVnMpdry8=,iv:1yg3YnQbvmZ1I3aGMdMOvPKLdclGdIjm9lxVHOv8Y94=,tag:eQSwXbEBrrR9ugvBl06qPA==,type:comment]
    #ENC[AES256_GCM,data:334osvqoCsUh7SL8RqzZPKJVicGr8HNXmMVmNo9j1CcPcnceiuOorpwHBOw=,iv:tCfnppyXn8UDu0SWthufyDacoIlgJUAAPXHz14ZCwks=,tag:nhkgeUeiB8aO/BgH/NkUGw==,type:comment]
    VIP: ENC[AES256_GCM,data:NSrrF41yu8P6Cg==,iv:7ZmDl+jCO5g0SF2+rYPLJ/GThGcXzBbx/t6Ls65a4E8=,tag:SAIy5VRFtSSeZ0bkXw7J7w==,type:str]
    #ENC[AES256_GCM,data:RfrN/IlztCpVqfsxrj7rWSJQwVDpoBwwKBse,iv:+rH6DxqHHysFHEVPwAXxMc31Wp72tqMEYtwIDRaTb4k=,tag:F44iGgzsJNLam9zc+eFriA==,type:comment]
    #ENC[AES256_GCM,data:RqY79JpuuxlRfXKtXirI0C0sDzNzG0uxB6I6nv2bmKXsYk+NowOtk/ImaI2uLN9QZw9vc0XFFfPEtLCjaIBDjcQkDVe69BhjZBoYZfIUkZ21NEM5acNM+zw=,iv:6HTx31mMGg4ojHGvgSUajVhRkE9E4Uk5eN0uN1hYVDk=,tag:N591juuHnl6mxEoBh2oSXA==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:M6txDV8lyuJmPw==,iv:64/wBhDkxojeNO/UYSEPAvmmqTuYxTQyFakl/o/7d2k=,tag:acIbKsO+747CmViiEO3pJQ==,type:str]
    #ENC[AES256_GCM,data:MES6liPhop5BAMIYYi63itCWT5XWdR5TpGwjsO/DFe1N7w==,iv:lkIQ97FO/fGqzKZrevkibKk05iD0JwZjclel9+VYlGc=,tag:D15zkGAOafSLNJR66LOC0w==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:5FeD7i7sylbU,iv:HDF4PkGfbIk08JyvniOVkxWfhG1QC7hI9iBLKLPiEws=,tag:+3Zh0Lwl6A0KnM545h/6bg==,type:str]
    #ENC[AES256_GCM,data:lpov7kZQrDxEnuwQG1NgrSZLGvVaW/E+Bm69UGZk8piPwrU2HYrmsGTvdj0FVY4=,iv:kKqLe2sdtapiN0pqzIcxpvy7q6ux6DuBF+p3QZwohSw=,tag:q9EGiYTFnE/Aii/J9NYk1A==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:K/boyMS3Y7+mwzq94xLceN+Kvb0JQA==,iv:/RdasFk5Rp7ktrwolt3bipSvFFeLZD/gis9/cp8ThJI=,tag:zybvx4RoFlqfqzWnfFY5oA==,type:str]
    #ENC[AES256_GCM,data:XYrR3vwR3zJXZL2OlMprVseiVjQ+t6xmw0uZOReerDUr1nmHKWgerFhydlJ70akwyhuToWNpV2Lixyls+yziIuvCsLptYAA/8lqJzVPR4z4w7g==,iv:tqP0J3LP0i74fHFQkH8+pe+8jsZak+E8v9ytqO+ykXg=,tag:haE8PuwHaauvqwl920WpGw==,type:comment]
    TRAEFIK_IP: ENC[AES256_GCM,data:SSzRxcUCewHB5Q==,iv:jhK51OcidpDtpVRCMBdtc09FYIPtV1sXnaRqYHIF7yY=,tag:JR1dqrzDRkZU9BH+I+/f2w==,type:str]
    #ENC[AES256_GCM,data:/S7gycRSO4E/rmzVyTa69KbHOSQ1DfxcVkHtKhh1/tFB,iv:77Y6LZia2S86BPtzbuhd7rTnBAAL/kpdKy8tt7xAbCY=,tag:VusqJ0+dShQhxXEU19TgdQ==,type:comment]
    BLOCKY_IP: ENC[AES256_GCM,data:Z2yuQtT8ph4SSw==,iv:sgrLSogdNrbp0yzGN460j1HEQtOjLU38VwgKZkRTGfE=,tag:po94ninZfVdqI4TUurmL/A==,type:str]
    #ENC[AES256_GCM,data:8ICPfaOU9Wx80CW7wRv6jXB8ycnSFLUw9Y6sV+5CXmnzFg4t4QGKBnTyxOxKdW0RKpTjIHNbCgZ6IMuvBHLU2mCn76NAZC2LOK0oXCYEobk=,iv:hgf501Fwl95d5f+xItDelBuGXakeyfhRaBVNazacqKk=,tag:cAyMZsK20TaKO6ndkAbTNA==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:+dnRyY+L0cof6A==,iv:67Pg75LoeaZOwHH+Uc91+4dtVKU29DpxrDnnQv10Kj4=,tag:9cdNtvaBnOew9yrgSB9uiQ==,type:str]
    #ENC[AES256_GCM,data:r2sI70k1ZHsUHZ9DAn0Lz2zQzW07qx1lXk3MrSATsIAKS+fVBQWGYxF2U1LcEQJWkRoP1IXeKWWuVAXffuIyAJar/iBJDd+4eoXKXIwd6sZSqWP967gw,iv:iYXIHU3adJAry8C6snUQEvc1CUUB24z5F5NV5RwUTp8=,tag:PGEyvuv1iy/vYzclqEeQVg==,type:comment]
    #ENC[AES256_GCM,data:7CO1Vzh/STN9i8nhFHJpujsjIAoKkuotHom80/T8Yy9thzmuS6cPtVM1z9/SnEunaDgzWg2YqOKRQm1cqp/qAACR22ER505sgLbilSobdQ4ofOCw4Yxp2ELjomEt+SlmE/5fvxGBRnLoXwycn+dVEdoEnqRk/lHclo/RXg==,iv:d4TLkfH1f2AYuW6UTGNuJ0+2REbcUdS2T8sLrINonCo=,tag:NvJ23Ip7AhAf1DOsfJVo0Q==,type:comment]
    #ENC[AES256_GCM,data:3/gVum09wq6yyqhoV53tcyzo6HHWUCWEgOORyrPRrAi3PbqhyAmyarFVp83YCh2YkHRyqjjIetabDXtap+co/RWTKh/X1jLfp1bvGTlFTxo=,iv:wQ/Vk9Q3QTXFdCWT5BRPEnzBm/nLptd7Yp6nuuhQ/dU=,tag:8h2sBeARTsvWM0Oyu3a8oA==,type:comment]
    #ENC[AES256_GCM,data:JHYOkLdzYGsXWJHCkcMLMyQv9oeSiOfRI0M0HJx0HaDbadmNO2XWlTw9y7z9mMfDxpxBMvvx,iv:BkT0O/I7r4yC1PtjoL3cjiR7dfReqJB+j3yFGFdPZKQ=,tag:2KSOhJm6ueRU6wH9ZqvyUw==,type:comment]
    DOMAIN_0: ENC[AES256_GCM,data:T6v9Y+qOEZQREJ80+dC7+Pg=,iv:FsYTXMNO7mVxuiK+4cqnGOX6cjlJKj4baB2XSmleYP8=,tag:ngBslSjR5gycyzWAREXhsg==,type:str]
    DOMAIN_0_EMAIL: ENC[AES256_GCM,data:B7AvpZNmGezMK+7RXj7DNQnmQVndKw==,iv:JhPuCbGAUFa3thtFYtxgYRvprMy9Vii1t3vv9NjrnAI=,tag:I+hGD0E0tobUF8dTcSOCcw==,type:str]
    DOMAIN_0_CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:mA/gp/XXWS799VS8yHSvJoUSAJBGJvKgICLv0nZzTerP1PH0/NjWCg==,iv:6affcQAH0fE5hHEkZ/wNpJyps/vmZ3RI3yqUmX8jCGo=,tag:bDd+KviJRnEpHPttNBpyYA==,type:str]
    #ENC[AES256_GCM,data:0LmeDnfrQYofPncZtZ5PYLSR3U7H3puqyTT5PL4zHDqnAYeBIQZ3pWoI7IrNzgQwgma7yMnUu6o=,iv:1FNmHe4L4mhDeefm/UnGwgwIMHavQFQq87yMf8pgsRs=,tag:nDxZh3nm9IW7ySeMTE+IoA==,type:comment]
    #ENC[AES256_GCM,data:89LXOnBFvWWmitXtxaBOz7t7V3Orcsc6ZA==,iv:SnJZXh1AGvJ5XIUnyvTxH/cMn+SOhhTZTgJAuhKyGz4=,tag:Astu43NdBj8Djs24MNo2kA==,type:comment]
    #ENC[AES256_GCM,data:nKOtDmjAlpYUIuN5NJbvK3E8s1G9tLp13tVYN/DPJuWYrJqSfyVF+WgFNr0BlRTHLp6gVn8G3EJ4++40IV1u0o705+ydSR0H9dCYOYo=,iv:3wyHfTQ5GLfr8PZ/moCn4tGN/6hBm6uD+Un8AU/st/s=,tag:Yu1b1SnewmIocH6RppQh5Q==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:DXTR2ivuFC+Uxo5d5EJDfb9xjrJ8UjCdc/8wSSqlHn33Le4sGmtww+57sxOJsDnkZPdKLWO9FVMHhg==,iv:2qja4+7dB2peAl5jakWwUkQq+PjI0Ohf0OD3d8snhdY=,tag:uB8xXfdXX+120tSeFfuAcg==,type:str]
    #ENC[AES256_GCM,data:1STb6/XPondmZpHruxmZweRwOit1n6O6LRmEg0KClsUJMlDM/CpA/wY6Y2caCo44O8l9AAz5t5zpnjhj0RWMTzqo0VTMPh4=,iv:ixfqbFQUuz7uyDod0dDLR1M/AzSWzgVnrkxeN1TCdS0=,tag:Gew9VML8wUblNKR8o10tvA==,type:comment]
    #ENC[AES256_GCM,data:zxiNhWqud1PXJdpr8Zdvz7g15/2KtMNBRHdwDQ24lS1j8wLibpwsGelpgt5JqXOKCi1IJmn9,iv:SDy28Nyx/tpA0vEHnvx64HfYf5Ew9F1spIEYfEAZ7os=,tag:ICPzmMRDWuEogF+/DyWifQ==,type:comment]
    #ENC[AES256_GCM,data:ijmDsNUPrWgFOUDzpV+Z6HHdvkMofTa6XIq6KbyCUQ6qwkA=,iv:GQ2IAs6mwWBsfp9hs+S3s3OiZUc6jg+TdE0fOCSxAww=,tag:VwdIas0MUtcqbmai9Dc6qQ==,type:comment]
    #ENC[AES256_GCM,data:utP4AUIk9/JoNQn9cXOtj7n0m5SbRhtOWS5h8G/4CSP0vY1EIW3K,iv:C3R9bydo9+RGflmSy5O3lOkdTjHD6q7lpS6te79aq4I=,tag:ECvYZtwp24gaG7Y2WmUFBA==,type:comment]
    #ENC[AES256_GCM,data:/psqAqPwrWp93gS2SS8=,iv:bt7DLX9+WtBMSotmfjStV2FpmNHkJY0ZAwxIYfYDcb4=,tag:33sdlmuD2Z/0aXJ8/M/w/A==,type:comment]
    PODNET: ENC[AES256_GCM,data:HnYw2uhYFTxCnA9C8g==,iv:I8rOos/PAcItz4eSqpfgnKsCd6/FA/IRE58/kyC1Bo4=,tag:QGrgvWvNR7NmnnNLqh2LZA==,type:str]
    SVCNET: ENC[AES256_GCM,data:5CKf8rZiAUpILaeLlQ==,iv:tiUspjeLdV1fgiyPo9BfNnJXjLqD2KVyhXO27swlHzQ=,tag:TkKwEnslWuYi+Bh34M7kag==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:zYcw2w==,iv:Y4VljaVrXsZjbnhTcvNkjCnZ9i9wut5FIgK7bzipJNs=,tag:bLhq6CI5ZVR1CE2vIScB1Q==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19wg3490scy7jf9srcmzskv6k96nj9fx77psdqkxpt3lg66j3fcys4xndsq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJVTZteXVkY2tJbm45ZHEv
            MVROSU9PVWFubERpQWMybjBNRXBYRUttQ1NBCll2NmJmYktCcEErZjdLcVpzdElr
            VWRQRkVSREM3eHF5Z0lma2VZbnM2OFkKLS0tIHNxY0t5THBRTGhkVkpXbVBSUG5r
            WUZGSzd4blNScWdub2RFL3dQREVNUzgKU3qT+uvsS/m9kKKDgYikxBCGTdIKMObI
            I586/Mz1pW9Q4Y7+qgamBFuQAAHRxbmvcFAPu5N9J5SW8yNPyCV8fw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-22T21:13:06Z"
    mac: ENC[AES256_GCM,data:79t9flEu8WN4LZingPJ00QDeEcTc3+KRESCP768bMwxiJAHdKN0I4Cz/BL4bQhIsFTUeZKMEXnmCCeaDoFVdWqND2J3kUxGjhV2n+JGmJcV9O0djDxBIBRe+aZyx/gsyOnsnRL4RblY79QwDCmN56kG1qETtwlqcmItAU5QA8Hs=,iv:KivOY4JZ3UhMW3ZExb4z+li3Yir2yfkjEOjTc9+lVHM=,tag:6a4RRpEYUrNjCFzNr1cghw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
