apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:KVmB1gX0gyH8TVYt+2FM1ScfpTl+rXXUEXQ5E1cZvtaueQ/ZwxyNIyx4we5DPM0nxQgUxKI5HZsJTXL+t9V0tLo=,iv:c6UVpOgcXgKzIm1MLGQGqood+nrUe0/vjMGlEQV2q8c=,tag:gXd+JsQ1Sjyh+ZtFHA66wQ==,type:comment]
    #ENC[AES256_GCM,data:N0bFvyuzJ3/jXFpzMJPrQYl5WigC9AbU2RAPlQ/jHNP8lTkc4OwUd4YCm3E=,iv:6vTDwUn4PWHX/vR4m0lJ/MNsGEknounYtBsAZ1BEAmU=,tag:wQcuDJzBk7cp79qZsYX+ZA==,type:comment]
    VIP: ENC[AES256_GCM,data:EvXzScfkK6UhrQ==,iv:3NAuDuvLySjGfuitJBoQmW9IlhzZTuZdgMiF9tyBlLc=,tag:H6tXIYul8KVT8Al0wmb5zw==,type:str]
    #ENC[AES256_GCM,data:LZwcn9cKUgWgoOZnPC+LhpK8Dz6ceBjXwpfk,iv:1M/VVHB58ICl/o555PIzJjeABJaOYaYwHmdseR2zISo=,tag:w7ooldkvoLlzfpoeaADPtg==,type:comment]
    #ENC[AES256_GCM,data:x4TDE+cbxRPZTMYFiFuuCqvQum3ucHUzPiTidC+KFGAzPLn1az4ms0LMTVimhVtYR9zGBRzN/TaJOZdqAKE6Yc6acNnxihHbWeYPq86wkw/ZjC2PY5n/RnI=,iv:OaYpwTpGkiN1w8/h3i4sxgZ1cSOcok24/ukHzScQyUI=,tag:zeq5XH6NvAVGVebU3qHoXQ==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:neMg60awSeHSHw==,iv:rcFrcO3Wt3B5X0oWnH9JEZc+jBqfvl9SZ36EnQwEilU=,tag:m70QWIGTF9DtyxQ7DpOSLg==,type:str]
    #ENC[AES256_GCM,data:csJtOynUlPd0Vd/9L35vOLaFCR3QkcN93MXMw/n1ycvvuw==,iv:phGHasI4ONZosMGC84dnRA14wroqx2bsR4HcnYvuxHM=,tag:vI8Gne1YQ+q/vgqUehLOAQ==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:uYwNOD8wu7Zs,iv:HooTe4mC3rfhAlFKxBbA8h4BgoaewmoIw6y76ssgdlE=,tag:NpM53CzPaAMOytwwys3reA==,type:str]
    #ENC[AES256_GCM,data:OG4ZhD/ch/Q9vaP2dN1U4ts5iXKAtGQwqHHdmlcyqBvzca642zSaj9I4psNpPec=,iv:B/UdycxTHEQGECxPnaekSEn3M2OheCLZcZ3N8EqJRNA=,tag:lkbgpn2R7znbVydQG0BEAg==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:EcA3M90XN62zjyievBSJVrKA7BNL/Q==,iv:xtFZPpqk7oPooeT+jI1qF/0zmJVU4zOzcQvjBuAdcQw=,tag:ZnKszMmm3PPniJHOqROh9g==,type:str]
    #ENC[AES256_GCM,data:kXxtmC4cy/P53RvjbovsKnosoRwFoGKM9J5krl7z2AiMBwZjvoY2aljulaKHrgeB4pbwkPa9EzJESXlsrndbVG2+8NhmrZ5Uxm3/GzgPZbyf5Q==,iv:RWe8UFWwjxyul58ARdTBbuA9HOVi+mpRvuO+Pzykxi8=,tag:Csj3nSaMl5MffrAYOeffJA==,type:comment]
    TRAEFIK_IP: ENC[AES256_GCM,data:E+yRm3wFwMhtLQ==,iv:bIq17muyp13uWuGrV+Rm5c3I2mRY5JmNUO9Clx1qRY0=,tag:KOcU+v7rH/U/NFC47viE6Q==,type:str]
    #ENC[AES256_GCM,data:jwyyUe0ftKygtzNXf914VbB4aEzbRJ9gc2W1LameUsNm,iv:B6qbEWs6Jok/plzqymR0bbcpMzjskUvpY+aPQpyaiUs=,tag:AFQ0pPessjOT/8yVf5lFLA==,type:comment]
    BLOCKY_IP: ENC[AES256_GCM,data:QMGApfSTa5ifuQ==,iv:Pvu5SyZHS2bKNBOwV6ocAEjIovk09Pg+03/QLNoXpwo=,tag:O1RnIdvGvHk3+G7F9OtZOw==,type:str]
    #ENC[AES256_GCM,data:uw+yJDUBL8SF3Q85PrydlKPteAIFnY3eUT79D3hVa0jQ2QWDqCDvoHcLZCw37B6AnmhCAeV4aXsdClUIt9G7PQdERgAz7Z2twQRTwch3UfU=,iv:8mEm+SLU2Nh0oBu+MEjJM1ntbZyGJgritTIthkOqpS8=,tag:XytvKtw+pWfurEbhUXa8ow==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:FhuvE879P+JZ0g==,iv:3dqZP7kz/AulS0UptPQW+nDYBg2UJXyWWGAKC5R5LEs=,tag:lZwNlLZRdll7DL2WBI4J5g==,type:str]
    #ENC[AES256_GCM,data:GdI9EiAXrGBnrzSas5JDSVj3WF4gMq2DXMknYrs0Ez33AQ+vLO6XwdWvkffp7NNdbNpF7G1cRFl5741W5VtbVGEUip32maF1fIW5o9bwrg2jPaZv7fSS,iv:3o+55UIebhwAyRZmEW0uFI1mTg94d6rp2CY/w1VOUBY=,tag:a4PszWLBsHVP8hkG9+6bqA==,type:comment]
    #ENC[AES256_GCM,data:+EZ6ZfYK07K/rip2cB65PIxElZq+ae30OkFKhjSqqeCdgq/KqXoCj5r6x0ar330pXLqBItwNyN20doaIDlDLn0aH8Si0JSRak6S2ZllbcuxlZWOuCQhknROdJh5UI4A7zC7uhkmT0D4BjJM9/QIXhHm4TCdyCL2ppdmTGQ==,iv:c5AOvfIFCeNpnIoPlb5ySkIo5UQmMT81fpn1xaly7e8=,tag:/MB+d2+MEspFUzi6B5OM6Q==,type:comment]
    #ENC[AES256_GCM,data:DPre0OJnEKXKX5i9ugBEsKm4d336J9Ka8S5tCuP82OqiNGFhVruPnqZCA/euaHKzxQZOxEsvIflmExLLjhHA3j+YNpcWh5HIW4XDKx1zwpU=,iv:tQFUh2tvcg+aSLguduGMkEfD9+xkVrMhK9dvGpirJLQ=,tag:zjXuVnT/XyEbh2PnKkX3CA==,type:comment]
    #ENC[AES256_GCM,data:ElBLyec5m9PJPxbXwlKZqdIqkMHRh6zuHCk1fr9+oS5nbsyFfHzU90AXWzw5PsPM6qVD94aQ,iv:ApPeZJJmPbpT3psEF4YYqYyq4fm1B0945jKyYkfUuUc=,tag:6rODdxReFKolIqTU0LDbow==,type:comment]
    DOMAIN_0: ENC[AES256_GCM,data:/vG2wudlocdoHFdX8V5elKI=,iv:Y6k5FaBSDD8jh9mL2NiSDXpV2HkpZkwPUsatA2zha58=,tag:Z6HuABLHTl7q5Pc/4wnfcg==,type:str]
    DOMAIN_0_EMAIL: ENC[AES256_GCM,data:d8/vnwSEYeXzQBwMBsVZhDpwdREzsg==,iv:ne8r9C/34DPT7nsbHrvHN25KkPmxSXxE8KBUvoTSGt8=,tag:bcXHZM1d5DxhBKnfJ+RL4Q==,type:str]
    DOMAIN_0_CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:qMPftU79KGlALUMQ8h6um/bh/5bTdM7GgmdeWkGUjhpCjfiY5N75dw==,iv:xuEAwuqW9zObrfZ8C0mmZ6zA5nJ9BzQlliFCLMbj8/I=,tag:Wr/5B/8EfvTfflVXhLzOcA==,type:str]
    #ENC[AES256_GCM,data:fNzSWzSbifNBSqQw6ahY79Q+CnYpJK5IDBmPpId/d9P9VE9vpRsd/+DkB9ANdYV2v2SauwBYOTE=,iv:QncyUik7va1rHM9s+fW6HLHjaU7m2CgL+a1kd9y9kN4=,tag:MJNcP7LBeONu/VasS+v56w==,type:comment]
    #ENC[AES256_GCM,data:RmJSWsXKuhOWzBV5WVNT6Kjo2W1aY2fa+w==,iv:71nRN0PXTqu7+qQRbnArcbd/zUvfZd65Er53qED/LfA=,tag:hM1uklGhIB102Wx4Ze7Cmg==,type:comment]
    #ENC[AES256_GCM,data:OKBGlBfeW4lsFqzIfWCDPds4T3PvzpFtcLCk8WPVUWu+mDqHWTYAXoHe8/MRJOzeBdi0/WmJhl4odmTm5yRLaQKa1nNDnYBovHt8SC4=,iv:a3CM0SJOIy6AI+U3ZGnDucSCq2czhgB6LzUQWGy5ngY=,tag:zkvjtA1wXzw+bQmCLuAy3A==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:VdKMWXwfy/jP8jpsqqI/A5rf9RdBxSfHiKnNxEKwuEddIFup0X440Aw4S07ZT05k1S1B6JdeeWURQQ==,iv:2poG0mmemz4MqhRe/bIOcdD1x+Ru1eCNvlT6Uk4BEeI=,tag:tpfq4SXGbnCAkH1XFUnfbA==,type:str]
    #ENC[AES256_GCM,data:xY8zqZM5hlHehzxeJY7+2RBKabZI3lWA/1IGpvoiQqAbhoSGiZOXWveJ0zilLyfsOM/iXBi1nt4iPB6VgGP6qbKV2Nou5ms=,iv:1QFHPLo7vyLqUoxbN9T9ZyPWhwY8VncuPaa9MBweNAA=,tag:b4jlSE8tqEzwk+fdAKyW6w==,type:comment]
    #ENC[AES256_GCM,data:Xe9/xQIlWUhjMfjejoVDe9Ud7wO8/EBW9sWKpPyEZUL3AxYTYcuvlHY5u3IHpNKT0Hrepc3I,iv:04irI9+zhEBr/k6HVUEPpCb7Bs04QipxgD4ZeagHQDM=,tag:AOp49UqJZeCe3sohIZEsyw==,type:comment]
    #ENC[AES256_GCM,data:wuNgyPaEpFEnmyJC98WYSPejTgNW7sCOc1BXFl45lIrs1I8=,iv:3YYk6hpJWSiQkqMMb7N17IRs3bzvPFnFrnvvv05ikRU=,tag:w/phTksJu4t8l63vIqA31g==,type:comment]
    #ENC[AES256_GCM,data:YU/MxrTRbIuadIadcAU1pTEFfZio4R7Q4NirW3Zr+Z5mxq40J+k0,iv:02VY0dNMSjVCtZ9dc69nAfcSQt/VQ8WxCIdm+7hWWrM=,tag:xonyMsBCqe5Mp6W6wtcW0w==,type:comment]
    #ENC[AES256_GCM,data:ZNZT2M7BgcAtDIokYWg=,iv:W11wpYKUF/zfrWGzcY4cuwQYLTkAyuj5mfC0nkPqhxI=,tag:2o7YJU3QRCX/UCFyPmJLkA==,type:comment]
    PODNET: ENC[AES256_GCM,data:7Btnpf3Ky/a7ZhA4FQ==,iv:xQx3o2pVEfjiGg53hQs57pw8TFItBdRKauWVjFK8Rrs=,tag:DNMePDmbViRSJWA25oIVRg==,type:str]
    SVCNET: ENC[AES256_GCM,data:KnLdCetkGtG/COzpaw==,iv:wSLbIDSrK4CHgqo+52eaRL9ncZha7k6BswaNf7DhCds=,tag:tYoEOQCFYKq0h7EFdhAS9g==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:q6O8wA==,iv:+MQYFL3MRyCnGayhqqqZzOhfrAzfIzuzXQyBD/hJmEg=,tag:+BLNVDYI2YOfmjYQ0oRoDw==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19wg3490scy7jf9srcmzskv6k96nj9fx77psdqkxpt3lg66j3fcys4xndsq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtRDQ0TDN3eXovUUVvbGw4
            R09KdWRqOFFUUnVtRGtsanBwN1VXeWcvU3lrCi8zTU9aSERLMzd0b3JIQUhsMHdT
            eEQwQ1BrSzhtTCs4WGlUQ09rSVMyMm8KLS0tIEF5bVVYbEwwOTV5akFLSkNYNWZi
            MXppNjNtZmw0SjRuMFJHcUtSR3hiLzQKFOFYcdAU8vxut3OaTGC6pdxCscOVoVK/
            Ev8zwlsImrOC0XW9ABbuzlt+gC/HndRtIQ2LGP8RGuEipRJ2rllQIQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-22T22:13:16Z"
    mac: ENC[AES256_GCM,data:PqHmeXG7GettVpK/w6B2/Pl+EO3mMXM95qYGe/wQjKCfT8wR5P9G73A8+tDYxI2M3m85r6aUgBUTBk1WsTBxgg8j5u1FlcbjUELx+tXbxZZ/ZRC2Oeq9KZJHlpiCPvx38Bc6CZ/DkCahspFwYeG6N6WUPCrA1QiHwGvO1/Zzgdc=,iv:4VdMe8xi1KuWTvzSifaUmEs1fEHk0342DU3qhxCmcnU=,tag:FOdX4f5wl7ICpnm4l6e91g==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
