apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:YlIsc6vtvmKiv04DXhm5Ocl8tseJkDvQ3XzDRU++CW6WhfV6QljsXxDBORo6lyAhgpRb/GlUzpyJybKZ6DgSFUY=,iv:+UDJ/u6LCb1jIt2lljGpe6w9fKmnpx1TjcCgMEVwb0E=,tag:EH5T0CU3r+XBGxRa4a1pfQ==,type:comment]
    #ENC[AES256_GCM,data:eH5jbIFYuVzEu7iaxlzotrcSbaLeW52glhqTEc6kU9HdSlp7E+AnfIw5BdA=,iv:IkANZTRQpuv/YWhxVDG/FMS6XVyItYWoW85qqYnjlYA=,tag:umuw1Jc1ausotIWQ6rkHFQ==,type:comment]
    VIP: ENC[AES256_GCM,data:q8BHi2/FJO411A==,iv:cVKiCaeToD2QJbkT0Et9cbMQhrFa/bA7Nt3x8B1g110=,tag:CUmBYU2UehxWM+CWtNoYGw==,type:str]
    #ENC[AES256_GCM,data:qVBqxf357jgoBQHiakH3OeJJ0HnKUVN9LIff,iv:PGGfe27cIhcxMZ02NoY7Xim9M79/DT1pU0jstn2CTCw=,tag:l7xkNEEjmifwEYMwa9VIqQ==,type:comment]
    #ENC[AES256_GCM,data:A+pa7hKByMy3dxulrKp2lTQR02AEwBuWu9YGM/wRZUjn7CGG3DJZLNjBC2CGXYYWpPOGagT3hcHp8PVnAG+sh2n9Wk7mBhqNZx7BdoYL061rcsdu2B6NL+s=,iv:xAyNtkiZLi6vglMtSskKfpEyQjLyZ9G46XK3Gt/bBuY=,tag:leqgBnqTaa+EaQQUyw0jKw==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:Hfuh/IbLgzFdKw==,iv:p0imHiBQNOe0haZP4wowmsXM8l92/7aYWuwLeTaqYbE=,tag:yWCzYp+YboRb8JOTj1guOA==,type:str]
    #ENC[AES256_GCM,data:dtC7zeVFQRWmTEcW/VXJmfs6Dz0I8EBHrKKDSq0qVXmQvg==,iv:VhYhlfUGf20NCh4Uw+MCw2Mt/1W6XxSKlMd5Xt0eLJo=,tag:rgrbHiSBVjgCVhqgcsQpBg==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:mple9laNp1dV,iv:dr8/kBKJOyQqJ0jYCf0ynSkeFvD9gYkpJ9B35TMJ44U=,tag:Cuv/EJVKJNaV8ku3sszNAQ==,type:str]
    #ENC[AES256_GCM,data:8yLzfGfhmPkMKw1wMl2JitXEzcrjdolb5bRt3XL1K2DF1K8gg14N9G81K3/LiwM=,iv:/RQJ45yeY/ZmKlSL2D2vXPaPtt7eW7eRFsrp6p6B/G4=,tag:Ge9+vFQ26+GXH7g0AUK/Gw==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:DgzKtwy+8jlbM70tGd3fJQRL/ctccQ==,iv:UB7tkl30st3TChAib79JsyYEmlCFkmdR4iw4RZoQ2X0=,tag:gmJreG3hczqGbnjh3Ngx4A==,type:str]
    #ENC[AES256_GCM,data:U/N3kpkED2gDGl9CYdJR5TsJIrjSFVV560XoojY4NjkXgZhkWy1Nx6IvEvE0pK1CNWtEUjALD8e2RN/yxKwnReX282scZz1ArZJ2cYDKmLvdJA==,iv:U6xy1tSxyVhTvOb+U+vgHY2vYBNBRMZ6ibApKTikffY=,tag:PviU/Igs3h0ZkE1me7sGdw==,type:comment]
    TRAEFIK_IP: ENC[AES256_GCM,data:dZ7LDSqs6O0mjw==,iv:u/wgtXBuiDQugkgyn9LqzYtkO9AjUbHLf3yvzmOnTK0=,tag:rmRoQxG70o4nSH5c1MWtjg==,type:str]
    #ENC[AES256_GCM,data:YneVVQenrMmbcpGtxGV3bh8IwYBhBgsFh85MflpS7I+s,iv:QRDNccbIJY9nY61COUtcCwVBWxHWZ/3sI6D+ab5j6qg=,tag:PAiQOlu5wkIkgWBT7tXIdQ==,type:comment]
    BLOCKY_IP: ENC[AES256_GCM,data:96rzFxDs575xyw==,iv:48AKReK2u3iQifALQillFMdMA6u3hcccnS2JGgMUTt0=,tag:8MyMgBbaS0ETdiVyq5q3dg==,type:str]
    #ENC[AES256_GCM,data:zVwT24BRuC4vzxv+8aqwG+fiSh/DhOovHsUrVVvMHjzCXmZ2RetUbm4kD3mIRXCSM+vdLpxlg4kmEoLTub5JUKI9EluevmNnQBd8+CQxgjI=,iv:4f7uXWxNHBu1B9ipCTAsW9Ht/tH5jHvju2AVixBMFts=,tag:g1A942cVsR0PgWHRV0g0uw==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:WyAz/MhGF1Srfw==,iv:KN+OJP86KJ9BjXYI4qJZrp6ay/EMCKgCk68FKhsQzhc=,tag:YlhrUiJH1/3EOGp4dqkvKw==,type:str]
    #ENC[AES256_GCM,data:FBQBNejxWxnYaLTQURjOvi9c2KSdGVxSxOqGF/EWBxR7XbXupOs13in/eoZlWIeq7/C+gnhisWsan44bU78o87BYB/ENjD6EGJnQKn2Jwd33bQJTyswy,iv:6oSuAMzCK8ctuCLIYK+3ioaxVtjHdM7kQ4JGgWPMpx4=,tag:lyAwW3ZG23BD4UpUZZr2Wg==,type:comment]
    #ENC[AES256_GCM,data:+C/IFEh15X5TcoQdO7uP84PvfFMtUX0MgTlVR3l964rVLTI3ABPeg07aAKB6iMJiW66abPQyaqkEGFHhD3rg/VvRHGE5uE0pwsIsSEe3YzYFXN/PSo9yfxl56VB8EOWvqJM/pFyPp3NrBMnH0f6+QVGzifg/J3OH+koxIw==,iv:T6JN02BeX9S34k2MfLD1sh5eFk/g9uvd1qEB9i0nmrQ=,tag:r5ZwQUgKXRPMJKLEyRnZeA==,type:comment]
    #ENC[AES256_GCM,data:6rMDnrd6oblVr9a32U91PkiOrtAme3jLBEwklrMmFvL1IhQOT9yX/+RYniz2BYotBk4GUXGkoWWT6kDiEipW+ebrvngurvR/u+cfuCqBiDg=,iv:STEAdeofjiRoNdSSce2pRcVr/0CzViIqyDlwJQLo/0k=,tag:DAoqfhmYIp91IkBb6MOSmw==,type:comment]
    #ENC[AES256_GCM,data:HJfTY4HcyzOak1KFypu/Eki8yLhmHNmec0GNG6QC7KapfbyiCu3UFJSiJ9lxjFE4rJ+hPPM4,iv:BFdFLYqZfrarswRtgBI0XWZMeBeAYrh63L+0mUmOP0k=,tag:tu0bPYUrExMVXtYfY52AfA==,type:comment]
    DOMAIN_0: ENC[AES256_GCM,data:XTGjK3/+H0eG8KRiB7sAbrc=,iv:icBVmOH8F0QdvqV2bpD092S1KL859PjXdxLp9fOwjic=,tag:jQGoCzBhOUdgETBD9i+KvQ==,type:str]
    DOMAIN_0_EMAIL: ENC[AES256_GCM,data:Zrr++eRJfMH/8O31bLGhHapwqS8S1g==,iv:cXVexkiAZw4RWSeHzzvWI/IvprCSb/1rHxrtr5/O49A=,tag:Kp7f1bPKSCWeKsWXCe33fg==,type:str]
    DOMAIN_0_CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:1c4Ix+aadjcJKxeNG4xlGub8dt0QdmlQucMTxhtnkzR2ViLTbmbF4Q==,iv:lDXpIjT/IIL+A2UVLAoz7CDSYh36cDoUW2ARrwBUBQ4=,tag:aS0AO4/UjlfNyC13jG0M5Q==,type:str]
    #ENC[AES256_GCM,data:XqImW9oirBvWMMth3k6QWVyQ59Xo7XGiaPOoXoTBMwUw+1kkRMD1ekzPQjMYeyrHA7qjUPGYE20=,iv:XezitpiLfi5+nsaNeTc15sM1tsDK1LgDzAOQomdAZKc=,tag:HEywFxNi4oZfbRJHJ/OUsA==,type:comment]
    #ENC[AES256_GCM,data:/HA52bOglrkC+2noW3mbykqR8/tyMeWtzQ==,iv:+N9FKM0oeeIERxufzGI4A0FYbTi1FtqthBz4wZ8F8sw=,tag:rY39NJ2abQRrR8+vVpeFHQ==,type:comment]
    #ENC[AES256_GCM,data:B+PVhouvmf9rjoFLvyXU6mm8CpDOXjVmwo5m3qKcjkqZRUvF+0hKikSiKigM9y6zTH5rBR3gZxhaNAgJVszCzfQZQDlXLqEWu8m9zeg=,iv:vbX33+IOfLxlcmavr4rSaSMrngStzthML5xeEEQaSlM=,tag:kkNJjdt2vQlB388V123IuQ==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:TOnR8UnPZchKA2uNbQCK8xDCcqCSKpgE6HRyYhJrQ9s1w3pepewzqP2T9ifX4VCjeNBAZTY8c64wcg==,iv:RLb/bNNS2z9mCRUltNfhO+BRXUuAo1lZJFnngp08SRM=,tag:BbRGMFi+x2DYI89r4mtqCQ==,type:str]
    #ENC[AES256_GCM,data:F+VQUfsyvurIq1dUvXOCYUbnLfhs4epQNsYa8XlDmCX6vC/oQ42xb6IBlx5+11LGHUgqgTL4mtVQzzuArI4rivkn1Ek83a8=,iv:YjSkbt+mwXFEcfjPKwFXHe/eHiaCfRQsQXatpIZKxZw=,tag:9b5A3Xk3gBwy2a4wwAN/fw==,type:comment]
    #ENC[AES256_GCM,data:hy8Sym1OPa6QcjsApRrGE85a95lJ3LmmXCd+xrmlt54IHERaefbuJzkKup6JJ3kZKf4Qx2X5,iv:+29UZH527wRF59HVOTlmKkBjnrDbgB9lz+eaUiH8yhc=,tag:jMIYyWdaLuaTT4Z5QtsAkw==,type:comment]
    #ENC[AES256_GCM,data:7TUirFKcF6DKHHBKoDHintNI207mN6nXmbYYiQUTiXWRw9E=,iv:P8eQFgXXq88LnvuBJk9CG/+R4rMSGwYayktDLsOJnCA=,tag:/Q65PKGvLnX7Qli8tzmwUw==,type:comment]
    #ENC[AES256_GCM,data:/fHOpZSEjI1dVVAQCl8wH8i6Ia4vAeMzmzFadrMfp1hqQIasS98Z,iv:Yl14z6xI4dNP8bZGth3qpVDMQ07qb/Q4zt4sV2EUWgs=,tag:6T1onM+EhZOkSefPMSpDvg==,type:comment]
    #ENC[AES256_GCM,data:I4+olXI5Q1Isd1TncYQ=,iv:mN+lkZ/okupSUaejK4ntVvzxKVV9KA7X4jWxvkOhbgI=,tag:y4ZJlKVSuxrfof13paBTgQ==,type:comment]
    PODNET: ENC[AES256_GCM,data:cRxVBCKG775ZVkbtVg==,iv:YKeyBxMc0wAkW832UPyFUebqll5duR02jjrufzt5in4=,tag:JEbonEZLfqgA94zuIE/9bg==,type:str]
    SVCNET: ENC[AES256_GCM,data:3AE5OoyxPGXC45Dg4w==,iv:WrbcJI+qG5gEuO1a8jWyo2VDoGVxsSiESb6seR1xmEw=,tag:BBv1dS9vbAe3Lg/OMfPDGg==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:RGQkcg==,iv:zZz5SVvMzhC4ZntS1k7zPA7sl0MzCrnJDJ0Uvh0xUkQ=,tag:484rpFtbl0ejncCHy9Ol2A==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19wg3490scy7jf9srcmzskv6k96nj9fx77psdqkxpt3lg66j3fcys4xndsq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrM3g3aTZxdnhTUWF1OHJn
            VzlmWldPZE1HWUtNb0xQMlRwRytla0ozMFdNCjlPckZ4TGJNQ1h4ZGJERUZVRGh1
            UXowTFF4SDhLTXFZUGtnSjlJeHdzZlkKLS0tIFEvVE9OL2QyYWhnVGhQaTdITXVy
            UmFnUEltaSt3NVl4a0ZrVjhoSWtJNFUK828VBX1j8Zl/VullM9lUgzySRWmtdQ+1
            14ytNtZMbYld+PySMu4KIzq990v4HOL6LpTlxFWiR7b9eyb5PmSkTg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-29T08:33:59Z"
    mac: ENC[AES256_GCM,data:WRzt/PZmvzix80EQpzkJ71PVdreZk7ruWFVDzSEUxJwUc5m7KHJHfQOhjHg1cQFjiGLcRE0aetnlK7vAmcMc5OSQY2m/4w+nlkm1w8pb+7Q7u+fGW4EXkP1z+Rbc7IvFQSBHPVy315Z93o9hkJhyoc97rb/E12ldfIOfsXS1Fz8=,iv:PQAbmyqn5D6x9y39FRXDxNc8cC4PJdv4FZs4V6XjG18=,tag:wMddK8Tkkw/IgwCdohd1Lw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
