apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:Qynf5CT0ck/PbOwomKEdKtkOawWaqpnxwflb+jCjIS13qusnY59AqRqH9v7+YPDpZWDGhfvWUMHitvrnK3HImhdQ8IIKLDrctSD9vVWloI0TAW7s9SViiqYoRa1QzOlS8AKB2/WUpspq9xoX6/KAHg/fmRrE+67BtjG6rbe1RLpvjPgYffomYddgYRr/6antG6OnSbQkaOFEp7RHjROla8I7f1+4AQ7WldzEGqCUULqG3jjzH5vW8xxr/re23AGflJDpeU3Pk3RpguKUWvCb6/tJbpCDoeANM+UapKIj4Vmg5fWYuX5LBBizNRMJX3SWLAnlHkREc8TsuvNJ7zCZaASNpI/1Byjy5ntxFkfiH3bB9n5F7y9wGj4eIq5MKrH5,iv:fpYbJoeFYYiFxzhqu1tLz/BflqJg5F7L4slymSBFoMY=,tag:r/Lwq8lsPvfG32Abp6XBPA==,type:str]
    identity.pub: ENC[AES256_GCM,data:uYz9Oz/n8BFMGwTduWyVhTMKlAmq1lwj0TTNulWSp8ZZrmh8kw6wxHDRvCz+6cKsXyjjQJUXUPOkEwmt8XtDJu88JdttqkpXna4BuK8SrpTcyGciMXOOKBA9qF+6+4eaUo3pm5n29piEcT1khc9TXqcf40bNqS4JnQ8yQYK90jtJRh+dtM7RMwf4ZVnZoNts6r6zCHS/HXGvAkoydR2PwbKTflBavDMSO3XhoRgfQtj61JGS/075Xy4XRIRNf6+OEs1DaQG4Q+pbKc5lHw==,iv:FDbz8yKFFqW9NdLDXRr/6nhD926+FobN9elhuJak394=,tag:VLD84ioHfgAMNl8O4S19gA==,type:str]
    known_hosts: ENC[AES256_GCM,data:oz4HZfgdkjQdRjJfAlY+R+CFIrta2nzGbeL3eOU9IEKcsQX1wMQLZV6fnXi4yEczkFX3stMmsKNs6FePj91oRKYfwpGDiZOruduN2A9Vi/hYcBVQfpRq1oB/WqclZsv5NdBTSMEF4JyNcAC7iH70ZiOwq8EgznDOLLfiPB2+qxlLNvdCmKy4n7ohbKOUSTE2Eg+VnK5X6Om7oNw87BWa/rpTdUnN00tahJtB,iv:WJvu0dAHt7JY59JERwqnXJakXRy65LVoPE7tPVByrQk=,tag:CFJXXThE7atN1hUDVGVa7w==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19wg3490scy7jf9srcmzskv6k96nj9fx77psdqkxpt3lg66j3fcys4xndsq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEOTBwL1RTVFZYQ29pTjBP
            Zi9SWDFqZUpLcjBIanlsTVV5RHZ3WUdsOUZnCk5IaXI5TUZLOWJ2ejdIUzMwakIw
            MU9oOE4wOWV0ZllpY0h4blVGbTlwZVEKLS0tIFZHT3RzTjVielRFZk9qb28vYUlu
            VFM3bWZRa0dLdUlZYWUvSnFqYjlxREkKBEDNB33E7BuGb/v7tT5cd47nkPp0Szm8
            VF1daroyfxurtkpRru+NPC1eRzoIhAuXZlKerAywn7ZBMXZDYQYG3g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-22T17:11:46Z"
    mac: ENC[AES256_GCM,data:V+J3ySP7cqRQc2ShdQKNp7KphQTi7nHL0o0k9YFeom5KVKEsCTerNYBry0EeoF8Bo9qZeO7/m34uu1K4xbW2XshuYPhWyvLwvRcO03x694Su9+KN9npRsHAMFEI9GH2ecq7tWDHzc/5by3uLy4hu7MA92En95VGmhKDfkUZv2Bc=,iv:bu1+rnypMupkm0ZpqDcfB5px8gyGMIG8nO89yYSLU+o=,tag:7Gj4b5t+ayRVPWt9a3iiJA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
