apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:FMTyn7rkNl+NtJp3f5iX0LyLcYxH9Q7ZKOaxJpazChihgx6d+dM9XgEw5j6OJOBxoiVlno61lh4k/8RRdAF5cpxycDaKY4Aor/m5f5/CmEObO4c1fdtWjhRBL0Hko2BuTD4GaIGIlqGCjL8MSRalnpcNLIfxGS/b/nGA7eeyxMHQ5i1PRGV15PeewTOBLV5sIYQMykgLM5z+SHGjw86lS+7Hd8ZqWKCIdq/KOUmWWKDmndR7Lx+KLTQiBrSo8ZsGRqIK7XlqsvQWhFa/msusGVHf9xtRbe+q4aefDNHt+hgEAfa2KSEqVRzwM0t1B6FKaQyI0sw56VuF8do1DYCcp80il1YriJtFk/72s3A4i8h6hWK0VvUBIQifiRV7WsTj,iv:zZG1IZ23OJqhz8he/ZUSVJwfZp0K8F7I3ThqJiSGVB4=,tag:KSN/tpI/zNUCcbAEhQ5ILA==,type:str]
    identity.pub: ENC[AES256_GCM,data:EXt1nRgdaJt+KG332N+1K6wyaLKE3QbiI8K8CWRzayrWS3avXVyRrwAYbMv2BBhbWxt691RoV2UMSnteDlC+wKURunbxnOC2teTXnRnx6zkfEcU3YIL8Q1WQsz6L+p9jMbKUF4I1ltRXj7/KhvbZ+mbeXfeiaI0LYZmrBWBljl7VUtQMvv2dYoU5mRgYqumhxjrDXDDgjrCg+Kb3Yz72x++jsNiiUJkgGR69WYcREkHz5AI7AHxDemCZJmp5KlhY3zD/EMJOIKPWGmvsMQ==,iv:4W/fFldLVSwIAQ+DMn4uYn8CVFVHotn26ff6BR8Eg9g=,tag:tw+aZU0UPSRx8uZPtoazQQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:AG8k5pcjvCuVbNY9OfpB+2dYRBO/0g9LvWlQtDD4WNAlSNJFksoBidAOi3D6GVYBnKiqzvm6+JgF/OsTMt3ChR5H4FkYW6sJrDOhOmPDXFZLhc595B9FCOHlAZAjy8A62PIVH5ZxNO1ruCrNUMBgRg/Smoses/tr8C44kRTowCe+EFvzV0GgKJft2Kw6GoEpdRykHyQOwuJeDS0f7A1ngIAG2JDvRYqD8bKM,iv:8cga1jFla0UJaWRrxu3Uiko+rbLDW3fEkT1OookNNfk=,tag:BAm1K/yOM1tLW8RDfx7kVA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19wg3490scy7jf9srcmzskv6k96nj9fx77psdqkxpt3lg66j3fcys4xndsq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwWHJnUzFtY0ZYOVlZQWg1
            cHAzbDRiK2ZDQXZJOUMwTTQ2SDZxV2pIUFhJCndCVU1lRDh0MHkxbnlVZXQ4TDFo
            U3RWWFlVaS9neHk4VHRRcVF6WDRDTTgKLS0tIDVBS3BXZUViczJzbldLS3I3RmNV
            L2xXOUVhRHRzMVZqcERWMEN0UGllODAKmM5PVm+5/zx9GfmddzaCstBFmYewDoo1
            ck9UE1M2CsnFE/fKaVhQaXmoUcIC1SYJWzy1NBNxLT1zv+1MIA9ZsA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-22T17:14:42Z"
    mac: ENC[AES256_GCM,data:jFOFMIeTXBCnT+gpnOCyV1x/OrjACC+3RAZyddtA0iSOFyPKWBtp/fzCcEfzJGrRycFFVUOua6pKzIAF4P/VYGrvSxLHeufuBwYG155wguP35Kpp9S3a2campUL7q3UZrsTfGhE70tKo2cvhAbk9l1WlnlxsfwS42Q3HDCKkJcY=,iv:y9ZO4FcEtwt74HgnojjnHEIcJltRAQWajKlmeP/Fk2U=,tag:qjj6dduhlggnHJdYPV+3KQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
