apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:YBwzF/EC+boXaJQKs3y5t/aNyTbvsNZJ2Clv79kPYgjjYJ5pmBaVQgxoA5+2i22iHIqDPiwH31OCplP0WHI8rKpjVpSdxb8t/NURHPbYCNPdbgLwgJzBQTh8F3Fq2YFQdHNaIL7uXCCIqzvzwLkU0aRXG+bX3uSFZKjRev58ahGQKtu3iMa8k3VDKmmqb+czTFeAH9Vk49+WZhb+dTiFMrSeH94fzZYmioPGyvtQ3HqmLx0pLMVQ2GZ7GeGJJeFn+JMFLHH5JhrMnZM7keWvcazHxztG/nNywS2gxfyC/Tys3rBX8vlBAaSWhY2Jl23eHQTlLZODWupSUIpMIeUZMXWaAp7PfnNgsN4z3XucUogyMTVR+TiAk/EvKwNtslo/,iv:9M2KHTre1rmxq8YzUxp3dEhUC6TEKdokPzIYXOzuf+U=,tag:OoNYgX7OUpeDVX6jMALBdA==,type:str]
    identity.pub: ENC[AES256_GCM,data:07BTxGDxD0JlFrQxQvcjp3krVxNXhS4uTm5aTV9ftpEjNsYJPQBKhp57yTEsjXyR9lcQHG+5eXp81EZx1C5ombqEldv6qx+a0xLvbcvLT25r0eA2Lrm1ZT7BhTYWZjNFlEq9TjCowRFeP0BNtMir1Pkru9Cj9mQ44jBIu1GJZ8ZzzCF5wQWEM4WNEnLlFfpFxV+G+Da6U5H0OJxqd0hyVOuiAWP9GhVfki5RldwU885LnLaOHHr6yYZJWJWldwR3dAx2rcEAgOy+niAsCA==,iv:NIqung0a+3k5o/QaAdoGPmrKMKcsewemMMjUDo7qNBs=,tag:T0VvYcAJNiHa7ZxQNseQFA==,type:str]
    known_hosts: ENC[AES256_GCM,data:xgp0bloRMxtUHBtjTtcyyZwi8rAyL3ZQwjsvOAqPbJeAGg0/WVczx765azu4R177m34zRVZR6uZmVny7pvOGYXNXJMPpxhIejQSCOu0w28ziiCv2gBL7EAUkj4y7covd73JDZNO9+uhxktsQUgvjq/eQJYfd8Jx8hegEXVCvBLOCoahb86e+DuwqzoBPMo6hnzreyiJ9fw4+DioDAOHpJ8Q4CLnNbh3t7/87,iv:17O8OdzOf2q9I/FoOcOGKPcutwRn+YzYALrZNUhExf4=,tag:mi1Wmp0vnZqG2NsAgw/wNA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19wg3490scy7jf9srcmzskv6k96nj9fx77psdqkxpt3lg66j3fcys4xndsq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBodjMzdkFiUFEwNXB6NnJB
            VUFSdlRCR2N2U25GNFZEeUZTem1ZendMUjNvCmFKbFlBK1FMZUdUNXVmZUFFVzE3
            dC9FRURaLzllMHJodDZoZFA1V1NGVFUKLS0tIFNvdXYwaGZBYVhTL2hZQ2xMa2ZT
            MEhZOG1rODRHS3NBNE9GQ3hQRW9PWVkKkmjugDe2yVmLzy1IQaA+SbZ/apwPROzb
            APSl5A9LujMn2dVBDBssrbJ8udCFYYZ/Av7uzx8C2dCO9AcSUzXubg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-22T22:40:21Z"
    mac: ENC[AES256_GCM,data:NHnkTbpE5xSRomv1AV7C5uSSGYhwHqoy0Q7gf1ANU8PLALEynnedDzYHi8na2IJTgAWjKg3oLvCjENO2RtLmkefkyGfjhrSRb5B5AEt8Jf78bEnyFXX2vpVOs6/6ubiMSSJxVLtdgH5nLSy5pk95xClVO2GEOqhjuIxrdBVAo9Y=,iv:F9OWhWObD9fnHc81SDCvKZKeoyyH3bBWuZ8UZun2Hnk=,tag:LcplbH5LkjyYxAlVUMzn7A==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
