apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:E20PI4w3Iz0v1SBhVuOkLzi9iCN9bjLq4J6YHhhHM2I92ACrYkopJlGV/EL6HeSSNfm7vWNESt9zgIXyp2w0BLQD64NSAd8Pd2tdMOAyNLi2crzpTd/SfrbR0R3uFN12FpTgAtwt6+OZW5+N1xa+38I8bfJB6LdwuiK9IoAx+iyyJMkaFjHhdSES8xNmew8kdJHLmY66cMxoDf2u0i9ffqoCHXA/jqvDtlPA4Dbq+tvBO380m4jeXrh+5WqT2MHk08edD9zz1UP7wFB2jVGrdmLGHszrY6Ymcm97cXkYD4862MSTUYVbfavfPX6Ds8j/zwlw1q9n3ow0oRYGgeLoLI9mmET3641MqmATuSBVBzQ8VgHzSgebj6+9TcYKDdyq,iv:8ri+RjBFAv9QOXp9pXGyyQWKUXuhDbR/df65XK5Lxfo=,tag:cnBJOreRFqtM9PwpXVC0wg==,type:str]
    identity.pub: ENC[AES256_GCM,data:q49yxF7bMSc47Gx/zUJd0zSKSNjo5RzaJrfrJX+UV+Lb4cxeC4kInxyUT/+pgl1tol8yqHfwYlvzAtGpeU59rT8a7tV6RDHL4WgItAFWei0xLPrTzwLRDIHkOb4T7dYJFKP1etitMpHiQlTiFTkfGdHfEfLpVITIAkZ3U68687phAbk7MHIl/48id0dG4WmTMsdnmFVgNNZN9V+pmMIPfCaNb26JcG9G0GJQQ5WJ4TkzCWVzZ5qmqx7yk0+6GAPlaTdcQyHIHLT+DkhUdA==,iv:PyphNyAzBljJ4j2LIqfSkGxKIXwR1Fll07CxdaJXGs8=,tag:4xsQ3EOR9TCN2jAj4/Uv8Q==,type:str]
    known_hosts: ENC[AES256_GCM,data:oGRxlR8u4S/j087Z9V4OV5up5I0lif0qAsy1ODicU1Rth9YGv8nL2tjsUgaXzRJvmY6Mfk1lCbdwu/uBEtECV9D3fcsvY7yjPjbAKlxWtkJ26Cd1jaA7Sg3BdIuL8MUB8i+pcIgYch3v3NCWu4OUTPukni1pjAcqWw72PvkWHmpTmnvRo7tCIxz6fyEsbwHXzeZPbYsrDTO7N3snO3s3vZboCEil145uL4zA,iv:G2pJx+2bIM5OMjcCKXQlwzFTCV7HrAaqP1mMjqvPPtk=,tag:AW101sMtkRQWqyKENq2WYQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19wg3490scy7jf9srcmzskv6k96nj9fx77psdqkxpt3lg66j3fcys4xndsq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkQTN1RDh1bWZPdGJVdWpX
            YmRDVEVUcjNKTUpVVnpLbTU1T2x0R05udWdzCjBMcDF4ajZiOXB2b0FJVTRXdmE3
            RmFOL3pSYmR0MXk3cWJPZTdUbHNMVVUKLS0tIFVOaUh6dUhMRFlSZkcvYWx1R2Jz
            WVl1MmJpK05Wci9vcjRHSFVRMkdqQ2MKCy5YhiURyRImSPVfT0Bxbuht0mdYxRZ0
            RL3/yCanzpQYinK3XpLY/ANsTNf9UXSjMr3knk+IWeTra42anSTngw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-22T18:45:25Z"
    mac: ENC[AES256_GCM,data:bBjZAgcb7iAyM3+QkSQGJupQObFfg3ptGk+25XHbMcoGACUlIS15KFb8i/ZCLm9juf5gEfAqXwrKfw1JbZ4Ni3mF80TZkngE9dsdFvwvS0tHuX7LynC7SrZXFhn1WBa9XCdrSj+pY85uYbFSnovIpMOhZul8gNsgjO95pW3U7JM=,iv:kZkg8lBvvpKL7e86cSXqY7NPvrop5H0c615s6dXnFek=,tag:9Tq0aXhbkonWzjOVn8zmgw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
