apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:1Bd0UNJQxcZWMnpViZblL0A3BmHYGKEmur/Dg/n/n6lIKYqVgVAyZngwmh0X+Ze1jNot2LFAGaBL+lUE3JV3tc0ZwPFkXO4dXV4MVmoQuDGuQR69M5w7S7HrlWU654GeaT49CO9ULt6NRWyaf/Ykt72F8g175S8O+IGO/c5ahLMRLDqn5BpDtBMdgN7C/TjzsG37GLoyhfXo0ciVoUapR06eCfMcHy52CiBgjCASMU3F8prq6vcx5nfj/7SI87DpawM/vXUuIo9xd9S26OMEhYjhl1c9NrxJK/gWlccB8iokJptzu9FR4JjiIdI8x8eB7YCN+5kLlazXC/r5u/j/t+ykp3wtaI3FdMN1oK7iVAeqOWd2RHkHOvDnIUlYjfSA,iv:9YqtLPgUxbfuUAxUGqMLum2u0wQa5t1nxeVwITM2xUk=,tag:j/F8OLeXYmRaikFSShhfWA==,type:str]
    identity.pub: ENC[AES256_GCM,data:eHjYj1M/uK/+mRlWWDFelZ1jPEZb0yqZE8vjFsHiuJEUlbKNSK9tS91J6tWS4C6iBlLsBBkB6fTSw3/0Kw8E5jPUz7M7ZTEAL2gRXQ0entrXkHeAHbIX+n0Pi/pYK3HLKCd9Ox6GkUI9jTsL6vfn5eJjY6EU1CKF1/unh4zKeWlrW6cR8A8NJNR+fdnl+ycbsrfuAFhS1CYlxtUnwu45EBo7pXP/FVumIfXlmv1BQlKjcxFgSSREFfzJRpe/ZC89cj8WzBuuQ2i78KGPOA==,iv:Gfy1EygCAf8BW7m7R+AJ/H0NwbZe6EHXq/xFwF2yBso=,tag:mr8twD+uQg2WhbrNBIfGEg==,type:str]
    known_hosts: ENC[AES256_GCM,data:Z9LQMOkruv2lQ2NAVp6p4iUI+A1Y+3uvY3GqxH/G+A9Mw++ID7QLSAmcgnDBFPMTT2Lg2vhXLX+Ojf1pwHVsm7elHRB9lTgV9xRmr05FNjSBNSNXRGzn+y1FYdlpmdWuR+Fn23zTW/WLz+fRwUDZEZLs8rC2UEtc2oLuh/6ZadSAsidTGkGQJjBM0/EFz9vwnQ/7SoOyF30VscqOA2RNl1hYL+DGnnhGJde1,iv:cdMxp+IVnRhFPrIPmgh6VYTvTL6GDhiCImj4kf7BzCM=,tag:mlkp9CO8z6Gl8S17T97Cog==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19wg3490scy7jf9srcmzskv6k96nj9fx77psdqkxpt3lg66j3fcys4xndsq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGbEI3UUI5d2ZuWG54dEE0
            c0VDMm9vbHdaSm0vcDZaWWZOaDBUendtVjEwCm0xSU5BUGtuZmpuSklza3phUFRS
            aTV3c3crOFRDZjhQWXlqaDNHMGtQWnMKLS0tIHplbVNhdmlLVHJTdlE0V05GZzFV
            S2JGRi9vUEpCVTdjM1NyQlJJcWNFOHMKNJ5WD5JSd0ApeiUaVFxxS1yyVwu86FHp
            suLpwj8Bczz7yEL34wIlk+bcktZtC1IbdOuCukdXLYarZQFJAUZIFg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-26T15:06:36Z"
    mac: ENC[AES256_GCM,data:GLVfKIeuTRR8LrFyRJr9atbfWVH16pcLyKxTPBKn9wLhiNtLlOpLFlHdMyKwWQYQUjluuMUWJq+hrYmsGt5bKk/wSmjJaPfzbd0CKYpTvya4X8SxlSXjskixg4xaA3YyQvD5C4wpGzvH4aozymd2UHvBt7XzhrtaW7QebAASRfw=,iv:l6iRMgL4f9EPmstWWRdZCiNsfA2NFOgxvEOYZiLJSrs=,tag:4JaZh/h5SK3MavppJ8tInQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
