apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:viYaLACsN5EhyotOM956EtzAa427iOfWA8jEWjqQnbstszKYJ1hh/CQjx/vm9YWrhH5L44zOGrw58XPIqzaT0dGdC2kVGrZNsCFMLSjY1qKqmA4FVlqIrlZoSwJPcv9ciOtAk0kzBofxoLVkSvkVGRhBWh6gAkD0+tnwBy5q9vDU+1vRuKR5KLagZco5IsMcVXGLoWr9UT/2Eu+evFyU96WVcyumApP57O47ogZZtP6a1gwym+/NQV/hZ+T2CX661FbFc9DrohqkwvLPEXgv7qe4CjvFSRkipjeSz5HT/SB1BOhoYmuIH1fVMNSxHhCVtuC2Z25KWiXTDoclQ1VCaMXW4tI1mBrxlGY/yJRqWz/p3qFDnjgUWO5n1HBLQpUu,iv:tbf60JybneeJgHD/8wLLsT5pQOfYBuOmmOjb6rELX8I=,tag:FZD5MRluAgA9NDPF/n4IRQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:B7j2jM1wFlDXDuQZeHQ49HUEfSHj5pJfB0hDImUwHuj6xrRo2k5gSSzY0R1mB5XFBSDUNpDFDJVfRnm0glqJObhoi+pZ0EU6PEMtLagwyel9Ahx0RbSAzfQEKgTz0Sv4xagEGbFOy3LyHkOcyzYSbSotMNiZ3Q+Qoeve+UnmXW+asjm+qIwr6yBovk5oiN/c7VSon5itwh00TH3+BBkDF+oRaQc0YWSV3I4X2VwjZJQ9mpkRLZ9Tr/Cp+4R/MzAcnvMkK52ke8TWTc8vvg==,iv:dCrJqQYZVlLYy6FWkI+VPGXhi/WS/wOEgSiPqowF6FU=,tag:Lz7SIJmvEsxqjk9Tlwei8g==,type:str]
    known_hosts: ENC[AES256_GCM,data:AplfE+oSibSCindyAXyNN/q64Q6EYzK3g8rGNvqCzatbWJDGg96HHYtT16UmOYuECfeq7JRM1AsvDdTCDPgcdXtb+6PXdxJ2+lRTK+XD8C2fM0l8bQen22/GY/6UrKciIdGUTKJTlHuP/us7g/HU5hZ0wzcO+xuUoryZJRbpL+HgNIWO5TDHiEjzhasrve86eLfbwdJtgJ7NJFbbGrRD1BtnGRTUMYtnB+7X,iv:iKblWMRXNdoG5hmUQtsS4z8sdJHcu+9jeUYt+U0l73M=,tag:nOjRV6tKbZUJazE2TCzZ/w==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19wg3490scy7jf9srcmzskv6k96nj9fx77psdqkxpt3lg66j3fcys4xndsq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6ajF2c3NDZFJSTjlub3VZ
            bHRSdVBIei9SR2I0L2I5WU1hZUxLdUxZNmdzClJJRTBzVzUrODZES2hmWjd5SVNr
            Mytadkh5cS9kMzBWT1B3a0VMbmlvZnMKLS0tIEF3enRBbjdGUjI2V2JXTUZWZnEr
            eFVwY2h0Zi9TYWxUZ3c5S1NmMVMxYVkKoRBRHgy4Nr0kgDeUShhtMmIsPaYftHXa
            qz6rzLAl8KVdwbEbL3dPz4Xc/l4crO2+PO/iyBp/1LyKkNy+b0QW1g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-22T22:14:59Z"
    mac: ENC[AES256_GCM,data:VR7/yFckvRVAWoqYuav5xq8+PGfc8T6WIOzWv6ipY+umqbnusAGODZaas+n2CXnRnLxLufyXk7xDMgBOYjQHrBvjSWIIbEZKnzcngSHHR8XqFGL4jmLvtc+kKCnDoPdI6Qi+2a13JINWtKK/vVlAu7+n8mBHPf4AfPynWQG/cug=,iv:lR1Lm3YKO1EMCikkmdMeLZnJ1Gzduz/QZZj3kOhDW6o=,tag:nRAbrlreU4IVjHSuSVMdcg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
