apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:gjyMYG6mek/0tWOL7IwLGXlB23FzSqTbAXohxa6ItgC/8S6sYZJBmEDyTNyuKpWxC+AEyg+giIFdGYV1Rl9BYPiCbYfstr41foH7r4j5CYScZ0KFiidmnrPw7lwhvAOlcyxmniMyQbJnvJQKTe1W0iYWfqBI2TIiAJG+rDywfHoQS8KcuDdCeer4172lMoSgI9hzhRH4/XKSDM6JqgmewATugteZHqCHTCPatVsgyclR28wPG62jkf5JivlN0l2dsaOy0PbYsWIypOq233vqbUbvPv7i8qyjb7gHV6Xw94GrpgWol9k4zdbHCtuSrfYOrZ/5JsA+uRhfwwyW+lqlsVDNXWtU+SwN0MVYsmzj4PHkSpyF/VzKvJRwC1/eFi4x,iv:bRWI2zCI0hoGChJFdD0+WlH8yFop2GVJNT4x06Z5jh8=,tag:0nxPwf6YSQq+epme6VNJew==,type:str]
    identity.pub: ENC[AES256_GCM,data:rBsWM1doAO9EGw3ykqLLcvAcBPxagTCVDT7JYLdXi0jEDcAtigPeLavcj/oQlWYRPnMatXfVrA3NOrKkhHR6zEN2JKxvqYB5qKNdoKl+RKslrmRmu1NJ/1gDLMbds4wuaL2A//JtjTUGL+blrYeKdXa+C29TlyIr9a/gLs8gAlVBEfrvUftXbcEP0rcakW9AWW25ioYYhNSxI28Dfox5bNQnzgLxxUWePZwSsPxbqQj6qDO4ymUj1zmuYbDNVnT2i7NDFBfh5FXiZaqAkg==,iv:4+jQcJlCKjnKyQ4UesOyJdtQbXJbBwYuK+mf2+oNoOk=,tag:6kKFn/cXoYEUh/w9ZEFx9w==,type:str]
    known_hosts: ENC[AES256_GCM,data:6+0XlMJZQByg5HzYWc5HMOnD34pdTxKEvdA3NjPEtSYFyzeGZ0TB74sKZj/r3gVQR7egueSMHOSYvCHVMhFIJ/nyv3ZpYmtW/wGNcpMtJ1icu8BWBpXbBu5OZl9VwVHwrfpo22HkoC4UMgPeif6i3s4HR+z9Zy/pdkjPWD6PTUBGeIjd0t0jRiqcccUtnyELwGp8Nz4YBC7QBxtbV7/tGeGtNDe4Zwxnrkt6,iv:XFwVZoYIdFToMcbINobyIIOUTFmXbr0Qi2Y1XMuflvE=,tag:iudL0OcDLTg0fOQtsul7pg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19wg3490scy7jf9srcmzskv6k96nj9fx77psdqkxpt3lg66j3fcys4xndsq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvM2JVK0VWclMvbFV4d3Jl
            Z1VjSkd4RzFYRlFQb3hIRWI2TDFuOEZhaVcwCjdyYkdxaGorTjJBN1ZpTkN2MG9E
            bWIwTFNJbkswckpiaTBDb1ZKeVk2L2cKLS0tIEZaM3Vac1ZtVkQ3czZzb0x4cSs4
            QVFwd3JobHg5S3NoQ3VZRnRMZ1QvL00KRTSm/EtaOxqOX3rVL3cCrnr0/wJMHOW6
            9rR0sHUtm6z1K6EyGOC85nIwm1oddNpncAVnZ9od+TkPx/k2A0alRA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-22T18:05:59Z"
    mac: ENC[AES256_GCM,data:PgNIsD/MhxvSH0lP+TOlx72roJA/0GitBl55w5uU5rEMzrYoUSD6ZOCxacR5jipYl0M0C/drPO80SXHMnCAcLtUwm9MxYHdLlanh1ZvrCH/bVUXa1bLyfUze5N5e66afOh9l3atyTUix0le76jwqrpRkeg93AJaNFfYC7ENe1dg=,iv:dMjeKEcQ4VYpdWCQMQyXnpnb4aZJg7Io5bw5sRrtvjs=,tag:bO+f2G2sIgpEwqYReQr3eg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
