apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:b0Goomd0ApyDMvXfmD95ZR7iKVK8mlc/nSIPrb6ObwycseG2XVWcNcuBsErCpu9uwbLGlOhadO85rfQpceYFAhaaDs/NELzYK048xC58hh/G2tJwdhlW+ZkWcBfsSefrzQPBinXhTim5J5Em6AssnPDl7IDYL0Dp0l5FOzl8MAkYuP9Nd96ZDOf7UHRW9CtR9gxYT4FZ7gikHUUdMkqel4LDQTgPs2dMeMsUbXW47vi2s41klXkrU8HiMyK040xc1gPVjbmyems32t+igCPCxeLhaZN0plHYFnV6ItUCPeEfkWkz0Y8y3qvxu39O9qv6OCIKbW16qtrHA41jdASAAfc3/bIRPqd79/CJR5qhWmrOG5/d416dQEVu69YjGE0x,iv:Bs0wBZzcjAys3qMLunNUI7ROYeIew2efFNOx/41+Snc=,tag:iHBOdtXdXQ1AYKprOusaZw==,type:str]
    identity.pub: ENC[AES256_GCM,data:/ee8TwW9LNUg0G+hJ2pdkTLkwKL+N+VOkZ7DiLZJ2/zIZCj/8YFxDD+I5RnC2cKAYrcvOK/F16PNwFWErccNdQ1TbKAqyTCoWlrApHVKynq/YlHgxBAZuJWCmPKzXb1WFLsLMdJ5L+iMUSiG7AF9WlV1nbFrGDNP5xxTyX+DKLu3lfGgktzypU4h7tVhI0qcr7ISnImXgT+JeV8GFSwDoeimXZ1QkLVZfYH8ywBkTmj30/DxZujpWsE88X/Qd4aPnD6ICxpgi9T7VmgPBw==,iv:+TAh3UEur1NkWWZQjZnXot65rnHW/Yp/OFnhJTMQpiQ=,tag:O+279Iya/N3theM+BgLocQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:J93GBbF06I7Xu+4wTMIiPwIkvqw6v7WfbS0Z+WpjjtkGL5FzePi4xbKeMJXKmZBsnPN/FQs8g4kchyvuEAwssGhUxR0XOaYIzkGX1hAbSDYcOIf+/Sz3Jo3jz6jFpxS1pOWpAuAEthjV56vCX9N3YLoNIiJs+qsl+WbIxEJ7bMXg8k0mzvn+oABf4MmrpQReNGhfDJx8hvOKTXeJvX5wdZIMxaJox0Z7MWUi,iv:uio6hsJ+jHoFriN+E0CV/9P6vvlOEKSJ19EUDxA9oXI=,tag:pZIE0WW7+9BUQGCpO+zuXg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19wg3490scy7jf9srcmzskv6k96nj9fx77psdqkxpt3lg66j3fcys4xndsq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIV3lxL0NuKzE5UmpSK2py
            NW16SjdUeEZYY1MrVFFQSWdlUjV3ekIzSjNNCkRjSDJ6UHRIVjNwWTl2UE05TDhD
            Rmx1d2IxWXN2amFpRXdBNWFqWEFvczAKLS0tIGFRb0NYdWdhUStPdi94Nmx1S3d4
            QWRNUUNDOEVpdCtDV2RFc3RueHUxMm8KayMS/JAK8K4Q0W9zY9o+Gozj6r2MxB6f
            1glgFRxSa4b9PIHPNqw0KqO/pP0Gb52GvTxFKxDNZGhm5CNFOKMnvQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-25T21:45:21Z"
    mac: ENC[AES256_GCM,data:sRQMjwQ82B47Zlg+mtykRd1jbx7LTqkCC/+eUXvSn1pVzavGj5qjCZoyVPu6IVHip83wzbnPJKJ96MAeHaGyss+DpX26GDHDfT2QpsCdS5PwAVPsKJP1AvIoF2blRy/GWRV0pCF2iFFOFSXA02W8wGz6zna0sXvejOBF1VLdbEc=,iv:7lUrAp4jwbP4LucDxwLpVkLB/lB+CGAAXniMBZDEqgg=,tag:t1t3clVikagr6T8rfk7PgQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
