apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:O9l0fLX5QYk8QY1RAOWMqxZWi8kn6LGeFd11XbpIu+29pI1tfyxGBMPZffuC2JOABcY0qPgsdR78S9RxW3IJt+zNYnz+fkrll7weU6PPuQ84Q09Xr6S7yPLVGMd678oINImI1ng1Y826khS7DBwr1IAatbCQGXYtNLazG94Rk1smruynPIqSFD3fpRYlGrr0TlchzZEaH4D9gv9mqbiOtxpwDGdbqVbSMzaZyyYVRzf7rDgo2XeAXeg8G8K3itVKI6DHiFokd7Ugki6/+AUjPBC20aNVmAsuVv6VljJefomyfTkpUPZIziSyHnK6nKfc26w6jeBDMWA5xyZPTybKjIRx2FII3AlzYTbvzStVQWqDePrYBK7ZX3DzDbVbakET,iv:3ZXI+zQBLAcmg7UaYdo3QUYzDiBIo2Zs1J5bNqQnpVg=,tag:AYRApVIIMZSCXIrcKuzKKQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:RdF1k1k6v1Qwlop8rOUjkR9KLG9VaMfFJ0IOFcyCt4fWLgOaR+zrXPNQx/ME8d/9LzNLbKqvEmoqH1vv9v1urJS1R4obYKIi/ChEEpVP8iBeDpdiO0cG/3S/Sus8Q2Wq74l75UMY0DhJTnXxSeT48UP3lYh3iLvizGrepoSUYnZMubquon3TyXY+p+NG/n2Pj34DwE8hcIqQSlBsCInC6iw25UPE1sTm34l2kRU11xIEmEOd9rUhByYvV9vLmq6TNwbngN4rMm2Bplmflw==,iv:s41tWdOhgbOvXcd+uJEmeFTHfzUQMUq5CFec9+LD3N4=,tag:GuU8k9d4m0cj4daRfkQUAA==,type:str]
    known_hosts: ENC[AES256_GCM,data:AHrWKVOxBQWwmOxDP9nFGv0D6hyXlp+a2voMUz6nid9SqxDqkp5NoNtQldzRDP5Q/BspV9D4RU1DNWXYO30lprX/LMZN++n+PqrhlYwH/dk4ZMF+pR7PNIBXvhHEFi7QcwCdQVcEMWuIqpwoy7FLUwF6M9DqhsWD+2JocpJbuiVXpjzXzgOmcRpNXtcJh2vbackmwxNaq+q8ZFZ6HEfOmn0slK2yF6+51qJ8,iv:JqZo8ucnreFb+xQy5ppfFs7sHfZfJLd3vSPpkqBDjMc=,tag:EBhZXbKnNGMo7CG+8sQcPQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19wg3490scy7jf9srcmzskv6k96nj9fx77psdqkxpt3lg66j3fcys4xndsq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLYU1OTmNNL3RzQ1VrL1RN
            YXkrNExIUzhDeTlYWDRnY1JoOWlrNTcrSm0wCkMxSllSU1oxa1U2akRldzdwbi8y
            Rng3NGVUTGlsNUxYTUFrY29GN1hrc2MKLS0tIC93dnRxRGtKSFU3SUhQMnMxSFR1
            RlRWSjNHZ0NFdHp2RVp2RkJtTzRjdUEK1VAPXYyEA0VUOuP0sO56eEgMGLUJ3IPf
            IoANj/qCbBLxBdcItU57L4XErZEw/L13DY50e28J9onFaN0nodJmuQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-24T17:33:43Z"
    mac: ENC[AES256_GCM,data:WFG4oWbRaTA7pcS9i9QF1kGysnpPYty5bDCgGQqCeiZxrKAit4s2NGJ0aUOlzA33ocC36x6ZQzGxfAHxMYFqy6Vi/ZaC7d1FfwPVPlSVwUbdUpKH+giILbTUGm/ooxrzsDx8rv3l1Q23cLVjeJQZc9Cs0TyHaTlK22qMCDa3/hs=,iv:yPh/Na4S3lcwZetiA0kNs1CNNPvZrYPNoTcXcygyEvc=,tag:X39Mk+tniKH7BgU2wJNa7A==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
