apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:0wWIuEC+IAOmKz8U5tDiglIcnMp88cQA8bmn6jCdQzfpOq1ne/EG4fc13og36XjAmEoz2kDLVwr1jzlsuaY7gBysAthlWriNrcj72pFpBqortIhEosNQrRJhwWdFD65t9xLpropi6Wy3QNy/eqi2Yfh41NcUSZa0zneJdmaPyHUB2rsDPyVJal0mOaJ+E+o2gZpJYg6TgqRVZ1DVkrhFPjLpyQKvhMryxapGHCtAs7RGZUTzqqjB2VW3/LGhU4rJPFu1UNcPRdtL1vh6X0t1MU4OZ4iuRnb+QlusfH078Z6v8c+sfMk6yoNn2EJmdxFAep+WHlUvVNZbtjbLKA+oMOVzbaVOhC1xW20jzlWNhYCDYxlIfSjiEEQX5uowdwQu,iv:uJ5ko5YSk6Zn1FQxxaDd2Tje7QpShYHKG3Bz3v2ZUCA=,tag:V7x7hkyFLx36a/60sFHjmg==,type:str]
    identity.pub: ENC[AES256_GCM,data:6mSZLkocwxY7wpBthN8yXa2K/SCB9ac6iZEF6lZleyw4Ad1h+X9uGFDhx430RyPAr3b4EhKHucagDua66JHfpqRhCuHMoMzuX8FmRn9eWCwz9eKLVK1N+OkGMNEQISIWrPYIDbY0fhG31SWuU6SaAqUt34Akks+79y+Jeg+/wscKcWKIXGpLXpephVn8W7jLlOfC0XD1DTG7QiCj5bqodXgNDahPl3PFW4LPBrIswvXaxfuvbztU9hF0xPIEmIlz3yMA338X6Bp74wd7vw==,iv:Z986rx+p0Y1K76KH/5YWMfZhdnJ3v+gBnCFaX7gOmK8=,tag:qgEvwZFdIKU408fYcNKJJQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:N5q+/GjFjuGA9uAnszB3Bv6V4kPDKvuIB/w6aGjs3cXAYVTAqddw/PdZUG0mJbI4lqxCLs+yj1f0gGwufbM/QNSDnTS9zNSoTbc9DTO8apq+LexL3Uzgy7FhseiZRD+2LsA142yALVwNpzw2r48KniPh5I7kdO13FYa5bQ9rCfRVopmgZdBvZDfR9bKaoG1pzROnW4c2irm89PlcpM+j8Z5kaenv8D+LKTdy,iv:lgVGAaLcmE0v224RSW/G7Y1NBaokhfQvrjfkshIKcVw=,tag:gBM9EL+1IZW8AjNDfbVszw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19wg3490scy7jf9srcmzskv6k96nj9fx77psdqkxpt3lg66j3fcys4xndsq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCWk11VnhnY2prUmxCMjNN
            aTNJeFR3SFMzdGs2aFljNERpVGMvTFlmMUZZClVuV2tCUjR1R3dkdE5ENTVoY1hV
            NEo4U0R4dStxL0lGU1d5NTFFY2pOUjgKLS0tIGFvaERHZ0ZuOG8xWHhPLzZFU1Q2
            ZE1ZWm5TRzVPdW83TzVFUVZCR2ZOMzgKEfoBdf5QCRnc2HBmiu691JOG7/qy1WA4
            63IyaNoV7AjIbFPt9Oxl0zi/+hhtQyMq964B1elwTkBWoMNhg+RcBA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-22T16:37:36Z"
    mac: ENC[AES256_GCM,data:fC+Vbipj7yfuLAHOtikW4QP7naAf4fCsFALv52uMozYZLyorJoqI6lsp9jKRnX5vva+XbTot+m99v1amJccBLyYyWJpDJO1FCC+boG9sr3X0+kA5P94nI/dcu+wVgoHO734tN/PRW3nDW3o6VTI9Pl45YWktboBFG1QS5vxxpNo=,iv:aJqYY6sz0V6pmo9GaQ6Muaz99HM2hralQb/BFasX3DM=,tag:zfC6BtQlADqmJNvYj9KBdQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
