apiVersion: v1
kind: Secret
metadata:
  name: deploy-key
  namespace: flux-system
stringData:
  identity: |
    -----BEGIN EC PRIVATE KEY-----
    MIGkAgEBBDC1VW+zvy0NOEoROhMIYUPf85DxGk4DktGnX8eFVCd3M+O9kjbvUf5d
    Ejr0gp9tk22gBwYFK4EEACKhZANiAASI6VA1M8cSmBGC3tQzoQyn1h/klJC0TD1a
    Cx0qJXgNyjVlAozG/Mm7SDuHxJPjszIP86nXXQTejdhXhb4hLsBByg28vqsTjcr/
    BbwGDbQiymaEvaBSfDcrKsbJmAGtxRM=
    -----END EC PRIVATE KEY-----
  identity.pub: |
    ecdsa-sha2-nistp384 AAAAE2VjZHNhLXNoYTItbmlzdHAzODQAAAAIbmlzdHAzODQAAABhBIjpUDUzxxKYEYLe1DOhDKfWH+SUkLRMPVoLHSoleA3KNWUCjMb8ybtIO4fEk+OzMg/zqdddBN6N2FeFviEuwEHKDby+qxONyv8FvAYNtCLKZoS9oFJ8NysqxsmYAa3FEw==
  known_hosts: github.com ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEmKSENjQEezOmxkZMy7opKgwFB9nkt5YRrYMjNuG5N87uRgg6CLrbo5wAdT/y6v0mKV0U2w0WZ2YB/++Tpockg=
type: Opaque
