apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:kin/bbSu5m5r2UEyTn3Ia8pzemF9B+BO1NtA89uhvSS/Y326w1l6rhkKZtPe8x20yYthpeqJadytbEU48cSXtpDOCoWPWL4V0tRnbtGxe+tpCKq40I4XUKZvTHpUpgihwV/UX7hy7H5UHKDibQJRdQvYjWihW/Rk1Wc3jBFLJjWQ10mEBNG2Fdjimq0UilSbYFPx1e0+16UMoXaHbJ3CANBsK1dxQ1gb7qFiPZWqODKbRPFy0Y0dFuwbTMD/PUOnVhPNqa+59nrLsiNt8pQ1t7D/0gZ67/01DGEBX/TbEYltcn4r3PFyGks2UgIDvdansH5MAk2j8RQsO8FxFiuXjLHVm03MkFp9+lGDfcJdjPVwdDDbPndYp8INFEPQ/Kv4,iv:78M5BbBcEzihd7aotLI9l389jmLi/ghba/D9WITCDKQ=,tag:KtEj53PIuDc3F1COoq/ZhA==,type:str]
    identity.pub: ENC[AES256_GCM,data:dZyBbxr4FWigIiGNXr7lpAXVXduITBaHq+7hKwtfIAh1dra6F6rO4ilgcbe8gnX/3AlH6GziAJrmS3TKwTMp29Wle9A0/YFlqk9nfis5DnE0PlxEzKAAqoC06o0Q4CfqSycqVRyV2ixM/EMGrU+LRRbgqqI+inEfSbfqPERm/zxYqwdDOle4zW2NikP4eoL1/yn6buD5rpFDil8ifdOauKf9GfT/ZFfrBxZFnsNV6A06r3Pa/7LbYZlNOPJyjo4zXk/Q+6C2c/3k7P4tbA==,iv:dA4YOuQu+c2e1vyczN8qPe5PlprtIEaOm4ycpbFm96Q=,tag:dlDL/lY97dDWK4y8rE4EbA==,type:str]
    known_hosts: ENC[AES256_GCM,data:yGpQ8hXeRTloOgnYH8MBtCTwIMWFukzCuX+ovbSgTEHgYNj1boXeD1CTD5qwXbqFWSEAalv3yjXnXIykkOqtQhfFszjWKZ0FP46/6eP4JzACXNoiwFTsMDDqsdlVwICjKGtGwXRcOVwHW5wkJ9dWUEdSejnMdtLlnyjnIH1MgOux4lW0qaoHoBVlsbDL3f8KKmrLslHVZIecaqrqyWureD0hE8qbjViWlEcF,iv:4pu/blnMgv+4sQloqfGyuuz1M5k7CBIS3ACZicX7ab0=,tag:PqzS4RL65NMKtsNPX7wR9g==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19wg3490scy7jf9srcmzskv6k96nj9fx77psdqkxpt3lg66j3fcys4xndsq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCTEI0UmNoQzNGaTFEa3d3
            NTFqYUgrSHc4WHI2OFc5a2Rwd2tPUzdLdmw4CkMxMjhkb2lJVEVJZ2s1ZW5GZEl0
            Wmp1ZjM4NWlXMzl6Qk9YTFg1NnBCNlUKLS0tIE9vTThXNkwwL3hBMXRZY2E5STBL
            V0xpQmpzK1pLWW1jcGFZZ2tNVFZFcjAKybFkrhJyRRnHZoDUGh+ZDX1fiI+0R/FX
            iM8jtSRsPeTjHMfOXrQKx+OnKWcsUTwxRy+bPhUxV3AjJpZX1nDUHg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-22T15:58:58Z"
    mac: ENC[AES256_GCM,data:DklL52qxN4mqi31I4Y5aWuVcd3k4bFe1NZwlcgStI6e+WP95V2mm5e6T+CUqtPJ1Vtj3j+bShFP8a3ESaEWWOarjplPRs/Rd1uZz9ZaesIpbo2zdvZLYLplHfK4WyDIC/sNBniTl7bPPpNQGQTPpSeyarGTXCwen/hhdX3128yM=,iv:aI/015CQueU7iazteZt+lOzJWjw4oh5VIxvC6skM4tw=,tag:1bJ42WykBzjcb2Tl5llQyg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
