apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:LDJ9yQ8I36QeRgTHlSPv/DbzFPoz+ivWXwU9ZY1tzY+oRgn/9VjN+tDB43KA7IIHXGSZjnv2rHKfznCx3HRdPLx8wRZSiZ87R8OzfIRejUH88R+UTUdxXzDeG96Fs5qAiVzySXhOOWaAJ4KC0ETxi5hhpGdtWW7BgSf7tU0VYYIKgera+I1Ec0+5jPvtrzGQlj+5gIdikHCvvo1J80kYk2DXjOpziRsjrrD05n3Zx2+L9FbVJ/saMnauy46pF7weSUTNVM8CKqI2b3nUf5kuD0wWLFK+58hA8vZ0wmq3yiQwJKf4uFQRuF3Oyff/o8aNqgJKFM6z74xO92q2Svoj6YrDOvHF9wkCR+h6Izr+RV2s44Gt+xbNYrFi5ynjBIEG,iv:zribAUfQTwmc5n/AKByUJm9pA0l1XqYZ6Y+J01+CT7A=,tag:gA+XpGxOm4X0rYw3to28IQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:I80UbUUpQgQb+4lsnnmQBstHa6R7uMtvEcmYiQLI6fo3byJknfMw/Fs/XWaLd7SIGQUhMHv3HuMjkREpDvoKIqFJd6eqjmL5dtghaQhnIXP/e7sZLMdV7QDF90rhkaTkDG8nWdez7Djyy7tY3fEns0AtbjeZnBdwOjNk+Oj16wUN7fH1tM0Qw800dt4/ZuwF2f0dUSr52nMYWAPu6rqYmpeo8JAYdZsEeMXraZEnoWn6xRDSy35Em335OU15oxgcaGU7KBxwCHtr2DAipQ==,iv:ACodxsz6V4fNdA2UgBx66kWp9ZjzOlilG7ZDdBCIpW4=,tag:fMmkBrV4rOm492+Thcmarg==,type:str]
    known_hosts: ENC[AES256_GCM,data:pXzcaFWl8aisEEdsYYrDraBsXe8rZjIjq8bfRomNmN8V4sEyu46BID+7lp6pTYPX6XhaHWMNe6PDQNPZkePcwEOM2PK1r3HyoNBtPjbwWBTXtkVFStRRpVlTbEd/oAmNwC7h0YOnXoPD7aRiLb2A3FwDnqMm8H/dasOQ+0tmIAbwedxHHafcnhW4OmpwMfz/nZ6Pjj4ZcUG/tZRwRNT1ADNQZ/XtJwI6BZtU,iv:N5Mph5vcpNP2Qq98Ge4dakubN/SRgoUmE+dklS3cxCQ=,tag:LaKpFI1E88zOBuBPji7yiw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19wg3490scy7jf9srcmzskv6k96nj9fx77psdqkxpt3lg66j3fcys4xndsq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1czJlQzlWYkxPNEpscjBi
            SzV3SjVVQTJ6ZHRaditydWtjeWV6MHI2VWtVCjB3Rno3QUJoYjg1eGlUdWtBUUIx
            QlpzOTNCZHJqQkMwNDkzdE05SFFzOVkKLS0tIGh6ZlFZOW9mMDhIN3dGQ0xuNjRx
            NVdrZzF6TzI5Vm1MNEZpTjhWT0l2eWMKo6B+WzVnu1lWot7Zr7k4FaLiZuGFqF8Q
            lDWq/Bg6hrZFC/HlhLdawPZdTlyVB4X5VmOxW8lHLTwSgUm7kVjk1w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-23T11:25:23Z"
    mac: ENC[AES256_GCM,data:iWr1SD9pFxdv7Mt/YbCz3/M4ccH8+Qjz7BBw1a/FrRofvy/WgTHrsJKvp8VAUmb4j0mSboxpEZpzB94uW/49IvLtLmgdAi90ipE+cRpi8mk6ZJLVQqAKQVmcKKndvjavoZLN+XqaI3f9ujRupWav0QSsfNtoBt8o35nGDFUESIE=,iv:cc9VpG+2Xb1BIUVkpFr5+oxT5P/P6ck81fgGRT9XiHw=,tag:BKsMFsKoEh9tcSMuxKTYkA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
