apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:02AZOeE758tO2PniYKDXHXDPUzuOCB4vdU3ZwkfMmSvueF1dv5/8Ic7SSnQLH+RUsXxJ92zeQ/vnsNNvpaEk4An629sbSZzX186ziZ5tUx97PoQ+UevbdbLkf97CorY+4OdBm+p0uF697pJ5XKRTL1j9eFNDXMMGIVkb+nab6XqkDidkLjxsTpD3R61e3uATNYKbvA3cLuW1paJlK3jGMJnnzghxDQ0TCrljHl/+AJ2Nu/Ta46KclACzT1jeuWipK89IH11ktR2P/iHvyACu34nr/C0BouFLQISw8cORCgsFHcM/LuNs7ZCmzkvzHjjgwDWeIZSr6f37/GeO4FdMmPZBte7+tOcX4EaPPmkselNF3H1HJD4PE9cb1431W1ZZ,iv:8QhLvQrYwk3ANLiW5C11m9vSCy3ney4Vokh7PeqOtvU=,tag:orJOx28Q0fQTxC6r3hAS3A==,type:str]
    identity.pub: ENC[AES256_GCM,data:K+mwz/tmHsCG0Ms1CwNXfIABOYUVxN0d2qBWy5eS3fYsO6qo2pIT0n/W6i7H5KEk2GV6GnxmhRa0sDujw/5zoFXBr5AxA9Men/Ia956WL7372CG2PxJSQV81JnZxw8SD3lCQmo38VqDnjPlRWzna3fd6OpTyMUmogh4UO2sd7H2R/w5hPk3skstDoNtebJNQtWF22tY6BVpBltuEc6ndOd13guCf9Dmay6f6ePhFA2ntJCWX7q2I/76EWtckD0VPSCpUC0ZIZPzyFJibow==,iv:gNpXMqGz0FrZN/HaA35UU1qd4Z44TAdd4dcN08QwVss=,tag:yUu12dvjnXYRJko4xkS1nQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:Mvf9fkAn0pM+ikOgyTuM5HNoOtMYjOA4fKhgGyagI8qZUYJvdZznfBIRrMWsCF/MlHIufCNXpLCwGbeXuA1BNh5kkMOaPirAwk+NQyYJOn0VTA+Ud7Gj2ZMKdo86/VBPMQ1Z6dBKdyCgOJ8uPHnPylo7jDnmCRMgzJxX31xdgyQHH9Ffp1zY0WQrGgpOXV3i048pfiKEyA1UwS5zgNa3Ygslhny8w+YukJ1V,iv:i4jfPr/ZzlXy92uDVh018eoftrral+Yk6PFiaa3INpY=,tag:0B0iVNoJjDe9L4I/PXkVQw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19wg3490scy7jf9srcmzskv6k96nj9fx77psdqkxpt3lg66j3fcys4xndsq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjUDlpOTBVNFlDMnN6SHZZ
            Vi9waHJKUnhFejdGNFBWWlFRdEpKUkVXbGowClRsbE9pNVhJdnFxSTJhVWFyOHFE
            QzFWZWxDcDRxb3RUZFBUeFA1K3NtckkKLS0tIGlidE11L2F2ci85dTl4T0NXZ0Ez
            ckRUYUNkTkw2UDNVV2FpTHpuckg5SlEKzBrLbRKr5si7yh1sQSaH2+I2MWouMTQz
            bgwNYU01KuBDAn9jS+qfWS5OMCIwcjM5ZpLh+0cgblIkGrRpMR9qSA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-23T07:48:07Z"
    mac: ENC[AES256_GCM,data:l28EjsZdVhQYzC/gklX/uU/fkZ8WPakms4ItB4VGP5r0uHkfoxhZVw57WmdhPDYWwVFCcctjpKM3Dr2LIIPfLR++/zmCHIZ1GPSJEHcoI+VRnxUdn/ueefrd/YsZahkUc/y2ifcIynZcwpZIE/tGNf5iOFlcnu31LM6U9nYrtXg=,iv:VkpBwAgDYZRK/7d9N1yRVi/rXZCGKpC3wnPxYabWpyM=,tag:sW96hXJwY+JD2nwcOhvwXg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
