apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:27A8zXxlA4Ie4HZ7qKTENfvSpJ12u7Y9KhE6Nki6i6EnzwPJ/BFw4r0JpltuTRiaf58ZzJkjpMpCnyQyIlscoi9sOu/3BNi/izZgfF8UNr2mX3m1axnI1rIZXxeGj0LNx3y7UtTiotQ2MK37j70INdUzfwoHZf94nPY+8CTXvpY7QYUrkQmgWU685te6/sh/J9QzjsLG1j4RfawwyI5FLaU6VvSXJuAiUoZoAERFNk9FO45f2PsS5XVdv1KWGxX4PEV+cgYR8OE8PL85RKvxjI7j4RL/BEEMEd/ARpapI8Mfqg8EouuNOh34JiqFeETrzAbP7QYj9uJqAWfM9Hx/dEGKzkleOPgmLgRWJWZmPh2z0Ty8IrVEJiZ/kRh9kNBS,iv:J76n1yXxMbClyhh0P54AEtGe0RTCFo9uHuuBmy2KJ/c=,tag:MCt5myA9Sbg5V/5CA7qu6A==,type:str]
    identity.pub: ENC[AES256_GCM,data:UzU8hIIyoFOU8evGC4fsST67iMoFdbzVrHR7yGBKlKWwYg/J6M0lkxKqApTbcyMyvw5oGAwRAzWXn3VswHY+Nf2HRhT6OOrr60DoWswuPsQ24dSnRwGYkIfMjfOUObuMCJKsTK1iPrulEBu5WMN+gb/0IhC+BEs58Hck8pDv3eBw4hYuTF1Xy24zBAapIsyrrbRsvqxwt9ZaJYzrUzKmW3LZeZGbB2A/P57db/j/JWedclo5Gbi2IIs7xArylUZ8oWV5vkUSu2HO/k4Zow==,iv:FbQGgEHomDPVorvTjKMU8OO5PtW/s9pHGsizHUj9QnY=,tag:OV+yX3PTGtvwTalMhy6mzQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:VWicqNLxcyxwg4WxlVO/AK9W/78FT9mmiUC0zOY2FYSmNdr5VUFTfmYCKiDVM/82n291dV2Nqvj39aOe6yqW7PsOdh98jChc78O2jyJGLbRRHvMcZArBksD17LQpw0X0dyX2RFdjwuStkK1cyuH4NO8uF5Yj+szfUK1LA8WIW3kaMYb4CSQTnOLULFstMZPJgENn+TBoZhGMw3xoivy9toVGE8UAcFAOVt8d,iv:AbLdHTITvDuK/JVsdGhr/vhhhcR+wctSQ9umKN8dxpI=,tag:yzed7VgjNBHYxWYxW72LUA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19wg3490scy7jf9srcmzskv6k96nj9fx77psdqkxpt3lg66j3fcys4xndsq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzbGQ0ME1oTjJPdWlScG8z
            TDZjQ1RzLyt2T296bXlJQVpPWkxhZVhiZFNBCkUwdzZzbjdEYkRreWx4T0NPK2VG
            Mi9xOUdKanVZbmxMaE9GU1JrOGxOVTAKLS0tIFlXNmN4cFBTN0VhNG1Hb0d4cUY3
            c0hFVE1sNENxNlo4dWxYMFB1dFZpWkUKd/VpKpxFM4VYJya7VsShJ10Fa7zdcI7F
            WWo5LdUMCHKN6yL7kAmD4uO2clrME3lDzI89pI9HKaW/x/Wea7dbeQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-23T11:21:14Z"
    mac: ENC[AES256_GCM,data:TovCFyJY7yl8qnIIkP6gqfdSegnf67sTeNW5uT6eD8AGin1PgIEyIIiWENThPZBIvDbdwn5l+g7kHiIvl1LXWXm6Y6NvMO8X97x6pnGQwmWIOeIiaVpIqDjuMW5v0Iu4UyB/sNJPpbSmu3KTg19Tp0dTZc1R46DEaTWrMIAljbY=,iv:c9EwmcS0JhbdBJ6/5IsBQURpLvzBUdvOg47jjJzgdFY=,tag:Jt65Oy0fydsKPKP6y7bpeA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
