apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:OCdLtWFDNuxjuA3tHpVlicMx+Fy6o865XmL+Fa9e/INHNwhy3YHbc5zUbtYMDqoYctdL5Q1Cf3kBQsmws1pp2ifMduOHv46kkNlgpRnr1y78mPcQMf2ItNDbsdpCOEonch+bWWnEFaR1OpEXg3uuGmOmIMEI8nEg0t6JCl2LzH8eCYcb8FrsDeT3oBsE4HCfhWo5rbr4EfRwpiMi2YOlqJ0nr7A8/WBpEK63yJKPLsRDJXKM5I0ccV1R+68Mpu9K6T9N06Ri9Hak87ID1WYU78GYL6A2NsmzgOzoKYNKGtAGeiY+d/P0xN9YjhX0Jz/QljvqP9tjlFH1av4G9w2ibvlbCA175aI5+p4hfk1gP/dKBBsGbNUMcSeRDACIFZLz,iv:ct5GvBfF1lJeX4x1dOJwRf0iqAyunUoVFNhfCduPRyw=,tag:w/CQNoTfnI1aPtGeY0pK1Q==,type:str]
    identity.pub: ENC[AES256_GCM,data:uvjatLuURPHCv0cx0T0kg+SDBaZ67PoHBRSQoI1M6MnJ6JENk2+pOsEIlRQBg81S9dTkqjcajpr1npfGHyUozsS/LpgyOkxEVCAkgp29sNq6Vrze4KejczV1RCDgiw2iE5AfEuFEDIcKFDMhkWcLIzO4aAFk/GuVT5czz7f//ehgGMgT0IS23ZO4jZ4rWmSgT06Gu5Z6oC90BkrJJ4p6itvFO/+DSYrzvFcNm5bwdS78EoB/e8Wh1RL1DoJtdPldrbPdcTty7tdrmdk0tA==,iv:dKFkeihJXWignMG2vEw1uQo3Z9VRsOix7kmWqh+VLQA=,tag:aeCg18Deu8gDOUjhk7cfXg==,type:str]
    known_hosts: ENC[AES256_GCM,data:E7+0dfMVyTPA8FJHHGD+v/67b7JcVkaY27WyFbdlJKb6lMSF5zmgY0cvt4DcLzdQaKOih7CnuSaVTKSe+9JYoRQoQmTUm7hVeq/Fo9l02VhPLYtgaxWKtcIVyBQ08VdDvewz2Q12jdpOEYS2Ko/gFUtSiRrEhQifhRxbk0iwLMcahik1w2K00Ifsb+7kQ6EXmji1cQdx0HPH/CqfmgZSppfJ9+gIIy31TC/m,iv:IqXlxLugrmAoYPUMZQXg1BRuINo0oolcRW7dgYzMWTg=,tag:ytozOECvrs6xhXvcfhXRag==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19wg3490scy7jf9srcmzskv6k96nj9fx77psdqkxpt3lg66j3fcys4xndsq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNMWNuVGFUU1YxcUwwaTVn
            VmdCYzV6aG1YdmM5VmlYcjNGUzVWOXdSQm1JCmhsT2FySTFYcitUSktqMlM2NUpw
            OG9lQ0Jhb3NUV1EwU2c4TXNEK1N3SGcKLS0tIDRHd3BlbFR0YU9FblVCY3Mra3Mz
            ZU9CblZRdU5QQTJpcjQ4TVhmQTMzc0UK0fQNui9yMmFQnkK3NI5UNRYG32GTu89O
            Yq4WB430JxQC184eexp50SfvbVYIqdSI7jkTDBd1lXHz43qmG6VhkQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-26T11:37:30Z"
    mac: ENC[AES256_GCM,data:CmFJfi35gaT8oQVdXAvxivhV3sPFqnv54/GThHs6/kO3pBhMfdohpV+XppQM4qHP6N5WfgdLU8HY/ujQaUZnjdF4Dy60vBLRW2nyYSqy7VNEM5GTc4hTyzqv3Y8c3Vj/YrM4RrsUZNq8EhyQozQnWa/35A7sht/PNl83IfKsslQ=,iv:u1x1h9gLB3SoQ7Cjtcsroe9ZRTl2aog6rh+lUWEtzU4=,tag:DfLCl8mBqQQFal6EAhLtFA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
