apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:SWCmMbE1kEGjnswze1KPnLaETBqaNRDNHPTgAtpyadayoU7/r9XFaX4A9/7cyffym1jFYmZdv2BGON8/UXgMRsI/saaozIHXiqCl2zlh1eD3FpuAOYGEZ66RgAzjXZoWVg3k64INfAAaA3bQ0MpKCxO/Qn5UjKT0lYVPAHWVnFE//nNE+7zZFlrQG8Ufs1dG04I+I0z802wP16kqEjQgThA2jeZOdFIgkBZCS7S5Xl+30FAiOr3LjNIpsrLFZ/jWdwWgOgkS7hilxINirpIg9DuqI9DEoFEeLd9wfKmDleMD5V6eLdsmzh0ZPeXfa0cR/LoC+R5t154dFldEeF/g0+WvoS4/Gfc/EAnIVIUGWqfHKOGbuFnel7Bo8/Kd8MTS,iv:9mjp6pwBcL2nWHH59JDsMdqt3rdXop8gxTpJwTGjyCY=,tag:2xJGeAWKmb+2uJy5rCDwaA==,type:str]
    identity.pub: ENC[AES256_GCM,data:pgsjPMEKJmk67EX9v+wSaK8FisBztfWBVfkU8mZWhv5vYes/5t2ElfIYPByifbneJm86B9gcrpITQmmCFUhdphJwAgw7wm2mnoNq1dU7HouHl55prIqV/5YVbzW+SkYstxAbnssNwWLWzeeOSJuSDjrvLevqEzBPOLyLFNa0+64UxU3jn+pPoKvTcF/oUgWYNGBaXukuQM/Xc2qmwKoTQIYp3xv/+TEJCU9H/6P85nlWoxoU1O6tRkHOZROHTZnXQedeEqct5CGzATFjcg==,iv:SLKS5pOqRTfmz8/zLS2U4rEEWaq9rb76VMRPhYoFVH4=,tag:NgNu78O7iAmStoHV8ld6ZQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:53Y99EO7ftwl3pj4RoNkugD0E1P+3gOS7Ge1869MCtDx6jkgCNl+2W9DX/jI5iqnK+X4zkEPe9Fn55zVlwqZH9/ea24JkQCeqeDu36sPENeIPuP974ntoeW7/7yhhA8yMH5hg28tHTdqpte7gIpFbDJ0eO4CV8KByBTn68jjKimn6U3qz77L1FqBbSsR4BLPByHPmPSP9m8zGgnXbVujI79GlVFABXd1ZkeA,iv:0Rfk/HDuQz4XY5GBbcZ2niOughmoWoCZBsDuvW2ERpQ=,tag:XTX6Bqpj7Ye+LeRfc5pG2A==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19wg3490scy7jf9srcmzskv6k96nj9fx77psdqkxpt3lg66j3fcys4xndsq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNYkJrMjRxOE1RTm0ydmMw
            S0JlRVlMTEo0Rng0TUtmeFZrWVBia2s2V21jCnYrR1Npc01nbWtXdDVLZERFbWJq
            ZkF0UGxzNFgzd3ZxVnE0dm9XdGd3b1kKLS0tIHAySjBNK0ZHM0FsRkV4YWZjZ2hS
            TW5Mdm4zMGxJbk1nT0IzQ05rK2NXS3MKEXnSsk0LaQcFpGGaxzbAbZRSlMvjwjap
            GCuqr/EcK2ddYaAmaX7m9KKHDDgL+EBax5lFAWvbgLvrcfmOMZBeCA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-22T10:24:32Z"
    mac: ENC[AES256_GCM,data:udcQZM9BJftIofMqGCjcMhziA1D7hLDgzt+XPwNf1t7DcVE8nJOu8lGgVNsvz1lqaclrHuIQvbm6rTiqdyvKecQyMuDganMYo0YlRR1ux6kmrN1gQyrDFr/pdEO/VGExCPI+3AyB28rmvAYo+CM/doIgeGP6O7sZyFpP658gcVE=,iv:6ukq68gchNpK8ACVkM8XHwBnP83rOvMp6V+KxFqJXUg=,tag:uwAyVAZoYV6NCEXnjblHAA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
