apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:BsyYyjCh/6h79pVpDZ7Dsb43bV21RDqQWXnH3/gLgJurjGf7cyED7zbzFwIJzJqCRDGVaJJ6ikNKX3cCNyOSx/a56HbVxxJ309iqMV1Zo1n6wVZBwE6W+4sdFnAkqCxW+ilaTiyqaFdwidnBFCWaDxVKKJAW8qZe87hQGfY0h957Cqp5hPGE2kOr1cGN1iieKTgc+a2kMyWCnuh6knbNGx4T1HrOpRxJgasoIqy1hOzmOgScam2qq2uTtLP7T981N8DgomNZtPufCHuXT7/GqwXBsIsIJkKo8lPx9BmMmxfhy2zq1GywisAz4RjH9hg4s+RGEQjZ2wTsIApEVita2dZUUV5jNsdVGFij5+lZaAyh/PV/ObYeUbZbGGSCXQq2,iv:KIIJ+o7hFpB7Pp+n+pS8/ISf9Ibn7im1v4+35ooBFf4=,tag:mb1vhgUYK8IOsEhZlDnmBQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:lIY/JHY9lVLVGcqfki3mTZautK+/+XGP1k2MSDUlMIi4fJTdEMnEjbMeGbUFalwiP5I86xcXt8TjzqhYP688RvZREbBZCt4rePCTeyppqL3xeqQNOFSNiNBGpAPVacLRhGQr3mxKFNRwWsfBAgo5lPZSu72SfQFyIcVJVcGfQ6+XWZrvbzddueRRY7tyHxNosOoBx/XlogMOB8Vd7iKNqUrLPacVt6xqsCUO59PyxwYOGuPHbijqGJMeIsg2kK36BIPCZc+sDR1lGhdvgA==,iv:iIpWXbjOLyWpXjEyFm8PMP3zUT8HHkHoe9F897YyN5E=,tag:gUEPREL07DwAaarl5xLR8A==,type:str]
    known_hosts: ENC[AES256_GCM,data:4uwWOaq/F02Q0d/WemcNWlLc4g/1SXR9VnFcWUv+HD7OjBra7qeq91dK1GjMbESqExlC0bWWhNE5hMGCBStGFe/3jVp2zXqTFeX34QPLhoxneaRNxhgLOOugSf+/RY23mcCB/eWFFC3W5QlTo6mcbUKmQkFLB/D8IOmUZ8KpTYq2565/EUVQIKP76uyK6jDrXEa9fBwKRSIr3cno+w5w8c/+SQDGrqvFNjRM,iv:IlLCLh3NeQFvfej2VA2bNkaSPR9EZgKK7Nuv/zHuYTI=,tag:euQ1WAjWiRW2vtn2CUPzeQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19wg3490scy7jf9srcmzskv6k96nj9fx77psdqkxpt3lg66j3fcys4xndsq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5NjNuWDdDSDNmVlo3ZjUv
            WXBzOWp5L1J4WnBvQUFMOGlNS0lqcUNVVDFNCmhmRElicHlQb2cxUEk1V3RnQ0Y3
            NGJaVjZBSS8weVp3S0xWL0pjaTRWK1UKLS0tIFRFMmtxUzR2K1JVbUhvVGxyY25S
            QkI3enV6SjlsSzd6OVFhbThON3BtUEkKqMS3Knjug/X51+pgH0G9RMFQJknIX8ND
            aAFHHNM9Lf/VXL9S+vhLYZQGtnsxnZ/hlogdzE929G8C4f7jagR/UQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-25T20:32:51Z"
    mac: ENC[AES256_GCM,data:aAdaYFWY9VZnsLpaEj34dPtZOu32qN5vCwUjsjHTTdGsO2uJyOy2SGq+iccQ/X6TPcSG4cFFCOz6Q6lIl8tcXBdBHASe+XcrPySwPay5v1sgONs6YZ94ykiFZpsNVVaavl22x9tCGEfDyXnm5pM8rf6sK7u3U0ulB51L3O8N1ZA=,iv:ZVMCPfW2GI4RcWqYpwGqUB6hBsLh3fcseJwMbIGYYAs=,tag:X92l6aM/Wel0GJvVx+dw0g==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
