apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:PJOTmo4Fl+Ekws4MAqkHTI90X66qhXMkGM3MeOqlJroFrntgE7JcfTOBlEnkYqStk2tCV7k2JlBzt884xM+0xXjgaJ35v28kddlC51dLgKpBcaNeC/GtwX5gsx8Sa/nutt43y3Ir2gnWp02kSbcb2kIX59hW03Z0RelQ7tKnXSj71wuBzC9O0R74nzPhhEmvMgqNusABpg7d6hTSi9hNV2HTEG9Vkz5uOgAlsOqoYPhsf6XdVWKQ9jr1n70OMTytgQbFro4Keu5w/riWSDVFDScAzhvJKfDj8/C4n4QWhp+u9AoCHtZNDUwHd3zyEoRAZMyyJ9yxJUmygmrpTXyQTVivkAyGF1wlmhUiAj644zTPP+QNk9ggjn9Mz1K6p3KA,iv:V8nYQoq0PYoioED5iHPhoBW07D+zOczxratm1/34gnw=,tag:ZgRckVXj3Fl6kyvsb8YaPQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:Fl10500nXLIwDrat8T2ADi6HwMGQHZ0nKEwVq+NSZR/MUexx3kQl9mBRlPg9hVfWbUCBq1+9FOjhkz9eQA+1pCwxpagxzvjgBh9aRJRKyr+5xgpYVQHbjEVV2gAy0anrey4eZqBVKHf/ImfqXrPkRRrsF2Jhp7sNp1XRM5/3qUUdz7I6wDPZo9Bv8LaYgTjDQ9dUs6Pcm0D6jqu1zPEvoviV99zgetMp+z709PFt9+MA8/iQ6Z15CBkDWavRSHLXdiPQQuT2oGgl7h0q7A==,iv:EjgnZ3c7lbsWpF3Z1iTe40ILFrW8Tkf9/LmtVHh1pkA=,tag:S4FYumakcMiAxYpT8Kiugg==,type:str]
    known_hosts: ENC[AES256_GCM,data:xjM3xfNyUiTLv0yD6ZaFXnHQidL4Ur5XGBPx1oyA/OGoB4p5ege2sToq0vbh2w44rG/Hjck2AZC8nj/OfNnpW2ji2aszlXAYL+oOCewi8y6Biv0FOmiSave3jVr2lC33e5FRn8iNPjdioCeG23W+ydVOha+nIaiKUeVey3HSgbqG3PScskM0w2CkX7D+lMwKiU1f+2UKkhwqh+U3U8MPs2QgRpJ/Bm2cfPyI,iv:JtT3VfLHsBj5R8tm01KugQY5YXHht3b+JUtOODR8G2I=,tag:D9gmiqxJjmi96k9p9i0iHg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19wg3490scy7jf9srcmzskv6k96nj9fx77psdqkxpt3lg66j3fcys4xndsq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSVHNYTHlVTWtVaG9VWjM4
            QWJkallmaHpPWE5WLzNqVWJ2aVZjeTFBZzJVCnF1blBjSk1TWUNDZ0VYQWJqU0lC
            SkdIVDhWckx3Qkhkb3kzcE54SUdRYkUKLS0tIHdzdDJodEpwU2ZabElTWEIvWHBu
            dWQ3UVVNR2phSUxMbUh0eDJRakVwTG8KlJzWyqK1Kl0KLT6EreOBh1m0UyHWWuu0
            oK/I+MzcwMttqynBg6INxHexJqeXwFewdmtzxzyHCUFMhnoA7BDqHg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-22T18:00:14Z"
    mac: ENC[AES256_GCM,data:KZ0nZdx5riKW7bzHTXsL/JfT70yZU6ZGLpv6y4KRy4wtJr0BdCVgZA4gOTnt7379txqQsFPJWrp5vJQrw5LfOng4BHNu+wodie1zTlnk49wejnF1xHd3puhGhs5yQKdDjNsns/Gl3cAenWq+bPKoGaY+vMxUlSq/T7p9iK3Zjx0=,iv:f7thONyqtuUSoktd/DzfAf4P/XQu6dQzwqkwGfVmruI=,tag:j0foECpuu4d+roHeRIr8TA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
