---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: navidrome
  namespace: navidrome
spec:
  interval: 15m
  chart:
    spec:
      chart: navidrome
      version: 21.3.2
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    persistence:
      music:
        type: nfs 
        path: /mnt/AI_Storage/Music
        server: "10.0.10.10"
    ingress:
      main:
        enabled: true
        hosts:
          - host: navidrome.aivallecrosia.com
            paths:
              - path: /
          - host: navidrome.cloud.local
            paths:
              - path: /
        tls:
          - hosts:
              - navidrome.aivallecrosia.com
              - navidrome.cloud.local
        integrations:
          traefik:
            enabled: true
   