---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: wordpress-stag
  namespace: wordpress
spec:
  interval: 15m
  chart:
    spec:
      chart: wordpress
      version: 9.8.6
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    persistence:
      data:
        enabled: true
        type: nfs 
        path: /mnt/AI_SSD/Wordpress_storage/stag/data/
        server: "10.0.10.10"
        mountPath: /bitnami/mariadb
      config:
        enabled: true
        type: nfs 
        path: /mnt/AI_SSD/Wordpress_storage/stag/conf/
        server: "10.0.10.10"
        mountPath: /bitnami/wordpress
    ingress:
      wordpress:
        enabled: true
        primary: true
        hosts:
          - host: stag-wordpress.cloud.local
            paths:
              - path: /
        tls:
          - hosts:
              - stag-wordpress.cloud.local
        integrations:
          traefik:
            enabled: true
