#!/bin/bash
curr_dir=$(dirname $(realpath $BASH_SOURCE))

deactivate() {
    # reset old environment variables
    if [ -n "${_OLD_VIRTUAL_PATH:-}" ] ; then
        PATH="${_OLD_VIRTUAL_PATH:-}"
        export PATH
        unset _OLD_VIRTUAL_PATH
    fi 
    # Call hash to forget past commands. Without forgetting
    # past commands the $PATH changes we made may not be respected
    hash -r 2> /dev/null

    if [ -n "${_OLD_VIRTUAL_PS1:-}" ] ; then
        PS1="${_OLD_VIRTUAL_PS1:-}"
        export PS1
        unset _OLD_VIRTUAL_PS1
    fi
    if [ ! "${1:-}" = "nondestructive" ] ; then
    # Self destruct!
        unset -f deactivate
    fi
    unset _envTC_Activated
}
if [ -z "$_envTC_Activated" ]; then

deactivate nondestructive
_OLD_VIRTUAL_PATH="$PATH"
PATH="${curr_dir}:$(realpath ${curr_dir}/../clusterTool):$PATH"
export PATH
if [ -z "${VIRTUAL_ENV_DISABLE_PROMPT:-}" ] ; then
    _OLD_VIRTUAL_PS1="${PS1:-}"
    PS1="[TalosConfig Env] ${PS1:-}"
    export PS1
fi
hash -r 2> /dev/null
export _envTC_Activated=1

else

echo 'Talos Configure Environnement seems activated...'
echo '`deactivate` command to exit'
echo '`unset _envTC_Activated` to force reactivation'

fi
